### ISSUE TITLE
when total queue weight=0,  once a job in queue Q scheduled, other job in queue Q can not be scheduled

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1083]
/kind bug

**What happened**:
The weight of all queues in system is 0：
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  reclaimable: true
  weight: 0
```

when a pod in queue Q were scheduled, other pod in queue Q cannot be scheduled. 

we found log in scheduler:
```
I1010 10:13:48.161365       1 proportion.go:230] Queue <test>: deserved <cpu 0.00, memory 0.00>, allocated <cpu 2000.00, memory 8589934592.00, nvidia.com/gpu 0.00>, share <0>
I1010 10:13:48.161380       1 allocate.go:130] Namespace <test> Queue <test> is overused, ignore it.
```

**when totalWeight = 0,  I think it may not be necessary to check whether queue is overused。**

**Environment**:
- Volcano Version: v1.0.1
