### ISSUE TITLE
All job may be stuck, even if there is enough resources in the cluster for some jobs to run

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1096]
> /kind bug

Precondition：
1.   there are 3 gpu in cluster
2.  there are 3 queues A, B, C 
3.  a job a in queue A requests 2 gpu, and it in running status

Reproduce step：
1. create new job b,c, both need 2 gpu. And job b related to queueB, job c related to queue C
2. job a finished, and now 3 gpu in cluster are all allocatable
3. but both deserved gpu of queue B and queue C are 1.5, none of them can be scheduled.

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Please show me your volcano config and jobs&queues yaml.

**Comment by merryzhou** [comment]
volcano config:
```
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```

job yaml refer: https://github.com/volcano-sh/volcano/issues/1099#issuecomment-711487958

queue yaml:
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-volcano
spec:
  reclaimable: true
  weight: 1
```
