### ISSUE TITLE
job status is still running even if pod failed many times

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1099]
> /kind feature

**What happened**:

when set spec.restartPolicy=OnFailure, no matter how many times the pod fails，the status of the job is running 

**What you expected to happen**:

similar to k8s job（when pod failed times > BackoffLimit， job status turns to failed），may be volcano job need a similar field？

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Can you show me your job yaml? I wonder if job.spec.minAvailable is not the number of the total pods but part of pods failed. @merryzhou

**Comment by merryzhou** [comment]
nop, minAvailable == pod count

here is my yaml:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  labels:
    volcano.sh/job-type: horovod
  name: test-horovod
  namespace: test-volcano
spec:
  maxRetry: 3
  minAvailable: 3
  plugins:
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodEvicted
  queue: test-volcano
  schedulerName: volcano
  tasks:
  - name: launcher
    policies:
    - action: CompleteJob
      event: TaskCompleted
    replicas: 1
    template:
      metadata:
        labels:
          volcano.sh/job-type: horovod
        name: test-horovod
      spec:
        containers:
        - command:
          - sh
          - -c
          - mkdir -p /etc/mpi; cat /etc/volcano/worker.host | sed 's/$/& slots=1/g'
            > /etc/mpi/hostfile;mkdir -p /var/run/sshd; /usr/sbin/sshd;mpirun --allow-run-as-root
            -np 2  -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH
            -x PATH -mca pml ob1 -mca btl ^openib python /workspace/AI_algorithm/pytorch_imagenet_resnet50.py
            --batch-size=1 --epochs=1
          env:
          - name: OMPI_MCA_orte_default_hostfile
            value: /etc/mpi/hostfile
          image: horovod-py37-cuda9.0-cudnn7.6.5:test
          imagePullPolicy: Always
          name: test-horovod
          ports:
          - containerPort: 22
            name: port22
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
        restartPolicy: OnFailure
  - name: worker
    replicas: 2
    template:
      metadata:
        labels:
          volcano.sh/job-type: horovod
        name: test-horovod
      spec:
        containers:
        - command:
          - sh
          - -c
          - mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
          image: horovod-py37-cuda9.0-cudnn7.6.5:test
          imagePullPolicy: Always
          name: test-horovod
          ports:
          - containerPort: 22
            name: port22
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        restartPolicy: OnFailure
  ttlSecondsAfterFinished: 120
```

and here is vcjob status:
```
status:
  controlledResources:
    plugin-ssh: ssh
    plugin-svc: svc
  minAvailable: 3
  running: 3
  state:
    lastTransitionTime: "2020-10-19T03:08:30Z"
    phase: Running
```
here is part of launcher pod status:
```
status:
  containerStatuses:
  - containerID: docker://a7a1d1c0e84db708b9839d2b07b6fe1c74c389f9991a6017464be92b822867c5
    image: horovod-py37-cuda9.0-cudnn7.6.5:test
    lastState:
      terminated:
        containerID: docker://a7a1d1c0e84db708b9839d2b07b6fe1c74c389f9991a6017464be92b822867c5
        exitCode: 2
        finishedAt: "2020-10-19T03:12:09Z"
        reason: Error
        startedAt: "2020-10-19T03:12:04Z"
    name: test-horovod
    ready: false
    restartCount: 5
    state:
      waiting:
        message: Back-off 2m40s restarting failed container=test-horovod pod=test-horovod-launcher-0_test-volcano(4d2f4601-11b8-11eb-8915-ac1f6ba56e8a)
        reason: CrashLoopBackOff
  phase: Running
  podIP: 10.233.125.145
  qosClass: Guaranteed
  startTime: "2020-10-19T03:08:21Z"
```
