### ISSUE TITLE
Is RestartTask Action supported in  latest volcano version?

### ISSUE THREAD

**Issue by zjian-hf** [volcano-sh/volcano#1134]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
 RestartTask Action not effective when I config in task policies.

config in yaml file:
```      policies:
        - event:  PodFailed
          action: RestartTask
```

**What you expected to happen**:
  Task Pod can restart when pod was failed
**How to reproduce it (as minimally and precisely as possible)**:
1、create example.yaml file

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: "demo-1"
spec:
  schedulerName: volcano
  plugins:
    ssh: []
    env: []
    svc: ["9090"]
  maxRetry: 5
  minAvailable: 1
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx-1"
      policies:
        - event:  PodFailed
          action: RestartTask 
      template:
        metadata:
          name: web
        spec:
          nodeSelector:
            node: node003
          containers:
            - image: ubuntu:16.04
              args:
                - sh 
                - -c 
                - echo hello;sleep 20;exit 1;
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                limits:
                  cpu: 5
                  memory: 256Mi
          restartPolicy: Never
```

2、create job
     ` kubectl apply -f example.yaml`
3、query pod info, found task was not retry
     `zjian-1-default-nginx-1-0                                        0/1     Error              0          85s`

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
  master
- Kubernetes version (use `kubectl version`):
  1.15.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
ubuntu16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
