### ISSUE TITLE
Validation does not accept priorityClassName in VCjobSpec

### ISSUE THREAD

**Issue by kbroos2** [volcano-sh/volcano#1141]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Tried to deploy a job that contains a priorityClassName, but yields a validation error stating that the field is not recognized, while it is in the documentation. 

Exact error: 
`error: error validating "job1.yaml": error validating data: ValidationError(Job.spec): unknown field "priorityClassName" in sh.volcano.batch.v1alpha1.Job.spec; if you choose to ignore these errors, turn validation off with --validate=false`

example jobspec:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: myjob
  namespace: myns
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: production
  priorityClassName: regular
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: mytask
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          volumes:
            - name: secret1
              secret:
                 secretName: mysecret
                 defaultMode: 256
            - name: vol123
              persistentVolumeClaim:
                 claimName: volpv1
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            fsgroup: 1000
          containers:
            - command:
              - python3
              - /script.py
              image: mydtr.myorg.com/volcanojob:november
              name: volcano
              volumeMounts:
                      - name: secret1
                        mountPath: "/home/jovyan/.secret"
                        readOnly: true
                      - name: vol123
                        mountPath: "/home/jovyan/data"
              resources:
                requests:
                  cpu: 0.5
                limits:
                  cpu: 0.5
          restartPolicy: Never
```

**What you expected to happen**:
Just be scheduled

**How to reproduce it (as minimally and precisely as possible)**:
Setup volcano according to https://volcano.sh/en/docs/installation/ and deploy the yaml above

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.1.0
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): ubuntu LTSM 18.x
