### ISSUE TITLE
vcjob phase incorrect when job scale up

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1169]
> /kind bug

**How to reproduce it (as minimally and precisely as possible)**:
1. create a vcjob: one task, replica:2
2. wait job phase turn to running
3. update job, set replica to 0
4. we found:  vcjob status is running, and pods status are pending

```
status:
  controlledResources:
    plugin-env: env
    plugin-ssh: ssh
    plugin-svc: svc
  minAvailable: 2
  pending: 2
  retryCount: 1
  state:
    lastTransitionTime: "2020-12-02T06:55:31Z"
    phase: Running
```

**Environment**:
- Volcano Version: v1.0.1
