### ISSUE TITLE
proportion plugin can not reclaim resource in some cases

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1187]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
proportion plugin can not reclaim resource and jobs are pending

**What you expected to happen**:
proportion plugin works as design behavior

**How to reproduce it (as minimally and precisely as possible)**:
Cluster: 4 CPUs(actually workload can use 3 CPUs),  8G memory
Both queue1 and queue2 have same weight 1.

Scheduler config like:
```
actions: "enqueue, allocate, preempt, reclaim, backfill"
    configurations:
    - name: enqueue
      arguments:
        "overcommit-factor": 100
    tiers:
    - plugins:
      - name: priority
    - plugins:
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
1) Submit joba in queue1 which min=1, replica=6 each pod request 500m CPU.

2) Submit jobb1 in queue2 which min=1, replica=6 each pod request 500m CPU.
 
```
[root@wangpeng yaml]# kubectl get po
NAME         READY   STATUS    RESTARTS   AGE
joba-t1-0    1/1     Running   0          27s
joba-t1-1    1/1     Running   0          27s
joba-t1-2    1/1     Running   0          27s
joba-t1-3    1/1     Running   0          27s
joba-t1-4    1/1     Running   0          27s
joba-t1-5    1/1     Running   0          27s
jobb1-t1-0   0/1     Pending   0          16s
jobb1-t1-1   0/1     Pending   0          16s
jobb1-t1-2   0/1     Pending   0          16s
jobb1-t1-3   0/1     Pending   0          16s
jobb1-t1-4   0/1     Pending   0          16s
jobb1-t1-5   0/1     Pending   0          16s
```
Joba has 6 pods running, jobb1 can not reclaim any resources.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
