### ISSUE TITLE
'CreateContainerConfigError' on kubemark 

### ISSUE THREAD

**Issue by TomLan42** [volcano-sh/volcano#1203]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
/kind bug

**What happened**:
When submitted the example job to kubemark hollow-node with the node selector, pods are successfully scheduled and assigned to the hollow node, but the pod status shows 'CreateContainerConfigError' instead of 'Running'.

**What you expected to happen**:
No 'CreateContainerConfigError'. Pods are running.

**How to reproduce it (as minimally and precisely as possible)**:
Create a kubemark hollow node. Add a node selector to submit this job https://github.com/volcano-sh/volcano/blob/master/example/job.yaml to the hollow node.

**Comment by k82cn** [comment]
Is there any more log for this error? It seem pod template can not be parsed :)

**Comment by TomLan42** [comment]
The YAML manifest submitted is:

``` yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 6
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 20m
          restartPolicy: OnFailure
          nodeSelector:
            fake: "true"
```

The pod description is shown as 

```
Name:         test-job-default-nginx-0
Namespace:    default
Priority:     0
Node:         hollow-node-8g1c-0/10.244.0.27
Start Time:   Fri, 18 Dec 2020 11:28:49 +0800
Labels:       volcano.sh/job-name=test-job
              volcano.sh/job-namespace=default
Annotations:  scheduling.k8s.io/group-name: test-job
              volcano.sh/job-name: test-job
              volcano.sh/job-version: 0
              volcano.sh/task-spec: default-nginx
Status:       Pending
IP:           192.168.192.168
IPs:
  IP:           192.168.192.168
Controlled By:  Job/test-job
Containers:
  nginx:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:  20m
    Environment:
      VC_DEFAULT-NGINX_HOSTS:  <set to the key 'VC_DEFAULT-NGINX_HOSTS' of config map 'test-job-svc'>  Optional: false
      VC_DEFAULT-NGINX_NUM:    <set to the key 'VC_DEFAULT-NGINX_NUM' of config map 'test-job-svc'>    Optional: false
      VK_TASK_INDEX:           0
      VC_TASK_INDEX:           0
    Mounts:
      /etc/volcano from test-job-svc (rw)
      /root/.ssh from test-job-ssh (rw,path=".ssh")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fhklr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  test-job-svc:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      test-job-svc
    Optional:  false
  test-job-ssh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  test-job-ssh
    Optional:    false
  default-token-fhklr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fhklr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  fake=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From     Message
  ----    ------     ----  ----     -------
  Normal  Scheduled  16m   volcano  Successfully assigned default/test-job-default-nginx-0 to hollow-node-8g1c-0
```

```kubectl get pod``` gives:
```
NAME                       READY   STATUS                       RESTARTS   AGE
test-job-default-nginx-0   0/1     CreateContainerConfigError   0          17m
test-job-default-nginx-1   0/1     CreateContainerConfigError   0          17m
test-job-default-nginx-2   0/1     CreateContainerConfigError   0          17m
test-job-default-nginx-3   0/1     CreateContainerConfigError   0          17m
test-job-default-nginx-4   0/1     CreateContainerConfigError   0          17m
test-job-default-nginx-5   0/1     CreateContainerConfigError   0          17m
```
