### ISSUE TITLE
 podAntiAffinity not take effect

### ISSUE THREAD

**Issue by njlkj** [volcano-sh/volcano#1231]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
My cluster only has one node without taint. Deployment's `replicas` is `2` ,and set `podAntiAffinity` , and PodGroup's  `minMember` is `2`,but finally 2 pods are scheduled success on the same node(x.x.255.20).

- kubectl  get node 
```
NAME             STATUS   ROLES    AGE   VERSION
*.*.249.232   Ready    master   20d   v1.18.3
*.*.255.20    Ready    node     20d   v1.18.3
```
- podgroup & deployment
```
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: test
  namespace: default
spec:
  minMember: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx
      annotations:
        scheduling.k8s.io/group-name: test
    spec:
      schedulerName: volcano
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1200m"
          limits:
            memory: "1Gi"
            cpu: "1200m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "my-nginx"
              topologyKey: "kubernetes.io/hostname"
```

**What you expected to happen**:
Should schedule failure

**How to reproduce it (as minimally and precisely as possible)**:
`nodeSlice` is not updated when the first task is processed, i fix it by use `nodeMap` directly .

```
// NewFrameworkHandle creates a FrameworkHandle interface, which is used by k8s plugins.
//func NewFrameworkHandle(pods []*v1.Pod, nodes []*v1.Node) v1alpha1.FrameworkHandle {
//	snapshot := NewSnapshot(pods, nodes)
//	return &Framework{
//		snapshot: snapshot,
//	}
//}

func NewFrameworkHandle(pods []*v1.Pod, nodeMap map[string]*schedulernodeinfo.NodeInfo) v1alpha1.FrameworkHandle {
	snapshot := NewSnapshot(pods, nodeMap)
	snapshot.nodeInfoMap = nodeMap
	return &Framework{
		snapshot: snapshot,
	}
}

// NewSnapshot initializes a Snapshot struct and returns it.
func NewSnapshot(pods []*v1.Pod, nodeMap map[string]*schedulernodeinfo.NodeInfo) *Snapshot {
	nodeInfoMap := nodeMap
	nodeInfoList := make([]*schedulernodeinfo.NodeInfo, 0, len(nodeInfoMap))
	havePodsWithAffinityNodeInfoList := make([]*schedulernodeinfo.NodeInfo, 0, len(nodeInfoMap))
	for _, v := range nodeInfoMap {
		nodeInfoList = append(nodeInfoList, v)
		if len(v.PodsWithAffinity()) > 0 {
			havePodsWithAffinityNodeInfoList = append(havePodsWithAffinityNodeInfoList, v)
		}
	}

	s := NewEmptySnapshot()
	s.nodeInfoMap = nodeInfoMap
	s.nodeInfoList = nodeInfoList
	s.havePodsWithAffinityNodeInfoList = havePodsWithAffinityNodeInfoList

	return s
}

```

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  v1.1.0
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
