### ISSUE TITLE
volcano job created but no pods

### ISSUE THREAD

**Issue by zyyqqq** [volcano-sh/volcano#1241]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
when delete volcano job then create volcano job in shell script, pods could not be created sometimes.  shell script is:
```
kubectl delete -f pytorch-train.yaml
sleep 5s
kubectl create -f pytorch-train.yaml
```
when i exec`kubectl get pods`,  No resource found
```
~  kubectl get vj
NAME          AGE
pytorch-job   17m
~  kubectl get pods
No resources found.
```

 volcano job status is 
```
Status:
  Min Available:     2
  Retry Count:       3
  Running Duration:  1m5.558433347s
  State:
    Last Transition Time:  2020-12-31T07:42:30Z
    Phase:                 Failed
  Version:                 10
Events:
  Type    Reason         Age                From                   Message
  ----    ------         ----               ----                   -------
  Normal  ExecuteAction  16m (x3 over 16m)  vc-controller-manager  Start to execute action RestartJob
```
It can start normally if I retry to submit.

**What you expected to happen**:
volcano job can delete and start normally and stable.

**How to reproduce it (as minimally and precisely as possible)**:
create a volcano job with 2 pods, then exec script like:
```
kubectl delete -f pytorch-train.yaml
sleep 5s
kubectl create -f pytorch-train.yaml
```

**Environment**:
- Volcano Version: 1.1.0
- Kubernetes version (use `kubectl version`): v1.14.0
- Cloud provider or hardware configuration:  4 * P40
- OS (e.g. from /etc/os-release): centos 7.6
- Kernel (e.g. `uname -a`):  3.10.0-514.16.1.el7.x86_64
- Install tools: binary
- Others:

**Comment by Thor-wl** [comment]
1. please show content in `pytorch-train.yaml`
2. what's your scheduler configuration

**Comment by github-zic** [comment]
`pytorch-train.yaml` content is:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pytorch-job
  labels:
    "volcano.sh/job-type": "pytorch"
spec:
  minAvailable: 2
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
    env: []
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: pytorch-master
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          hostIPC: true
          containers:
            - command:
                - /bin/sh
                - volcano_start_pytorch_dist.sh
              image: registry.test.com/pytorch-byteps-horovod:20201210
              name: pytorch-master
              ports:
                - containerPort: 1234
                  name: master-port
              workingDir: /nfs/private/distributed-training-works/pytorch
              resources:
                requests:
                  nvidia.com/gpu: "4"
                  cpu: "16"
                  memory: "180Gi"
                limits:
                  nvidia.com/gpu: "4"
                  cpu: "16"
                  memory: "180Gi"
              env:
              - name: DISTRIBUTED_NODE_COUNT
                value: "2"
              - name: RESOURCE_NUM_GPU
                value: "4"
              - name: DISTRIBUTED_RANK
                value: "0"
              volumeMounts:
              - name: infiniband
                mountPath: /dev/infiniband
                readOnly: false
              - name: cgroup
                mountPath: /sys/fs/cgroup
              securityContext:
                capabilities:
                  add: ["ALL"]
                privileged: true
          volumes:
          - name: infiniband
            hostPath:
              path: /dev/infiniband
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
          nodeSelector:
            "volcano-test": "true"
          restartPolicy: OnFailure
    - replicas: 1
      name: pytorch-worker
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          hostIPC: true
          containers:
            - command:
                - /bin/sh
                - volcano_start_pytorch_dist.sh
              image: registry.test.com/pytorch-byteps-horovod:20201210
              name: pytorch-worker
              workingDir: /nfs/private/distributed-training-works/pytorch
              resources:
                requests:
                  nvidia.com/gpu: "4"
                  cpu: "16"
                  memory: "180Gi"
                limits:
                  nvidia.com/gpu: "4"
                  cpu: "16"
                  memory: "180Gi"
              env:
              - name: DISTRIBUTED_NODE_COUNT
                value: "2"
              - name: RESOURCE_NUM_GPU
                value: "4"
              - name: DISTRIBUTED_RANK
                value: "1"
              volumeMounts:
              - name: infiniband
                mountPath: /dev/infiniband
                readOnly: false
              - name: cgroup
                mountPath: /sys/fs/cgroup
              securityContext:
                capabilities:
                  add: ["ALL"]
                privileged: true
          volumes:
          - name: infiniband
            hostPath:
              path: /dev/infiniband
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
          nodeSelector:
            "volcano-test": "true"
          restartPolicy: OnFailure
```
`volcano-scheduler.conf` content is :
```
actions: "enqueue, reclaim, allocate, backfill, preempt"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
  - name: binpack
```

**Comment by Thor-wl** [comment]
1. Notice that you have set vcjob `policies` as follows:
``` yaml
  policies:
    - event: PodEvicted
      action: RestartJob
```
When pod is evicted, vcjob will restart. It is correspond to `Events` in vcjob status.
2. Notcie that you have configured `reclaim` and `preempt` action. It may result in preemption.
