### ISSUE TITLE
'enqueue' action loses effect when nodes in cluster had taint or labels.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#1265]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- There were 2 nodes in my cluster, 1 master and 1 node, each contained 8 CPU and 16Gi memory. I hoped my jobs only settle on node instead of master, so I added `nodeSelector` in my job.yaml. Then I created 10 jobs, each requires 4 CPU, 8Gi memory. I set args to enqueue: `overcommit-factor=1.0` to ensure the pending jobs can not turn to `inqueue` and create pods. But 10 jobs all created pods and turned to be `inqueue`:

```shell
[root@test-volcano-msr3t test]# kubectl apply -f jobs/
job.batch.volcano.sh/job0 created
job.batch.volcano.sh/job1 created
job.batch.volcano.sh/job2 created
job.batch.volcano.sh/job3 created
job.batch.volcano.sh/job4 created
job.batch.volcano.sh/job5 created
job.batch.volcano.sh/job6 created
job.batch.volcano.sh/job7 created
job.batch.volcano.sh/job8 created
job.batch.volcano.sh/job9 created
[root@test-volcano-msr3t test]# kubectl get po
NAME          READY   STATUS    RESTARTS   AGE
job0-task-0   1/1     Running   0          5s
job1-task-0   0/1     Pending   0          5s
job2-task-0   0/1     Pending   0          4s
job3-task-0   0/1     Pending   0          3s
job4-task-0   0/1     Pending   0          2s
job5-task-0   0/1     Pending   0          1s
job6-task-0   0/1     Pending   0          0s
[root@test-volcano-msr3t test]# kubectl get po
NAME          READY   STATUS    RESTARTS   AGE
job0-task-0   1/1     Running   0          12s
job1-task-0   0/1     Pending   0          12s
job2-task-0   0/1     Pending   0          11s
job3-task-0   0/1     Pending   0          10s
job4-task-0   0/1     Pending   0          9s
job5-task-0   0/1     Pending   0          8s
job6-task-0   0/1     Pending   0          7s
job7-task-0   0/1     Pending   0          6s
job8-task-0   0/1     Pending   0          5s
job9-task-0   0/1     Pending   0          4s
[root@test-volcano-msr3t test]# kubectl get pg -o yaml|grep phase
    phase: Running
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
    phase: Inqueue
```

**What you expected to happen**:

- For jobs: only 1 job be `Running`, 2 jobs be `Inqueue`, 7 jobs be `Pending`;
- For pod: only 1 pod be `Running`, 2 pod be `Pending`, no other pods;

**How to reproduce it (as minimally and precisely as possible)**:

1. make images and install from branch release-1.1
2. edit volcano-scheduler-configmap as below:
```yaml
  volcano-scheduler.conf: |
    actions: "enqueue, elect, allocate, backfill, reserve"
    configurations:
    - name: enqueue
      arguments:
        "overcommit-factor": 1.0
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
      - name: reservation
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
3. apply jobs as below:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job0
  namespace: default
spec:
  minAvailable: 1
  schedulerName: volcano
#  queue: queue1
#  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  tasks:
    - replicas: 1
      name: "task"
      template:
        metadata:
          name: task
        spec:
          schedulerName: volcano
          nodeSelector:
            kubernetes.io/hostname: 192.168.0.38
          containers:
            - image: busybox:latest
              command:
              - "bin/sh"
              - "-c"
              - "for i in {1...10}; do sleep 1000; done"
              imagePullPolicy: IfNotPresent
              name: busybox
              resources:
                requests:
                  cpu: "4"
                  memory: "8Gi"
                limits:
                  cpu: "4"
                  memory: "8Gi"
          restartPolicy: OnFailure
```

**Anything else we need to know?**:

It may cause by idle resource calculation: https://github.com/volcano-sh/volcano/blob/793a1cf6b848884bd85600007dea1e4e46917cf3/pkg/scheduler/actions/enqueue/enqueue.go#L106

1. in first session, the idle resources are calculated right, 3 jobs inqueue, 7 jobs pending.
2. but in next session, as `nodeSelector` is set, only 1 job is `Running`, so the `used resources is only 4U8G`, so another 2 jobs turn phase from `pending` to `inqueue`.
3. as session goes by, all jobs turn to `inqueue`.

**Environment**:
- Volcano Version: release-1.1
- Kubernetes version (use `kubectl version`): 1.15.6
- Cloud provider or hardware configuration:  huaweicloud
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools:
- Others:
