### ISSUE TITLE
use queue for Job

### ISSUE THREAD

**Issue by damon008** [volcano-sh/volcano#1330]
**What happened**:

create queue  named test：
```
Spec:
  Capability:
    Cpu:                    8
    Memory:                 20Gi
  Reclaimable:              true
  Weight:                   5
Status:
  State:    Open
```

create a job for the queue test:
```
tasks:
  - name: task
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 2
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - python onnx2tf.py --target_model_name VGG16; sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images
          imagePullPolicy: IfNotPresent
          name: task
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
              nvidia.com/gtx-1080-ti: "1"
```

resources is sufficient，but the job will not be allocated, and this can cause podgrouppending.

I can not see the task.

**What you expected to happen**:

I hope the job to be running.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: tag 1.1.2
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by damon008** [comment]
all in all，如果有设置Capability的话，貌似是job中申请的资源信息必须要在队列的Capability中有。例如申请中加了"nvidia.com/gtx-1080-ti"资源，则queue中Capability需要对其进行设置限制。

**Comment by damon008** [comment]
Another One:

queue like this:

```
Spec:
  Capability:
    Cpu:                     8
    Memory:                  20Gi
    nvidia.com/gtx-1080-ti:  3
  Reclaimable:               true
  Weight:                    2
Status:
  State:    Open
```

job1, two tasks:

```
  tasks:
  - name: task1
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - python onnx2tf.py --target_model_name VGG16; sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
              nvidia.com/gtx-1080-ti: "2"
          volumeMounts:
          - mountPath: /model/zkzhu0110/Onnx_example01
            name: mount-model-0
          - mountPath: /output
            name: mount-output
          - mountPath: /conf
            name: mount-cm-batch35
          - mountPath: /dev/shm
            name: mount-share-memory
          - mountPath: /data
            name: dataset-read-dir
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          resource-type: gtx1080ti
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/Onnx_example01
            type: Directory
          name: mount-model-0
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/trans_Onnx_example01
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: mount-share-memory
        - configMap:
            name: batch35
          name: mount-cm-batch35
        - name: dataset-read-dir
  - name: task2
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task2
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
              nvidia.com/gtx-1080-ti: "5"
```

two tasks all can be running.

```
  tasks:
  - name: task1
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
              nvidia.com/gtx-1080-ti: "8"
          volumeMounts:
          - mountPath: /model/zkzhu0110/Onnx_example01
            name: mount-model-0
          - mountPath: /output
            name: mount-output
          - mountPath: /conf
            name: mount-cm-batch36
          - mountPath: /dev/shm
            name: mount-share-memory
          - mountPath: /data
            name: dataset-read-dir
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          resource-type: gtx1080ti
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/Onnx_example01
            type: Directory
          name: mount-model-0
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/trans_Onnx_example01
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: mount-share-memory
        - configMap:
            name: batch36
          name: mount-cm-batch36
        - name: dataset-read-dir
  - name: task2
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task2
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
              nvidia.com/gtx-1080-ti: "5"
```

None of them  run.
