### ISSUE TITLE
queue for job

### ISSUE THREAD

**Issue by damon008** [volcano-sh/volcano#1331]
**What happened**:

create queue a:
```
Spec:
  Capability:
    Cpu:                     8
    Memory:                  20Gi
    nvidia.com/gtx-1080-ti:  3
  Reclaimable:               true
  Weight:                    2
Status:
  State:    Open
```
queue b:
```
Spec:
  Capability:
    Cpu:                     8
    Memory:                  20Gi
  Reclaimable:               true
  Weight:                    2
Status:
  State:    Open
```

and queue default.

then, create a job for queue a:

```
task1: nvidia.com/gtx-1080-ti: 2
task2: nvidia.com/gtx-1080-ti: 5
```

tasks can enqueue，but all pods are pending.

![image](https://user-images.githubusercontent.com/25023599/109136697-597a0980-7793-11eb-9772-0c81478ba3ba.png)

and queue state like this:
```
Spec:
  Capability:
    Cpu:                     8
    Memory:                  20Gi
    nvidia.com/gtx-1080-ti:  3
  Reclaimable:               true
  Weight:                    2
Status:
  Inqueue:  1
  State:    Open
Events:     <none>
```

**What you expected to happen**:

task1 can be running, but not.

but sometimes, two tasks all can be running. and the state of queue:
```
Spec:
  Capability:
    Cpu:                     8
    Memory:                  20Gi
    nvidia.com/gtx-1080-ti:  3
  Reclaimable:               true
  Weight:                    2
Status:
  State:  Open
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: tag 1.1.2
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
Can you post the configuration of your job? Is there a `MinAvailable` set? I am curious why podgroup becomes `inqueue` according to this configuration

**Comment by damon008** [comment]
@shinytang6 

job1:
```
spec:
  maxRetry: 1
  minAvailable: 2
  plugins:
    env: []
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodFailed
  queue: a
  schedulerName: volcano
  tasks:
  - name: task1
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
              nvidia.com/gtx-1080-ti: "2"
          volumeMounts:
          - mountPath: /model/zkzhu0110/Onnx_example01
            name: mount-model-0
          - mountPath: /output
            name: mount-output
          - mountPath: /conf
            name: mount-cm-batch54
          - mountPath: /dev/shm
            name: mount-share-memory
          - mountPath: /data
            name: dataset-read-dir
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          resource-type: gtx1080ti
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/Onnx_example01
            type: Directory
          name: mount-model-0
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/trans_Onnx_example01
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: mount-share-memory
        - configMap:
            name: batch54
          name: mount-cm-batch54
        - name: dataset-read-dir
  - name: task2
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task2
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
              nvidia.com/gtx-1080-ti: "5"
```


job2:

```
spec:
  maxRetry: 1
  minAvailable: 2
  plugins:
    env: []
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodFailed
  queue: a
  schedulerName: volcano
  tasks:
  - name: task1
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
              nvidia.com/gtx-1080-ti: "5"
          volumeMounts:
          - mountPath: /model/zkzhu0110/Onnx_example01
            name: mount-model-0
          - mountPath: /output
            name: mount-output
          - mountPath: /conf
            name: mount-cm-batch54
          - mountPath: /dev/shm
            name: mount-share-memory
          - mountPath: /data
            name: dataset-read-dir
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          resource-type: gtx1080ti
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/Onnx_example01
            type: Directory
          name: mount-model-0
        - hostPath:
            path: /models/_113d62e8f7c647f18fbaad7a2ec344de/trans_Onnx_example01
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: mount-share-memory
        - configMap:
            name: batch54
          name: mount-cm-batch54
        - name: dataset-read-dir
  - name: task2
    policies:
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          kind: gpu
          resource-type: gtx1080ti
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference: {}
              weight: 1
        containers:
        - args:
          - sleep 10
          command:
          - sh
          - -c
          image: 10.11.3.8:5000/user-images/zzk-model_transformation:cuda10.0-tf2.3-pytorch1.7-onnx1.7
          imagePullPolicy: IfNotPresent
          name: task2
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
              nvidia.com/gtx-1080-ti: "2"
```
