### ISSUE TITLE
Support `NodeTier` for Job and task

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1395]
#### What would you like to be added:

We will add `NodeTier` field both to `JobSpec` and `TaskSpec`

If `NodeTier` is specified in `JobSpec` and  omitted in `TaskSpec`, omitted`TaskSpec` will copy `NodeTier` from `JobSpec`

Example:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: demo
spec:
  minAvailable: 5
  schedulerName: volcano
  tasks:
    - replicas: 5
      name: worker
      nodeTier:
        # fast cpu types
        - nodeSelectorTerms:
            - matchExpressions:
                - key: cpu
                  operator: In
                  values:
                    - type-a
        # slow cpu types
        - nodeSelectorTerms:
            - matchExpressions:
                - key: cpu
                  operator: In
                  values:
                    - type-b
      template:
        metadata:
          name: worker
        spec:
          containers:
            - image: ubuntu
              imagePullPolicy: IfNotPresent
              name: worker
              resources:
                requests:
                  cpu: "1"
```

#### Why is this needed:

We have different types of CPU. It will slow down the Job If any task runs in the slow CPU nodes while most tasks run in fast CPU nodes. So our tasks need to run in the same type CPU node (all in fast CPU nodes or all in slow CPU nodes)
