### ISSUE TITLE
Support Job plugins

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#14]
Both MPI and Tensorflow need hostfile for its workers; and MPI job need more, e.g. ssh authentication. It's better to provide related plugins for different works.

The yaml file maybe similar as follow:

```yaml
spec:
  - plugins
      ssh: ["seed"]
      env: [""]
```

For example, if `ssh` is enabled, job controller should create related rsa public/private keys and mount them for ssh.
