### ISSUE TITLE
there is a OutOfcpu when applying job yaml if  node sync after pod sync in scheduler deployment 

### ISSUE THREAD

**Issue by huone1** [volcano-sh/volcano#1417]
### env
![image](https://user-images.githubusercontent.com/71266853/114528579-b9f9d300-9c7b-11eb-9d49-31df9e8bbbd7.png)

### test

```
func (sc *SchedulerCache) Run(stopCh <-chan struct{}) {
     go sc.podInformer.Informer().Run(stopCh)
     time.Sleep(10 * time.Second)  // add sleep 
     go sc.nodeInformer.Informer().Run(stopCh)
}
```

1. kubectl apply -f job-1.yaml  
2. replace scheduler image to image including the modification, restart the scheduler pod
   check the used resource info:
![image](https://user-images.githubusercontent.com/71266853/114528710-d4cc4780-9c7b-11eb-96e4-b70df53417b2.png)
3. kubectl apply -f job-2.yaml  
    there is a OutOfcpu 
![image](https://user-images.githubusercontent.com/71266853/114528949-0f35e480-9c7c-11eb-83e3-f26abfe53ad4.png)

**job-1 (2  pod  2 core/pod)**
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-1
spec:
  schedulerName: volcano
  minAvailable: 2
  tasks:
    - replicas: 2
      name: "test"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 10000"]
              imagePullPolicy: IfNotPresent
              name: running
              resources:
                limits:
                  memory: "2000Mi"
                  cpu: "2"
          restartPolicy: OnFailure
```

**job-2 (1  pod  4 core/pod)**

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-2
spec:
  schedulerName: volcano
  minAvailable: 1
  tasks:
    - replicas: 1
      name: "test"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 10000"]
              imagePullPolicy: IfNotPresent
              name: running
              resources:
                limits:
                  memory: "2000Mi"
                  cpu: "4"
          restartPolicy: OnFailure
```

**What happened**:
there is a OutOfcpu when applying job yaml if  node sync after pod sync in scheduler deployment 

**What you expected to happen**:
the created pod is pending

**How to reproduce it (as minimally and precisely as possible)**:
above 
**Anything else we need to know?**:
 Volcano Version: master branch
