### ISSUE TITLE
how to mount emptyDir and configMap hostPath as volumes in vc-job

### ISSUE THREAD

**Issue by NovaHe** [volcano-sh/volcano#1419]
I want convert pod.yaml to vc-job's pod yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    coldStartPool: "true"
    isPoolPod: "true"
    standard: test
  name: nginx
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                standard: test
            topologyKey: kubernetes.io/hostname
          weight: 100
  automountServiceAccountToken: false
  containers:
    - env:
        - name: PodName
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      image: nginx
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
              - sleep
              - "3"
      name: runtime
      resources:
        limits:
          cpu: 500m
          ephemeral-storage: 500Mi
          memory: 500Mi
        requests:
          cpu: 200m
          ephemeral-storage: 500Mi
          memory: 300Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /data/
          name: data
        - mountPath: /etc/localtime
          name: time-zone
        - mountPath: /etc/config/config.yaml
          name: config
          subPath: config.yaml
  volumes:
    - emptyDir: {}
      name: data
    - configMap:
        defaultMode: 420
        items:
          - key: key-worker
            path: config.yaml
        name: config
      name: config
    - hostPath:
        path: /etc/localtime
        type: ""
      name: time-zone
```

thanks
