### ISSUE TITLE
anti-affinity dont work

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#1428]
**What happened**:
vj like this:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  creationTimestamp: "2021-04-21T10:07:22Z"
  generation: 1
  labels:
    job_id: "544776"
    steal_cpu: "true"
  name: hobot-job-544776
  namespace: global-high
spec:
  minAvailable: 1
  plugins:
    env: []
    svc: []
  policies:
  - action: CompleteJob
    event: TaskCompleted
  queue: default
  schedulerName: volcano
  tasks:
  - name: task
    replicas: 8
    template:
      metadata:
        labels:
          job_id: "544776"
          steal_cpu: "true"
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: steal_cpu
                  operator: In
                  values:
                  - "true"
              topologyKey: kubernetes.io/hostname

```
pods:
`kubectl get po -o wide`
```
hobot-job-544776-task-0   1/1     Running     0          7m33s      train095.hogpu.cc            <none>           <none>
hobot-job-544776-task-1   1/1     Running     0          7m33s      train095.hogpu.cc            <none>           <none>
hobot-job-544776-task-2   1/1     Running     0          7m33s      train145.hogpu.cc            <none>           <none>
hobot-job-544776-task-3   1/1     Running     0          7m33s      train095.hogpu.cc            <none>           <none>
hobot-job-544776-task-4   1/1     Running     0          7m33s      train147.hogpu.cc            <none>           <none>
hobot-job-544776-task-5   1/1     Running     0          7m33s      train095.hogpu.cc            <none>           <none>
hobot-job-544776-task-6   1/1     Running     0          7m33s      train095.hogpu.cc            <none>           <none>
hobot-job-544776-task-7   1/1     Running     0          7m33s      train146.hogpu.cc            <none>           <none>
```
anti-affinity dont work
**What you expected to happen**:
anti-affinity work
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
