### ISSUE TITLE
Queue capability hard constraints have no use ?

### ISSUE THREAD

**Issue by yahaa** [volcano-sh/volcano#1463]
**What happened**:
I want to test volcano queue capability hard constraints, but the result is very strange.

There is my test case:

* default-queue.yaml

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  capability:
    cpu: 20m
    memory: 20Mi
  reclaimable: false
  weight: 1
status:
  state: Open
```

* test-queue.yaml
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  reclaimable: false
  weight: 1
  capability:
    cpu: "40m"
    memory: "40Mi"
status:
  state: Open
```

* test1.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: volcano
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "1Gi"
```

* test2.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduling.volcano.sh/queue-name: test
    spec:
      schedulerName: volcano
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "1Gi"
```

and when i apply above yaml files to k8s, i got the below scheduled result

![image](https://user-images.githubusercontent.com/16364111/117845664-592ddc80-b2b3-11eb-84ea-47214c890145.png)

**What you expected to happen**:

Neither test1 nor test2 can be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:

* edit default queue as default-queue.yaml
* kubectl apply -f test-queue.yaml
* kubectl apply -f test1.yaml
* kubectl apply -f test2.yaml

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.2.0
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-beta.1.229+fcee7a01050652", GitCommit:"fcee7a01050652e54d2819b1942533d96e40f455", GitTreeState:"clean", BuildDate:"2021-03-12T09:50:09Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

My volcano-scheduler-configmap as below

```yaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system

```

**Comment by wpeng102** [comment]
currently, volcano does not support deployment use queue `capability` to limit starting pod. When controller create `podgroup` for deployment, it does not set the `minResources` for  `podgroup`.

**Comment by nolimitkun** [comment]
It will be great to have full capability limit support for Deployment,Statefulset, Could maintainer add feature label to this Issue ?

**Comment by yahaa** [comment]
> currently, volcano does not support deployment use queue `capability` to limit starting pod. When controller create `podgroup` for deployment, it does not set the `minResources` for `podgroup`.

I tested it and felt that what you said was just one of the reasons

Here is my second test case:
* test-queue.yaml
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  reclaimable: false
  weight: 1
  capability:
    cpu: "2"
    memory: "1Gi"
```
* test2-pg.yaml 
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: test2-pg
spec:
  minMember: 1
  queue: test
  minResources:
    cpu: "2"
    memory: "1Gi"
```
* test2.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduling.k8s.io/group-name: test2-pg
        scheduling.volcano.sh/queue-name: test
    spec:
      schedulerName: volcano
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
```

and after i apply those yaml to k8s, i go the below scheduled result

![image](https://user-images.githubusercontent.com/16364111/119230042-25717300-bb4d-11eb-869d-811efd99fd1f.png)
