### ISSUE TITLE
The job completed but can't release gpu?

### ISSUE THREAD

**Issue by whybeyoung** [volcano-sh/volcano#1513]
Test a  case, if I have two gpu card, and now i put 3 job to cluster, it will schedule two job running, when the 2 job compted, the third one can't go to running and get terminated. is it ok？
![image](https://user-images.githubusercontent.com/10629930/120504138-79564480-c3f6-11eb-91f6-e9e1e78dd3b0.png)

i just make a test , and i found that  doc is not very clearly about the action and event...

**Comment by Thor-wl** [comment]
Can you give more information about the environment/resource definition/operations? Let me have a test. @berlinsaint

**Comment by berlinsaint** [comment]
> Can you give more information about the environment/resource definition/operations? Let me have a test. @berlinsaint

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pytorch-job
  namespace: deep-learning
  #labels:
  #  "volcano.sh/job-type": "pytorch"
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
    env: []
  policies:
    - event: TaskCompleted
      action: CompleteJob
  tasks:
    - replicas: 1
      name: cv-train
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          hostIPC: true
          restartPolicy: Never
          containers:
            - command:
              - bash
              - k8s-start.sh
              image: classificaiton-p4:V1.1.1
              name: cv-classify
              workingDir: /home/user/image-classification
              resources:
                requests:
                  nvidia.com/gpu: "1"
                  cpu: "16"
                  memory: "8Gi"
                limits:
                  nvidia.com/gpu: "1"
                  cpu: "16"
                  memory: "16Gi"
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: SERVICE_POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: SWIFT_ACCESS_KEY
                  value:
                - name: SWIFT_SECRET_KEY
                  value:
                - name: SWIFT_ENDPOINT
                  value:
                - name: SWIFT_CONTAINER_NAME
                  value: easydl5801074087
                - name: SWIFT_DOWNLOAD_PREFIX_PATH
                  value: cv/dataSet/base_data1395553048230629377/cv_data_type1395553048469704706/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553087854219265/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553131424649218/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553244029128705/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553283799519234/,cv/dataSet/base_data1395553048230629377/mappingInfo/
                - name: SWIFT_UPLOAD_PREFIX_PATH
                  value: cv/model/base_mode1395743218322116609/cv_train_history1398177983046356993/trainResult/
                - name: UTIL_SAVE_PATH
                  value: /home/user/original_data
                - name: CV_TRAIN_INPUT
                  value: /home/user/input
                - name: MAP_FILE
                  value: "0"
                - name: UTIL_UPLOAD_PATH
                  value: /home/user/output/best/
              volumeMounts:
              - mountPath: /etc/localtime
                name: local-time
              - mountPath: /home/user/image-classification/k8s-start.sh
                name: cv-start-train-script
                #subPath: k8s-start.sh
              - mountPath: /home/user/image-classification/swift_util
                name: swift-util
              securityContext:
                capabilities:
                  add: ["ALL"]
                privileged: true
          volumes:
            # cv train 启动脚本
            - name: cv-start-train-script
              hostPath:
                path: /data/easycv/start/k8s_start.sh
            # swift 上传、下载工具集
            - name: swift-util
              hostPath:
                path: /data/easycv/swift_util
            # 本地时间
            - name: local-time
              hostPath:
                path: /etc/localtime
                type: ""
```
