### ISSUE TITLE
considering the node occupying in queue scheduling

### ISSUE THREAD

**Issue by hacker-qian** [volcano-sh/volcano#1549]
In cluster, a user may occupy a node by setting taints. However, when a low-level queue (weight:10) user occupy a node，and high-level queue（weight:10240）users have pending jobs, the low-level user still cannot sched their jobs to their occupied node.

**Comment by william-wang** [comment]
I am not aware of your use case.  Please provide a reproduce step. @hacker-qian

**Comment by hacker-qian** [comment]
step1. user with queue1 (weight: 10) put taint on a node in the cluster, indicate that the node in the cluster is occupied by the user
![image](https://user-images.githubusercontent.com/6950081/123360725-615e8480-d5a0-11eb-85da-5fb08db7723e.png)

step2. user with queue2 (weight: 10240) create large amount of pods that run out the rest cluster resource (still have pending pods because cluster resource insufficient )

step3. user with queue1 create pods

result: user with queue1 find their pod cannot be scheduled

**Comment by wpeng102** [comment]
@hacker-qian could append  the volcano version and test yaml?  I can not reproduce this issue in my env.

```
vcctl queue list
Name                     Weight  State   Inqueue Pending Running Unknown 
default                  1       Open    0       0       0       0       
queue1                   10      Open    0       0       1       0       
queue2                   10240   Open    0       0       1       0 
```

```
kubectl get no
NAME            STATUS   ROLES    AGE    VERSION
172.16.21.168   Ready    <none>   162d   v1.19.3-r0-CCE20.11.1.B001-19.38.1
172.16.21.173   Ready    <none>   163d   v1.19.9-r1.0.0-source-67-g08638f57be7472-dirty
```

172.16.21.173 has taint.
```
kubectl describe no 172.16.21.168 |grep Taint
Taints:             <none>
kubectl describe no 172.16.21.173 |grep Taint
Taints:             occupied=queue1-user:NoSchedule
```

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: queue2-job
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue2
  policies:
    - event: PodEvicted
      action: TerminateJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 1
  tasks:
    - replicas: 5
      name: "t1"
      template:
        metadata:
          name: task1
        spec:
          containers:
            - image: centos:7
              command:
              - "bin/sh"
              - "-c"
              - "for i in 9 8 7 6 5 4 3 2 1; do sleep 2000; done"
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 1000m
                  memory: 200M
          restartPolicy: Never



apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: queue1-job
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  policies:
    - event: PodEvicted
      action: TerminateJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 1
  tasks:
    - replicas: 5
      name: "t1"
      template:
        metadata:
          name: task1
        spec:
          tolerations:
          - key: "occupied"
            operator: "Equal" 
            value: "queue1-user"
            effect: "NoSchedule"
          containers:
            - image: centos:7
              command:
              - "bin/sh"
              - "-c"
              - "for i in 9 8 7 6 5 4 3 2 1; do sleep 2000; done"
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 1000m
                  memory: 200M
          restartPolicy: Never
```


both queue1-job and queue2-job can be started.
```
kubectl get po -o wide
NAME              READY   STATUS    RESTARTS   AGE     IP           NODE            NOMINATED NODE   READINESS GATES
queue1-job-t1-0   1/1     Running   0          3m53s   10.0.0.114   172.16.21.173   <none>           <none>
queue1-job-t1-1   0/1     Pending   0          3m53s   <none>       <none>          <none>           <none>
queue1-job-t1-2   0/1     Pending   0          3m53s   <none>       <none>          <none>           <none>
queue1-job-t1-3   0/1     Pending   0          3m53s   <none>       <none>          <none>           <none>
queue1-job-t1-4   1/1     Running   0          3m53s   10.0.0.113   172.16.21.173   <none>           <none>
queue2-job-t1-0   0/1     Pending   0          4m12s   <none>       <none>          <none>           <none>
queue2-job-t1-1   1/1     Running   0          4m12s   10.0.0.184   172.16.21.168   <none>           <none>
queue2-job-t1-2   1/1     Running   0          4m12s   10.0.0.185   172.16.21.168   <none>           <none>
queue2-job-t1-3   0/1     Pending   0          4m12s   <none>       <none>          <none>           <none>
queue2-job-t1-4   1/1     Running   0          4m12s   10.0.0.186   172.16.21.168   <none>           <none>

```
