### ISSUE TITLE
GPU sharing does not preemt or reclaim jobs from from lower weight queue

### ISSUE THREAD

**Issue by igormishsky** [volcano-sh/volcano#1686]
**What happened**:
Have two servers with total of 65120 gpu-memory (using Volcano device plugin for Kubernetes).
Running 7 jobs with volcano.sh/gpu-memory: "7168" in the default queue (weight 1) and adding job in main queue (weight 7) with volcano.sh/gpu-memory: "7768". The job in the main queue is stuck in pending state

**What you expected to happen**
Adding job to queue to with higher weight did not reclaim or preempt any job with the lower weight queue.
I expect it to remove job from default queue in favor of the job in main queue. 

**How to reproduce it (as minimally and precisely as possible)**:
Install on kubernets with gpu https://github.com/volcano-sh/devices using the scheduler config provided.

Copy the template to template.yaml

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: jobName
  namespace: defaullt
  annotations:
    volcano.sh/preemptable: "true"
    volcano.sh/revocable-zone: "*"
  labels:
    volcano.sh/preemptable: "true"
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: [ "--disable-network-policy=true" ]
  maxRetry: 2
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
          annotations:
            volcano.sh/preemptable: "true"
            volcano.sh/revocable-zone: "*"
          labels:
            volcano.sh/preemptable: "true"
        spec:
          schedulerName: volcano
          containers:
            - image: busybox
              command:
                - sleep
                - "3300"
              name: sleep
              resources:
                limits:
                  volcano.sh/gpu-memory: "7168"
          restartPolicy: OnFailure

```

Run 

`for i in {1..10} ;do sed  "s/jobName/j$i/g" template.yaml | kubectl apply -f - ;done
`

Apply the the job in the main queue 
```
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: h1
  namespace: default
  annotations:
    volcano.sh/preemptable: "true"
    volcano.sh/revocable-zone: "*"
  labels:
    volcano.sh/preemptable: "true"
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: [ "--disable-network-policy=true" ]
  maxRetry: 2
  queue: main
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
          annotations:
            volcano.sh/preemptable: "true"
            volcano.sh/revocable-zone: "*"
          labels:
            volcano.sh/preemptable: "true"
        spec:  reclaimable: true
          schedulerName: volcano
          tolerations:
            - key: "gpu_only"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
            - key: gpu_cluster
              operator: "Equal"
              effect: NoSchedule
              value: "true"
          containers:
            - image: busybox
              command:
                - sleep
                - "1300"
              imagePullPolicy: IfNotPresent
              name: sleep
              resources:
                limits:
                  volcano.sh/gpu-memory: "7768"
          restartPolicy: OnFailure

```
**Anything else we need to know?**:

volcano-scheduler.conf

```
actions: "enqueue, allocate, reserve, backfill, reclaim, preempt"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
  - name: predicates
    arguments:
      predicate.GPUSharingEnable: true # enable gpu sharing.
- plugins:
  - name: drf
  - name: proportion
  - name: nodeorder

```

main queue 
```

kind: Queue
metadata:
  name: main
spec:
  weight: 7
status:
  reservation: {}
  state: Open
```

**Environment**:
- Volcano Version: master and  1.3.0
- Kubernetes version (use `kubectl version`): v1.16.15
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`):  Linux3.10.0-1160.36.2.el7.x86_64 GNU/Linux
- Install tools:
- Others:
