### ISSUE TITLE
Support ML frameworks in job plugins

### ISSUE THREAD

**Issue by LuBingtan** [volcano-sh/volcano#1697]
#### What would you like to be added:

Implement a series of plugins which can support workloads of ML frameworks, e.g. Tensorflow, Mxnet, MPI. 
With the framework plugins, users can easily create a job of a certain framework by add framework plugin in job's spec.

First, framework plugin should receive and parse plugin arguments to get some necessary parameters, and then generate environment variables which are framework specified.

For example, the tensorflow plugin may need arguements such as:

```go
workerTaskName := flagSet.StringVar("worker-name", "worker", "name of worker role task")
chiefTaskName := flagSet.StringVar("chief-name", "chief", "name of  chief role task"")
evalTaskName := flagSet.StringVar("eval-name", "evaluator", "name of  evaluator role task"")
psTaskName := flagSet.StringVar("ps-name", "ps", "name of ps role task")
port := flagSet.IntVar("port",  2222, "service port")
```

And then, framework plugin should add environment variables into pod (e.g. tensorflow plugin add `TF_CONFIG` to each pod)

So the whole volcano job spec would be like this:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: tensorflow-example
spec:
  minAvailable: 4
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    env: []
    svc: []
    # set tensorflow plugin
    tensorflow: ["--port=5000", "--worker-name=worker", "--ps-name=ps"]
  maxRetry: 2
  tasks:
  - replicas: 2
    name: worker
    policies:
    - event: TaskCompleted
      action: CompleteJob
    template:
      spec:
        containers:
        - image: example-image
          name: tensorflow
          command:
          - python
          - dist_mnist.py
  - replicas: 2
    name: ps
    template:
      spec:
        containers:
        - image: example-image
          name: tensorflow
          command:
          - python
          - dist_mnist.py
```

Contrast it with the current [tensorflow example](https://github.com/volcano-sh/volcano/blob/master/example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml), there is no need to execute complicated shell command for generating `TF_CONFIG` environment variable

https://github.com/volcano-sh/volcano/blob/6f5bb361553c7cd74aafc91a2bd05a4ded798ecb/example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml#L24

#### Why is this needed:

The Volcano job api has an excellent design on batch workload abstraction, but it is not easily to used for multiple ML workloads.

Again, let's take the [tensorflow job](https://github.com/volcano-sh/volcano/blob/master/example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml) as a example. When I want to execute a tensorflow job, I must familiar with not only tensorflow, but volcano job api and shell syntax as well.

* I must known exactly what is the content format in the file `ps.host` and `worker.host`. Generally, I have to take a look at the source code in the job plugin module.
* I must know how to execute a shell command to generate a JSON format variable `TF_CONFIG` from the file. Personally, I think it is quite complicated.

With ML framework plugins, I think it will reduce the complexity of submitting volcano job for ml workloads.
