### ISSUE TITLE
can not record queue label in metric

### ISSUE THREAD

**Issue by qiankunli** [volcano-sh/volcano#1711]
volcano version : v1.3.0 

if not set queue in podgroup, volcano-scheduler will not record  queue label in metric, so grafana can not show job normally.

```yml
Name:         mljob0902134218821
Namespace:    xdl-system
Labels:       <none>
Annotations:  <none>
API Version:  scheduling.volcano.sh/v1beta1
Kind:         PodGroup
Spec:
  Min Member:  1
```

query metric in prometheus
```
volcano_e2e_job_scheduling_duration{instance="172.31.26.74:8080",job="kubernetes-service-endpoints",job_name="mljob0902134218821",job_namespace="xdl-system",kubernetes_name="volcano-scheduler-service",kubernetes_namespace="xdl-system"}
```

it should have queue label,like 
```
volcano_e2e_job_scheduling_duration{instance="172.31.26.74:8080",job="kubernetes-service-endpoints",job_name="mljob0902134218821",job_namespace="xdl-system",kubernetes_name="volcano-scheduler-service",kubernetes_namespace="xdl-system",queue="default"}
```

allocate.go  line249

```
metrics.UpdateE2eSchedulingDurationByJob(job.Name, job.PodGroup.Spec.Queue, job.Namespace, metrics.Duration(job.CreationTimestamp.Time))
```
`job.PodGroup.Spec.Queue` may be empty, it is more properly use `queue.Name`
