### ISSUE TITLE
Gang plugin Task MinAvaliable feature PodGroup `Min Task Member` is covered

### ISSUE THREAD

**Issue by king-jingxiang** [volcano-sh/volcano#1725]
**What happened**:
create volcao job with task minAvaliable

> kubectl describe pg 
![image](https://user-images.githubusercontent.com/32818529/132168412-a29dd530-4224-49c1-8a77-229fac2d5524.png)

> Wait a few seconds, the Min Task Member is set to empty
![image](https://user-images.githubusercontent.com/32818529/132168491-d04efa57-700a-4f2a-84f6-0d8e249b90ea.png)

> and the CheckTaskMinAvailable function ji.TaskMinAvailable while be set empty.
![image](https://user-images.githubusercontent.com/32818529/132168679-5e6140d4-74f5-4480-9318-d0e15507c563.png)

> and the CheckTaskMinAvailable function **status == Pending** while add all num of pods to actual.
![image](https://user-images.githubusercontent.com/32818529/132168745-f6be3534-f8ae-4909-8c41-6ba18072e845.png)

*This will cause CheckTaskMinAvailable function to always return True*

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
hi @king-jingxiang, l just tested with master branch and set task minAvailable, but not met this problem, can you pls show your job yaml and volcano version?

**Comment by king-jingxiang** [comment]
> hi @king-jingxiang, l just tested with master branch and set task minAvailable, but not met this problem, can you pls show your job yaml and volcano version?

v1.3.0
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: task-minavaliable-jx
spec:
  minAvailable: 4
  plugins:
    env: []
    ssh: []
  queue: default
  schedulerName: volcano
  tasks:
  - name: task1
    replicas: 2
    minAvailable: 1
    template:
      spec:
        containers:
        - args:
          - sleep 60
          command:
          - sh
          - -c
          image: ubuntu:16.04
          imagePullPolicy: Always
          name: task1
          resources:
            limits:
              cpu: "4"
              memory: 32Gi
              nvidia.com/gtx-1080-ti: "9"
        restartPolicy: Never
  - name: task2
    replicas: 4
    minAvailable: 1
    template:
      spec:
        containers:
        - args:
          - sleep 120
          command:
          - sh
          - -c
          image: ubuntu:16.04
          imagePullPolicy: Always
          name: task2
        restartPolicy: Never
  - name: task3
    replicas: 4
    minAvailable: 1
    template:
      spec:
        containers:
        - args:
          - sleep 180
          command:
          - sh
          - -c
          image: ubuntu:16.04
          imagePullPolicy: Always
          name: task3
        restartPolicy: Never
```
