### ISSUE TITLE
If maxRetry is set to 1, the vcjob will not complete.

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1736]
**What happened**:

I run a vcjob, set `maxRetry` to 1, when pod is complete, the vcjob will not complete, vcjob will always be in the completing state.

**What you expected to happen**:

The job is in a completed state

**How to reproduce it (as minimally and precisely as possible)**:

1. set `maxRetry` to 1.
2. run vcjob

**Anything else we need to know?**:

vcjob
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: lm-mpi-job
spec:
  minAvailable: 3
  maxRetry: 1
  queue: default
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 2
      name: mpiworker
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
              image: volcanosh/example-mpi:0.0.1
              name: mpiworker
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
                  mkdir -p /var/run/sshd; /usr/sbin/sshd;
                  mpiexec --allow-run-as-root --host ${MPI_HOST} -np 2 mpi_hello_world > /home/re;
              image: volcanosh/example-mpi:0.0.1
              name: mpimaster
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure
```

![图片](https://user-images.githubusercontent.com/13084946/132661730-a8bc8d3a-9101-47c5-bc44-ddeb582d1f89.png)

**Environment**:
- Volcano Version: 1.3.0
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
