### ISSUE TITLE
TaskMinAvaliable is not honored in gang scheduling

### ISSUE THREAD

**Issue by Jeffwan** [volcano-sh/volcano#1755]
**What happened**:

I am trying to see what's the right behavior of `minAvailable` and `task.minAvailable`? 

I feel TaskMinAvaliable is not honored here. 

1. When scheduler calculates gang, if job level `minAvailable` < `sum(task.minAvailable)`, like <job 3, t1, 2, t2 2,>  I assume it should use maximum which is sum(task.minAvailable) as the condition in gang scheduling. in this example, it's 4 (2+2) instead 3.
2. Even job level `minAvailable` >= `sum(task.minAvailable)`, like <job 5, t1, 2, t2 2,>,  it should guarantee resource allocated to right groups. In following case, t1 get more resources which should be given to t2. 

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 5
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 6
  queue: default
  tasks:
    - replicas: 6
      minAvailable: 2
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "30"
          restartPolicy: OnFailure
    - replicas: 2
      minAvailable: 2
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "30"
          restartPolicy: OnFailure
```

```
test-job-default0-0                1/1     Running   0          5s
test-job-default0-1                0/1     Pending   0          5s
test-job-default0-2                1/1     Running   0          5s
test-job-default0-3                1/1     Running   0          5s
test-job-default0-4                0/1     Pending   0          5s
test-job-default0-5                1/1     Running   0          5s
test-job-default1-0                1/1     Running   0          5s
test-job-default1-1                0/1     Pending   0          5s -> pending, unexpected
```

```
spec:
  minMember: 5
  minResources:
    cpu: "150"
  minTaskMember:
    default0: 2
    default1: 2
  queue: default
status:
  conditions:
  - lastTransitionTime: "2021-09-21T19:39:08Z"
    message: '5/0 tasks in gang unschedulable: pod group is not ready, 5 minAvailable'
    reason: NotEnoughResources
    status: "True"
    transitionID: ccf461b0-5922-4ccd-9f43-327ad0ed2ac6
    type: Unschedulable
  - lastTransitionTime: "2021-09-21T19:39:12Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: a8f39bd7-9300-4cd3-8b3b-8c0e08beb6f4
    type: Scheduled
  phase: Running
  running: 5
```

In above case, I set 5 for job level, 2 for task group 1 and 2 for task group 2.  In this case, we have enough resources to run 5 pods, but task group 2 only have 1 pod get launched successfully. This is unexpected to me? 

**What you expected to happen**:
task group 2 should have 2 pods running

**How to reproduce it (as minimally and precisely as possible)**:
Just use my scripts.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
