### ISSUE TITLE
Cluster resource failed to rebalance by weight between queues

### ISSUE THREAD

**Issue by zhiyxu** [volcano-sh/volcano#1759]
**What happened**:
There is a cluster with 4 nodes and total allocatable resource `aliyun.com/gpu-count=19`, 2 queues are created in cluster, with `reclaimable=true` and `weight=1`
```
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  reclaimable: true
  weight: 1
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  weight: 1
  reclaimable: true
```

Then 3 volcano jobs created in test queue and running well:
```
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-1
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 1000m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  aliyun.com/gpu-count: 4
                limits:
                  aliyun.com/gpu-count: 4
          restartPolicy: Never
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-2
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 1000m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  aliyun.com/gpu-count: 4
                limits:
                  aliyun.com/gpu-count: 4
          restartPolicy: Never
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-3
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 1000m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  aliyun.com/gpu-count: 8
                limits:
                  aliyun.com/gpu-count: 8
          restartPolicy: Never
```

Then a volcano job create in default queue:

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-high-priority
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  policies:
    - event: PodEvicted
      action: RestartJob
  priorityClassName: system-cluster-critical
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          priorityClassName: system-cluster-critical
          containers:
            - command:
              - sleep
              - 1000m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  aliyun.com/gpu-count: 4
                limits:
                  aliyun.com/gpu-count: 4
          restartPolicy: Never
```

Finally the pod in default queue stuck in Pending statue:
```
# kubectl get pods | grep nginx
job-1-nginx-0                                       1/1     Running       0          75m
job-2-nginx-0                                       1/1     Running       0          75m
job-3-nginx-0                                       1/1     Running       0          75m
job-high-priority-nginx-0                           0/1     Pending       0          10m
```

**What you expected to happen**:
Due to the weight of both queue is 1 and test queue had used over 1/2 resource, the pod in default queue should preempt pod in test queue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
scheduler configuration:
```
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
        arguments:
          leastrequested.weight: 0
          mostrequested.weight: 100
          nodeaffinity.weight: 1
          podaffinity.weight: 1
          balancedresource.weight: 1
          tainttoleration.weight: 1
      - name: binpack
```

**Environment**:
- Volcano Version: v1.4.0-Beta
- Kubernetes version (use `kubectl version`): v1.18.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-514.16.1.el7.x86_64
- Install tools: 
- Others:
