### ISSUE TITLE
non-existant image causes job to wait indefinitely in "Pending" status instead of fast failing

### ISSUE THREAD

**Issue by d4l3k** [volcano-sh/volcano#1765]
**What happened**:

Launched a job with an invalid image and it hangs forever in Running with the workers in ImagePullBackOff.

```
$ vcctl job list
Name                          Creation       Phase       JobType     Replicas    Min   Pending   Running   Succeeded   Failed    Unknown     RetryCount
cifar-trainer-nwqtcjdxn0ypb   2021-09-28     Running     Batch       2           0     2         0         0           0         0           0         
```

```
$ kubectl get job.batch.volcano.sh/cifar-trainer-nwqtcjdxn0ypb -oyaml
...
status:
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  pending: 2
  state:
    lastTransitionTime: "2021-09-28T19:25:02Z"
    phase: Running
  taskStatusCount:
    worker-0:
      phase:
        Pending: 1
    worker-1:
      phase:
        Pending: 1
```

```
$ kubectl get pods/cifar-trainer-nwqtcjdxn0ypb-worker-0-0 -oyaml
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-28T19:25:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-28T19:25:03Z"
    message: 'containers with unready status: [worker-0]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-28T19:25:03Z"
    message: 'containers with unready status: [worker-0]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-28T19:25:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: dummy_image
    imageID: ""
    lastState: {}
    name: worker-0
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "dummy_image"
        reason: ImagePullBackOff
  hostIP: 192.168.32.51
  phase: Pending
  podIP: 192.168.34.3
  podIPs:
  - ip: 192.168.34.3
  qosClass: BestEffort
  startTime: "2021-09-28T19:25:03Z"
```

**What you expected to happen**:

It should try a fixed number of times and then fail the job instead of waiting indefinitely. Adding a new field to configure this or event type would be ideal.

**How to reproduce it (as minimally and precisely as possible)**:

Launch a job with an invalid docker image:

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job
spec:
  maxRetry: 0
  plugins:
    env: []
    svc: []
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 0
    name: worker-0
    policies:
    - action: RestartJob
      event: PodEvicted
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        containers:
        - command:
          - echo
          - banana 
          image: dummy_image
          name: worker
        restartPolicy: Never
```

**Anything else we need to know?**:

There doesn't seem to be a way to configure this behavior in Kubernetes. https://kubernetes.io/docs/concepts/containers/images/#imagepullbackoff

It would be nice if Volcano provided a way to handle this since in other job schedulers bad images usually by default fail fast to let the user know there's an issue as soon as possible.

**Environment**:
- Volcano Version: 1.4.0
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): Arch Linux
- Kernel (e.g. `uname -a`): Linux tristanr-arch2 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jinzhejz** [comment]
I can not reproduce this issue, could you provide more details? Here is my step:

1. a job with an invalid docker image, `batch-job.yaml`
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: batch-job
spec:
  maxRetry: 0
  plugins:
    env: []
    svc: []
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 0
    name: worker-0
    policies:
    - action: RestartJob
      event: PodEvicted
    - action: RestartJob
      event: PodFailed
    replicas: 1
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        nodeSelector:
          kubernetes.io/hostname: 10.1.22.115 
        containers:
        - command:
          - sleep
          - "360000" 
          image: dummy_image
          name: worker
        restartPolicy: Never
```

2. create volcano job
```
$ kubectl apply -f batch-job.yaml 
job.batch.volcano.sh/batch-job created
```

3. check volcano job status, it is pending
```
$ kubectl get pod
NAME                   READY   STATUS             RESTARTS   AGE
batch-job-worker-0-0   0/1     ImagePullBackOff   0          27s
```

```
$ kubectl get pod batch-job-worker-0-0 -o yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T09:05:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T09:05:11Z"
    message: 'containers with unready status: [worker]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T09:05:11Z"
    message: 'containers with unready status: [worker]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T09:05:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: dummy_image
    imageID: ""
    lastState: {}
    name: worker
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "dummy_image"
        reason: ImagePullBackOff
  hostIP: 10.1.22.115
  phase: Pending
  podIP: 10.0.0.239
  podIPs:
  - ip: 10.0.0.239
  qosClass: BestEffort
  startTime: "2021-09-30T09:05:11Z"
```

```
$ vcctl job list
Name        Creation       Phase       JobType     Replicas    Min   Pending   Running   Succeeded   Failed    Unknown     RetryCount
batch-job   2021-09-30     Pending     Batch       1           1     1         0         0           0         0           0        
```

```
$ kubectl get vj batch-job -o yaml
...
status:
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 1
  pending: 1
  state:
    lastTransitionTime: "2021-09-30T09:05:10Z"
    phase: Pending
  taskStatusCount:
    worker-0:
      phase:
        Pending: 1
```

4. Environment:

* Volcano Version: 1.4.0
* Kubernetes version (use kubectl version): Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-r1-CCE21.3.1.B003-19.38.2", GitCommit:"e796d381b893b3adcf99c50873f28fd6ef7cd7b1", GitTreeState:"clean", BuildDate:"2021-03-23T12:40:52Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
* Kernel (e.g. uname -a): Linux oversold-test-00174 4.18.0-147.5.1.6.h431.eulerosv2r10.hulk.sched.mem.v1.6.x86_64+ #1 SMP Thu May 20 12:10:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
