### ISSUE TITLE
nvidia.com/gpu is not considered by default in binpack scheduler

### ISSUE THREAD

**Issue by mkkb473** [volcano-sh/volcano#1844]
#### What would you like to be added:
nvidia.com/gpu should be considered as a default resource, like CPU and memory.
https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/binpack/binpack.go#L40
And in some GPU related [guide](https://github.com/volcano-sh/volcano/blob/e2230119e322677712ced70c6cba4d8bf1f77561/docs/user-guide/how_to_use_gpu_sharing.md), binpack does not consider GPU either.

#### Why is this needed:
People who is new to Volcano and would like to use binpack scheduling to save machine can hardly ever find that GPU is not considered by default. They usually would experience the following steps:
1. Find binpack is already set [here](https://github.com/volcano-sh/volcano/blob/51da227627008a8b653742e31dfdc3f151f41690/installer/helm/chart/volcano/config/volcano-scheduler.conf) and hope it would save GPU;
2. Notice that pods using GPU are still scattered in different machine;
3. Spend time on debugging, finally found this issue or even discovered it in source code that only CPU & mem are considered in scheduling by default, though nvidia/gpu is already listed in the [comment](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/binpack/binpack.go#L108)

**Comment by Thor-wl** [comment]
As GPU is kind of heterogeneous equipments, I think it is more suitable to add a parameter to enable to consider GPU for binpack plugin in the scheduler configuration.

**Comment by shinytang6** [comment]
I agree that it should be optional while not default, but of course the usage should be more prominent.

**Comment by k82cn** [comment]
yes, and let's improve the doc, log & guidance :)

**Comment by CaRRotOne** [comment]
is there  any binpack useage for nvidia gpus?

**Comment by gengwg** [comment]
I tested following config, and GPU bin packing worked for us. Hope it helps someone else who googled here like myself. Thanks for the great work.

```
    actions: "enqueue, reclaim, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
        arguments:
                 binpack.weight: 10
                 binpack.cpu: 1
                 binpack.memory: 1
                 binpack.resources: nvidia.com/gpu
                 binpack.resources.nvidia.com/gpu: 10
```
