### ISSUE TITLE
Cross-namespace preemption keeps repeating but low priority task keeps getting allocated before the high priority task

### ISSUE THREAD

**Issue by kenoung** [volcano-sh/volcano#1855]
**What happened**:
A lower priority task gets preempted by a higher priority task of a different namespace, but keeps getting reallocated. It then gets preempted again, and the cycle repeats.

**What you expected to happen**:
Higher priority task should get allocated, and lower priority task should be pending.

**How to reproduce it (as minimally and precisely as possible)**:
I adapted the simplified setup from [this other issue](https://github.com/volcano-sh/volcano/issues/1772).
`volcano-scheduler.conf`
```
actions: "enqueue, allocate, preempt, backfill"
tiers:
- plugins:
  - name: priority
  # only need gang plugin for JobStarving function if not on master branch
  - name: gang
     enablePreemptable: false
- plugins:
  - name: predicates
```

Create a queue, two priority classes and two namespaces.
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: prod-queue
spec:
  weight: 1
  reclaimable: True
  capability:
    cpu: 4000m
    memory: 4G
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
---
kind: Namespace
apiVersion: v1
metadata:
  name: a
  labels: 
    name: a
---
kind: Namespace
apiVersion: v1
metadata:
  name: b
  labels: 
    name: b
```

Start a low priority job using up all the cpu.
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob-low-pri
  namespace: a
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: low-priority
  policies:
    - event: PodEvicted
      action: RestartTask
  maxRetry: 100
  queue: prod-queue
  tasks:
    - replicas: 1
      name: "x"
      template:
        metadata:
          name: core
        spec:
          priorityClassName: low-priority
          terminationGracePeriodSeconds: 10
          containers:
            - image: alpine:3
              imagePullPolicy: IfNotPresent
              name: main
              command: ['sh', '-c', "sleep 600000"]
              resources:
                requests:
                  cpu: "4"
                  memory: "256Mi"
          restartPolicy: OnFailure
```

Start a high priority job.
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob-high-pri
  namespace: b
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartTask
  maxRetry: 100
  queue: prod-queue
  tasks:
    - replicas: 1
      name: "x"
      template:
        metadata:
          name: core
        spec:
          priorityClassName: high-priority
          terminationGracePeriodSeconds: 10
          containers:
            - image: alpine:3
              imagePullPolicy: IfNotPresent
              name: main
              command: ['sh', '-c', "sleep 600000"]
              resources:
                requests:
                  cpu: "4"
                  memory: "256Mi"
          restartPolicy: OnFailure
```

Observe that the low priority pod will get terminated, then another pod will get started to take its place. The new low-priority pod will start, then gets terminated again, and the process repeats. 

**Anything else we need to know?**:
This is my current understanding of the issue. In the preempt phase, we find lower priority tasks to preempt, and if we succeed, we pipeline the higher priority task. However, this pipeline status does not get carried over to the next iteration. When we open a new session, the preempted job has started a new pending pod to take its place. If we encounter the lower priority task first, and the node has sufficient resources, then we'll allocate it, which brings us back to our original state. 

Note that this issue occurs only when the high-pri job's namespace is after the low-pri job's namespace. If we swap their namespaces i.e. start the low-pri job in namespace b, then start the high-pri job in namespace a, this issue does not occur. The preemption of the low-pri job and allocation of the high-pri job will succeed.

**Environment**:
- Volcano Version: v1.4
- Kubernetes version (use `kubectl version`): Client 1.19, Server 1.21
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
