### ISSUE TITLE
RestartTask on PodFailed does not recreate failed pod

### ISSUE THREAD

**Issue by ponner-github** [volcano-sh/volcano#1866]
**What happened**:
`RestartTask` action only works with `PodEvicted` event and not with `PodFailed` event.

 When pod fails, job controller registers the `RestartTaskAction` and performs a [SyncJob](https://github.com/volcano-sh/volcano/blob/release-1.2/pkg/controllers/job/job_controller_actions.go#L191)  but pod is not recreated and remains in error state.

Snippet of controller logs [here](https://gist.github.com/ponner-github/ea6ee804d14e1e10ccbcba88417a9da2)

##### How is pod failure simulated
The simple example Jobspec below simulates Podfailure on Task replica `master-0` by having the container exit with a non-zero code.
##### How is pod eviction simulated
Pod evictions are simulated by manually deleting the po with kubectl
`kubectl delete po {pod-name}`

**What you expected to happen**:
RestartTask action should recreate failed pod on `PodFailed`

**How to reproduce it (as minimally and precisely as possible)**:
#### Jobspec
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-pod-failure-restart-task
  namespace: volcano-test
spec:
  minAvailable: 4
  maxRetry: 1
  plugins:
    env: []
    svc: []
  policies:
  - action: RestartTask
    events:
    - PodEvicted
    - PodFailed
  queue: default
  tasks:
  - name: master
    replicas: 1
    template:
      metadata: {}
      spec:
        containers:
        - args:
          - -c
          - |-
            /bin/sleep 30;
            echo "GOING TO DIE: $(date)";
            exit 1;
          command:
          - sh
          image: ubuntu:20.04
          name: container-0
          resources:
            limits:
              cpu: "4"
              memory: 32Gi
            requests:
              cpu: "4"
              memory: 32Gi
        restartPolicy: Never
        terminationGracePeriodSeconds: 90
  - name: worker
    replicas: 3
    template:
      metadata: {}
      spec:
        containers:
        - args:
          - -c
          - |-
            echo "sleeping 10 minutes";
            /bin/sleep 600;
          command:
          - sh
          image: ubuntu:20.04
          name: container-0
          resources:
            limits:
              cpu: "4"
              memory: 32Gi
            requests:
              cpu: "4"
              memory: 32Gi
        restartPolicy: Never
        terminationGracePeriodSeconds: 90
```
#### kubectl get po
master-0 pod runs and errors out,i.e. in `PodFailed`, however RestartTask does not re-create the failed pod as evidenced by the age of the pod. 
```
volcano-pod-failure-restart-task-master-0   0/1     Error              0          13m
volcano-pod-failure-restart-task-worker-0   0/1     Completed          0          13m
volcano-pod-failure-restart-task-worker-1   0/1     Completed          0          13m
volcano-pod-failure-restart-task-worker-2   0/1     Completed          0          13m
```
**Anything else we need to know?**:

**Environment**:
- Volcano Version: release-1.2
- Kubernetes version (use `kubectl version`): v1.19.14-gke.1900
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
