### ISSUE TITLE
error to calculate minresources value for pod create by deployment

### ISSUE THREAD

**Issue by lucming** [volcano-sh/volcano#1877]
**What happened**:
this is deployemnt i defined:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        #create test queue and use this annotation
        #to make deployment be scheduled into test queue
        scheduling.volcano.sh/queue-name: test
    spec:
      # set spec.schedulerName to 'volcano' instead of
      # 'default-scheduler' for deployment.
      schedulerName: volcano
      nodeSelector:
        kubernetes.io/hostname: stark01
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1
```

**What you expected to happen**:
![截屏2021-12-03 19 08 35](https://user-images.githubusercontent.com/32814765/144592715-57fec591-66f0-4cb7-9daf-2db35bdb4850.png)
![image](https://user-images.githubusercontent.com/32814765/144595770-7d2999bc-a44f-42f7-8cbf-dcf241b84534.png)
![image](https://user-images.githubusercontent.com/32814765/144595895-e8e358e0-d6be-4b79-b44d-7439f7680757.png)

minresource value is the requests value from pod, i think it maybe use requests(pod)*replica
![image](https://user-images.githubusercontent.com/32814765/144597514-a61ed713-befe-4a7d-ae9c-119043cf88b0.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
