### ISSUE TITLE
Pods remain in `Completing` state, inconsistent with specified lifecycle policy

### ISSUE THREAD

**Issue by kye308** [volcano-sh/volcano#1956]
**What happened**: Pods in a job remain in `Running` even though another task with policy `CompleteJob` on `TaskSucceeded` has completed.

**What you expected to happen**: Pods are completed after the task has completed.

**How to reproduce it (as minimally and precisely as possible)**:

vcjob yaml used
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vc14-test-1
spec:
  minAvailable: 3
  plugins:
    env: []
    svc: []
  policies:
  - action: RestartTask
    events:
    - PodEvicted
  - action: TerminateJob
    events:
    - PodFailed
  queue: default
  tasks:
  - name: driver
    policies:
    - action: CompleteJob
      events:
      - TaskCompleted
    replicas: 1
    template:
      spec:
        containers:
        - args:
          - -c
          - "echo Driver Started!; sleep 20; echo Still working...; sleep 20; echo Job Finished!" 
          command:
            - /bin/sh
          image: ubuntu:20.04
          name: container-0
          volumeMounts:
          - mountPath: /dev/shm
            name: bigger-shm
        restartPolicy: Never
        terminationGracePeriodSeconds: 90
        volumes:
        - emptyDir:
            medium: Memory
          name: bigger-shm
  - name: worker
    replicas: 2
    template:
      spec:
        containers:
        - args:
          - -c
          - "echo worker Started!; sleep 450; echo Still working...; sleep 450; echo Job Finished!" 
          command:
            - /bin/sh
          image: ubuntu:20.04
          name: container-0
          volumeMounts:
          - mountPath: /dev/shm
            name: bigger-shm
        restartPolicy: Never
        terminationGracePeriodSeconds: 90
        volumes:
        - emptyDir:
            medium: Memory
          name: bigger-shm
```

vcjob status
```
status:
  minAvailable: 3
  running: 2
  runningDuration: 45.576421357s
  state:
    lastTransitionTime: "2022-01-13T22:16:09Z"
    phase: Completing
  succeeded: 1
  taskStatusCount:
    driver:
      phase:
        Succeeded: 1
    worker:
      phase:
        Running: 2
  version: 3
```

Pods finally were completed after almost 24 hours. 

**Anything else we need to know?**: 
This was previously working on version 1.3.0. Pods would be marked completed within 10 minutes.

**Environment**:
- Volcano Version: 1.4.0
