### ISSUE TITLE
tasks in gang unschedulable

### ISSUE THREAD

**Issue by CaRRotOne** [volcano-sh/volcano#1959]
**What happened**:
I use [kubedl](https://github.com/kubedl-io/kubedl)  which specify volcano as scheduler submit a pytroch training jobs.  The request GPU resource  is 2 and the available GPU resource of cluster is 2. After I submit the job, I find the pod is pending, and scheduling is failed.
![image](https://user-images.githubusercontent.com/2860023/149449016-e77bb769-bd02-498c-a31c-15f27fa1bf57.png)

The training job yaml 
```yaml
apiVersion: training.kubedl.io/v1alpha1
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: kubeflow-pytorch-dist-mnist-test
              args: ["--backend", "nccl"]
              resources:
                limits:
                  nvidia.com/gpu: "1"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: kubeflow-pytorch-dist-mnist-test
              args: ["--backend", "nccl"]
              resources:
                limits:
                  nvidia.com/gpu: "1"
```
**What you expected to happen**:
Please help to solve the problem. I want submit the job with volcano gang scheduling successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):1.21
