### ISSUE TITLE
Issue in `LessEqual` affecting enqueueability decision of `proportion` plugin (in v1.4.0), requesting hotfix to v1.4.0

### ISSUE THREAD

**Issue by kye308** [volcano-sh/volcano#2014]
**What happened**:

When there are no jobs running in a queue, and the queue capability specifies a ScalarResource (i.e. gpu) attribute other than cpu/memory, the proportion plugin will always chose to reject enqueueing new jobs.

Problematic comparison code in `proportion` plugin: https://github.com/volcano-sh/volcano/blob/8423cb55aa539065c39733001c366194965ef0d3/pkg/scheduler/plugins/proportion/proportion.go#L295

Bug (?) in `LessEqual`: https://github.com/volcano-sh/volcano/blob/8423cb55aa539065c39733001c366194965ef0d3/pkg/scheduler/api/resource_info.go#L349

**What you expected to happen**:

For a queue with no jobs, the allocated and inqueue values were both 0 CPU, 0 Gi Mem.

Our queue specifies a capability of the form 
```
    cpu: X
    ephemeral-storage: Y Gi
    memory: Z Gi
    nvidia.com/gpu: N
```
nvidia.com/gpu is identified as a `ScalarResource` and appears to trigger the if condition here: https://github.com/volcano-sh/volcano/blob/8423cb55aa539065c39733001c366194965ef0d3/pkg/scheduler/api/resource_info.go#L349

Thus any submitted jobs will be stuck in `Pending` state.

**How to reproduce it (as minimally and precisely as possible)**:

Try to schedule any job with the scheduler config below and a queue configured as specified above on a cluster with no running jobs.

**Anything else we need to know?**:

scheduler config
```
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: proportion
  - name: predicates
    arguments:
      predicate.GPUSharingEnable: false
      predicate.CacheEnable: false
      predicate.ProportionalEnable: false
```

**Environment**:
- Volcano Version: v1.4.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
