### ISSUE TITLE
Faild to use ssh plugin in windows node

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#2066]
**What happened**:

When I create a Job with ssh plugin.I want to run this job in windows node. But it is failed.

**What you expected to happen**:

Use the ssh plugin on jobs scheduled to the windows node

**How to reproduce it (as minimally and precisely as possible)**:

1. create a job

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job-ssh
spec:
  schedulerName: volcano
  plugins:
    ssh: []
  queue: default
  tasks:
    - replicas: 1
      name: winserver-volcano
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: beyond.io:5000/winserver:1.1
              name: winserver-volcano
```

2. describe the pod created by this job

```yaml
[root@boc2 ~]# kubectl describe po test-job-ssh-winserver-volcano-0 
Name:           test-job-ssh-winserver-volcano-0
Namespace:      default
Priority:       0
Node:           win-2/10.40.20.68
Start Time:     Thu, 10 Mar 2022 16:14:09 +0800
Labels:         volcano.sh/job-name=test-job-ssh
                volcano.sh/job-namespace=default
                volcano.sh/queue-name=default
                volcano.sh/task-spec=winserver-volcano
Annotations:    kubernetes.customized/fabric-gateway: 
                kubernetes.customized/fabric-ip: 10.246.10.255
                kubernetes.customized/fabric-mac: 80:d9:38:3b:18:d6
                kubernetes.customized/fabric-mask: 16
                kubernetes.customized/fabric-network: network-example2
                kubernetes.customized/fabric-subcidr: network-example2-win-2-3514d6c9-e32f-4732-a45a-42e211be4190
                kubernetes.customized/fabric-vlan-id: 
                scheduling.k8s.io/group-name: test-job-ssh
                volcano.sh/job-name: test-job-ssh
                volcano.sh/job-version: 0
                volcano.sh/queue-name: default
                volcano.sh/task-spec: winserver-volcano
                volcano.sh/template-uid: test-job-ssh-winserver-volcano
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/test-job-ssh
Containers:
  winserver-volcano:
    Container ID:   
    Image:          beyond.io:5000/winserver:1.1
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /root/.ssh from test-job-ssh-ssh (rw,path=".ssh")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wszm2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  test-job-ssh-ssh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  test-job-ssh-ssh
    Optional:    false
  kube-api-access-wszm2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age   From     Message
  ----     ------          ----  ----     -------
  Normal   Scheduled       16s   volcano  Successfully assigned default/test-job-ssh-winserver-volcano-0 to win-2
  Normal   Pulled          7s    kubelet  Container image "beyond.io:5000/winserver:1.1" already present on machine
  Warning  Failed          3s    kubelet  Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\2822212d-4f2a-4098-b103-bcdb805787a5\volumes\kubernetes.io~secret\test-job-ssh-ssh\.ssh:c:/root/.ssh:ro': invalid mount config for type "bind": CreateFile c:\var\lib\kubelet\pods\2822212d-4f2a-4098-b103-bcdb805787a5\volumes\kubernetes.io~secret\test-job-ssh-ssh\.ssh: Access is denied.
  Normal   SandboxChanged  3s    kubelet  Pod sandbox changed, it will be killed and re-created.

```

**Anything else we need to know?**:

My guess is that when the ssh key is mounted, the path it is mounted on is not adapted to windows, resulting in an error

**Environment**:
- Volcano Version: 1.5.0
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
