### ISSUE TITLE
Could I preserve job information for few hours?

### ISSUE THREAD

**Issue by hermitgreen** [volcano-sh/volcano#2270]
#### What would you like to be added:

Preserve job in status 'Completed' for few hours.

#### Why

Noticed that job info would be deleted immediately when job complete, so does logs. 

to see what happened in pod, we need `kubectl logs -f`, but if a job need run one day, kubectl connection will broken.

If we can preserve pod log for few hours, we can just print debug information to console and do not need hold on `kubectl logs -f` util job finished

**Comment by Thor-wl** [comment]
So what you need is the logs, right? I think you can output the log to a file or some other kind of persistent storage by mounting a volume to containers.

**Comment by hwdef** [comment]
Did you set any special policy, I created a vcjob and it doesn't seem to be deleted

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pi-job
spec:
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 3
      name: "pi"
      template:
        metadata:
          name: pi
        spec:
          restartPolicy: Never
          containers:
            - image: perl
              name: pi
              command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(800)"]
```

![图片](https://user-images.githubusercontent.com/13084946/171592696-3ef1dd86-d6ba-4e9e-a3bb-58a17e9c5391.png)
