### ISSUE TITLE
Pod starts running when Queue state is closed

### ISSUE THREAD

**Issue by Sharathmk99** [volcano-sh/volcano#2276]
**What happened**:
When I close the queue using `vcctl` cli and submit the `pod`, it starts running.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Closed `default` queue
`vcctl queue operate -a close -n default`

Submited below pod,
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    scheduling.volcano.sh/queue-name: default
spec:
  schedulerName: volcano
  restartPolicy: Never
  containers:
  - name: bash
    image: python:3.7
    imagePullPolicy: IfNotPresent
    command: ["bash", "-c", "echo 'sleep...'; sleep 600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "1000m"
```

**Anything else we need to know?**:
Currently `job` validation webhook blocks the job with queue state is closed. But `pod` validation doesn't block the same.

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
