### ISSUE TITLE
Jobs are in pending state when cluster has available resource

### ISSUE THREAD

**Issue by Sharathmk99** [volcano-sh/volcano#2304]
**What happened**:
Resource is available in the cluster, but jobs are not getting scheduled.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Below are available queues,

```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test1
spec:
  reclaimable: false
  weight: 50

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test2
spec:
  reclaimable: false
  weight: 50

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test3
spec:
  reclaimable: false
  weight: 200

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test4
spec:
  reclaimable: false
  weight: 150

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  guarantee: {}
  reclaimable: true
  weight: 1

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test5
spec:
  reclaimable: false
  weight: 150

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test6
spec:
  reclaimable: false
  weight: 240

---

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test7
spec:
  reclaimable: false
  weight: 160
```
**Cluster has 8 GPU, But running job consumes only 7 GPU. GPU will be dominating resource**

Below Job status

![Screenshot 2022-06-17 132919](https://user-images.githubusercontent.com/3970340/174298773-bc7fa8fd-62ff-4577-a09d-6321e9ce46bb.png)

Scheduler config:

```
actions: "enqueue, allocate, backfill, reclaim, preempt"
tiers:
- plugins:
  - name: priority
  - name: proportion
  - name: conformance
- plugins:
  - name: overcommit
  - name: drf
  - name: predicates
  - name: nodeorder
  - name: binpack
 ```

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
