### ISSUE TITLE
VCJob singular and plural nouns should be updated to avoid conflict with the nouns of `batch.v1/job`

### ISSUE THREAD

**Issue by jsolbrig** [volcano-sh/volcano#2305]
#### What would you like to be added:

I would like to see the VCJob CRD use a different naming structure to avoid conflict with `batch.v1/job`. At minimum, the singular and plural nouns should be updated to be "vcjob" and "vcjobs". It would be nice to also update the `kind` to be `VCJob` and the `listKind` to be `VCJobList` but that may be more difficult than it is worth.

#### Why is this needed:

Currently, using kubectl to get info on VCJob resources is cumbersome because the "singular" noun "job" and the "plural" noun "jobs" conflict with the nouns used by `batch.v1/job`. So, none of these work as expected with respect to VCJobs.

```bash
> kubectl get job  # returns batch.v1/job resources
> kubectl get jobs  # returns batch.v1/job resources
> kubectl get vcjobs  # raises an error
```

#### Proposed changes

Changes would need to be made to the VCJob CRD. The current naming structure looks like this:

```yaml
spec:
  names:
    kind: Job
    listKind: JobList
    plural: jobs  # This conflicts with batch.v1/job
    shortNames:
    - vcjob
    - vj
    singular: job  # This conflicts with batch.v1/job
```

Something like this would be nice and might not impact anything else:

```yaml
spec:
  names:
    kind: Job
    listKind: JobList
    plural: vcjobs
    shortNames:
    - vj
    singular: vcjob
```

This would be more ideal but probably much more difficult:

```yaml
spec:
  names:
    kind: VCJob
    listKind: VCJobList
    plural: vcjobs
    shortNames:
    - vj
    singular: vcjob
```
