### ISSUE TITLE
the Pending state of volcano job maybe ambiguous

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#2310]
#### What would you like to be added:

extend Pending state to more detail states

```
  state:
    lastTransitionTime: "2022-06-25T07:23:19Z"
    phase: Pending
    secondaryStatus: InitContainerRunning
```

#### Why is this needed:

watch the volcano job yaml, we can observe the status changes as following sequences

```
# the status field in the fist volcano job yaml is empty

# 2nd
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 1
  state:
    lastTransitionTime: "2022-06-25T07:23:19Z"
    phase: Pending

# 3rd
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 1
  pending: 1
  state:
    lastTransitionTime: "2022-06-25T07:23:19Z"
    phase: Pending
  taskStatusCount:
    worker:
      phase:
        Unknown: 1

# 4
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 1
  pending: 1
  state:
    lastTransitionTime: "2022-06-25T07:23:19Z"
    phase: Pending
  taskStatusCount:
    worker:
      phase:
        Pending: 1

# 5
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  - lastTransitionTime: "2022-06-25T07:23:34Z"
    status: Running
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 1
  running: 1
  state:
    lastTransitionTime: "2022-06-25T07:23:34Z"
    phase: Running
  taskStatusCount:
    worker:
      phase:
        Running: 1

# 6
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  - lastTransitionTime: "2022-06-25T07:23:34Z"
    status: Running
  - lastTransitionTime: "2022-06-25T07:23:45Z"
    status: Completing
  minAvailable: 1
  runningDuration: 26.3158438s
  state:
    lastTransitionTime: "2022-06-25T07:23:45Z"
    phase: Completing
  succeeded: 1
  taskStatusCount:
    worker:
      phase:
        Succeeded: 1
  version: 1

# 7
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  - lastTransitionTime: "2022-06-25T07:23:34Z"
    status: Running
  - lastTransitionTime: "2022-06-25T07:23:45Z"
    status: Completing
  - lastTransitionTime: "2022-06-25T07:23:45Z"
    status: Completed
  minAvailable: 1
  runningDuration: 26.43882994s
  state:
    lastTransitionTime: "2022-06-25T07:23:45Z"
    phase: Completed
  succeeded: 1
  taskStatusCount:
    worker:
      phase:
        Succeeded: 1
  version: 2

# 8
status:
  conditions:
  - lastTransitionTime: "2022-06-25T07:23:19Z"
    status: Pending
  - lastTransitionTime: "2022-06-25T07:23:34Z"
    status: Running
  - lastTransitionTime: "2022-06-25T07:23:45Z"
    status: Completing
  - lastTransitionTime: "2022-06-25T07:23:45Z"
    status: Completed
  minAvailable: 1
  runningDuration: 26.474628979s
  state:
    lastTransitionTime: "2022-06-25T07:23:45Z"
    phase: Completed
  succeeded: 1
  taskStatusCount:
    worker:
      phase:
        Succeeded: 1
  version: 3
```

but actually, when the pod has a **init container** and a training container, such as

```
  initContainers:
  - command: /usr/bin/precheck
    image: system
    name: tool-container
  containers:
  - command: python train.py
    image: pytorch
    name: training-container
```

the pod is still in the pending state when the init container is running, that leads to the pending state of volcano job, i'd like to know the job is in the init state rather than a overall pending state

ref: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_SecondaryStatusTransition.html

> InProgress
> 1. Starting - Starting the training job.
> 2. Downloading - An optional stage for algorithms that support File training input mode. It indicates that data is being downloaded to the ML storage volumes.
> 3. Training - Training is in progress.
> 4. Uploading - Training is complete and the model artifacts are being uploaded to the S3 location.
