### ISSUE TITLE
How to have a default job that is always running when there are resources available? 

### ISSUE THREAD

**Issue by pietermarsman** [volcano-sh/volcano#2315]
Hi! :wave: 

I love volcano so far. It is really neat in managing batch jobs. 

One thing I cannot figure out though. I want to have a default job that is always running if there are resources available.

Some context. I use volcano to schedule machine-learning workflows on a kubernetes cluster. On some days I want to schedule a  specific training for research purposes, that maybe uses another image, different settings, or different hardware, or smth else. On most days I just want to run the default training that does hyper parameter optimization. The specific trainings should have a higher priority, the default training has the lower priority. 

What I want:
- The default job.
    * A pod runs for a couple of hours.
    * Should restart when finished. 
    * Not to be evicted/cancelled when running a pod.
- The specific job
    * Can run for a long time. E.g. days. 
    * Only runs one pod to completion. Then it is finished. 
    * Should wait until there is room. Should not evict other pods. 

My current configuration does not do this. I think it waits with scheduling the specific jobs until the default job is completed. I want it to run the specific jobs pods in between the default job pods. 

Currently my default job looks like this (simplified of course):

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: default-job
spec:
  schedulerName: volcano
  queue: default
  priorityClassName: low-priority

  minAvailable: 1
  minSuccess: 1000
  maxRetry: 1000

  tasks:
    - name: training
      replicas: 2

      template:
        metadata:
          labels:
            app: training

        spec:
          priorityClassName: low-priority

          containers:
            - name: train
              image: "mydocker/mydocker"
              imagePullPolicy: Always
              resources:
                limits:
                  nvidia.com/gpu: "1"
```

The specific research jobs look like this:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: research-job
spec:
  schedulerName: volcano
  queue: default
  priorityClassName: normal-priority

  tasks:
    - name: training
      replicas: 1

      template:
        metadata:
          labels:
            app: training

        spec:
          containers:
            - name: train
              image: "mydocker/otherdocker"
              imagePullPolicy: Always
              resources:
                limits:
                  nvidia.com/gpu: "1"
```

The priorities I have:

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal-priority
value: 1000
globalDefault: true
description: "Default priority class for all pods"
preemptionPolicy: PreemptLowerPriority
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 500
description: "Low priority class"
preemptionPolicy: PreemptLowerPriority
```

The scheduler config I have:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue, preempt, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
