### ISSUE TITLE
Deploying 1.6 on GKE: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]

### ISSUE THREAD

**Issue by JarnoRFB** [volcano-sh/volcano#2379]
**What happened**:
I tried to install volcano 1.6 on a GKE cluster where 1.5 was running before. After the upgrade I found that `volcano-admission`, `volcano-controllers` and `volcano-scheduler` all showed the message `insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]` and the deployment therefore did not succeed. 

**What you expected to happen**:
I expected volcano to get installed.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/release-1.6/installer/volcano-development.yaml`

**Anything else we need to know?**:
The only comparable issues I found where https://github.com/cilium/cilium/issues/13852 and https://github.com/open-policy-agent/gatekeeper/issues/1120. I supect the error is due to the introduction of the new priority classes in the 1.6 deployment. Trying to install volcano into the kube-system namespace did not succeed as well, but sounds like an undesired solution anyway.

**Environment**:
- Volcano Version: 1.6
- Kubernetes version (use `kubectl version`): v1.22.8-gke.202
- Cloud provider or hardware configuration: GKE

**Comment by Thor-wl** [comment]
@JarnoRFB Hey, I guess you put the volcano components with the priorityclass `system-node-critical system-cluster-critical`, which is reserved for system. Please try to set the pods with a custom priority and install again.

**Comment by JarnoRFB** [comment]
Yes that's true, but as far as I can see, these priority classes are set in the volcano manifests itself, e.g. https://github.com/volcano-sh/volcano/blob/master/installer/volcano-development.yaml#L134 . Are users supposed to overwrite these values?

**Comment by Thor-wl** [comment]
> Yes that's true, but as far as I can see, these priority classes are set in the volcano manifests itself, e.g. https://github.com/volcano-sh/volcano/blob/master/installer/volcano-development.yaml#L134 . Are users supposed to overwrite these values?

In general, it is not supposed to modify the priority for volcano components, which may introduce unexpected behavior. But if you are familar with the environment, providing a relatively high priority is also acceptable.

**Comment by JarnoRFB** [comment]
Would a possible solution be to make the priority class configurable in the helm chart? I am somewhat reluctant to modify the sources directly, as that would make future updates harder. I could also submit a PR for this if it is desired.

**Comment by Thor-wl** [comment]
> Would a possible solution be to make the priority class configurable in the helm chart? I am somewhat reluctant to modify the sources directly, as that would make future updates harder. I could also submit a PR for this if it is desired.

I'm OK about that.

**Comment by yiqin** [comment]
I get the same error. How to resolve it?

**Comment by wangyang0616** [comment]
Retain the current issue.
/remove-lifecycle stale

**Comment by BloodyPan** [comment]
my solution:

1. get volcano-development.yaml
\>\> wget https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

2. create a ResourceQuota after namespace created
\>\> vi volcano-development.yaml
\>\> paste the ResourceQuota show below

```
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: volcano-critical-pods
  namespace: volcano-system
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
```

then your volcano-development.yaml will be look like this:
```
apiVersion: v1
kind: Namespace
metadata:
  name: volcano-system
  labels:
    kubernetes.io/metadata.name: volcano-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: volcano-monitoring
  labels:
    kubernetes.io/metadata.name: volcano-monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: volcano-critical-pods
  namespace: volcano-system
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
---
# Source: volcano/templates/admission.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volcano-admission
  namespace: volcano-system
---
......
```

finally deploy this changes: 
```kubectl apply -f volcano-development.yaml```
