### ISSUE TITLE
Part of pods are still scheduled even if minAvailable did not reached

### ISSUE THREAD

**Issue by joeyjy** [volcano-sh/volcano#2462]
**What happened**:
Part of pods are still scheduled even if minAvailable did not reached
```
  conditions:
  - lastTransitionTime: "2022-08-25T09:28:19Z"
    message: '12/8 tasks in gang unschedulable: pod group is not ready, 20 minAvailable,
      8 Running'
    reason: NotEnoughResources
    status: "True"
    transitionID: 154b09d2-11ba-4c3c-b3d1-76e97ff8c2aa
    type: Unschedulable
  phase: Unknown
  running: 8
```
**What you expected to happen**:
The whold task shouldn't have been started
**How to reproduce it (as minimally and precisely as possible)**:
my yaml of a vj
```
...
spec:
  maxRetry: 3
  minAvailable: 20
  plugins:
    env: []
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodEvicted
  priorityClassName: high-priority
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 20
    name: trainning
    policies:
    - action: CompleteJob
      event: TaskCompleted
    replicas: 20
    template:
      metadata:
        annotations:
          kubernetes.io/egress-bandwidth: 800M
          kubernetes.io/ingress-bandwidth: 800M
        labels:
          app: b06a5ce9eb5994fb3abd0bf9963d06a97
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.mydomain.com/cni
                  operator: In
                  values:
                  - cilium
                - key: cloud.mydomain.com/role
                  operator: In
                  values:
                  - my-training
        containers:
...
```

**Anything else we need to know?**:
scheduler args like:
```
      containers:
      - args:
        - --logtostderr
        - --node-selector=cloud.mydomain.com/role:my-training
        - --scheduler-conf=/volcano.scheduler/volcano-scheduler.conf
        - --enable-healthz=true
        - --enable-metrics=true
        - -v=4
        - 2>&1
```
**Environment**:
- Volcano Version: v1.5.1
- Kubernetes version (use `kubectl version`): v1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7.6
- Kernel (e.g. `uname -a`): 5.10.56
- Install tools:
- Others:
