### ISSUE TITLE
What is the difference between this volcano project and volcano plugin in huawei cloud CCE product?

### ISSUE THREAD

**Issue by cauwulixuan** [volcano-sh/volcano#2494]
What is the difference between this volcano project and volcano plugin in huawei cloud CCE product?

In huawei cloud CCE product, after installing volcano plugin, several plugin configs were found in `volcano-scheduler-configmap`, like:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
    - plugins:
      - cce-gpu-topology-predicate
      - cce-gpu-topology-priority
      - cce-gpu
kind: ConfigMap
```

What confused me was the plugins (`cce-gpu-topology-predicate`, `cce-gpu-topology-priority`, `cce-gpu`) that were not in the `volcano` project. So how do these plugins with prefix `cce-` work?
