### ISSUE TITLE
imagelocality.weight can not take affect when using nodeorder plugin

### ISSUE THREAD

**Issue by zhifanggao** [volcano-sh/volcano#2496]
**What happened**:
imagelocality.weight can not take affect when using nodeorder plugin
**What you expected to happen**:
imagelocality.weight  works when using nodeorder plugin
**How to reproduce it (as minimally and precisely as possible)**:
1. there are 3  worker nodes in my environment
```
[root@host-10-19-37-28 volcano]# kubectl get node
NAME               STATUS   ROLES                  AGE    VERSION
host-10-19-37-27   Ready    <none>                 142d   v1.22.2
host-10-19-37-28   Ready    control-plane,master   147d   v1.22.2
host-10-19-37-29   Ready    <none>                 147d   v1.22.2
host-10-19-37-34   Ready    <none>                 145d   v1.22.2
```
2. job
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vc-gzfjob1
  namespace: test
spec:
  # minAvailable: 0
  schedulerName: volcano
  queue: test
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 3
      name: gzfjob1
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          priorityClassName: high-priority
          containers:
            - command:
              - sleep
              - 10m
              image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 200m
                limits:
                  cpu: 200m
          restartPolicy: OnFailure
```
3. only  host-10-19-37-34  already has `nginx:latest ` image 
4. scheduler config:
```
      - name: nodeorder
        arguments:
          nodeaffinity.weight: 0
          podaffinity.weight: 0
          leastrequested.weight: 0
          balancedresource.weight: 0
          mostrequested.weight: 0
          tainttoleration.weight: 0
          imagelocality.weight: 100
```
5. deploy the job 
```
[root@host-10-19-37-28 volcano]# kubectl create -f ./queuejob.yaml
job.batch.volcano.sh/vc-gzfjob1 created
[root@host-10-19-37-28 volcano]# kubectl -n test get po
NAME                   READY   STATUS              RESTARTS   AGE
vc-gzfjob1-gzfjob1-0   0/1     ContainerCreating   0          8s
vc-gzfjob1-gzfjob1-1   0/1     ContainerCreating   0          8s
vc-gzfjob1-gzfjob1-2   0/1     ContainerCreating   0          8s
[root@host-10-19-37-28 volcano]# kubectl -n test get po -o wide
NAME                   READY   STATUS              RESTARTS   AGE   IP       NODE               NOMINATED NODE   READINESS GATES
vc-gzfjob1-gzfjob1-0   0/1     ContainerCreating   0          12s   <none>   host-10-19-37-27   <none>           <none>
vc-gzfjob1-gzfjob1-1   0/1     ContainerCreating   0          12s   <none>   host-10-19-37-27   <none>           <none>
vc-gzfjob1-gzfjob1-2   0/1     ContainerCreating   0          12s   <none>   host-10-19-37-27   <none>           <none>
```
It choose node host-10-19-37-27  instead.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:1.16
- Kubernetes version (use `kubectl version`):1.22
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 7.5
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools: kubeadmin
- Others:
