### ISSUE TITLE
Using proportional in namespaced scope.

### ISSUE THREAD

**Issue by cauwulixuan** [volcano-sh/volcano#2498]
#### Why is this needed:
for now, proportional in predicate plugin was a cluster-scope functionality with setup like:
```
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: predicates
    arguments:
      predicate.ProportionalEnable: true
      predicate.resources: nvidia.com/gpu
      predicate.resources.nvidia.com/gpu.cpu: 8
      predicate.resources.nvidia.com/gpu.memory: 8
```

Now we have a scenario: we have several namespaces in our k8s cluster, and for now, we set `ResourceQuota` in each namespace for resource isolation, so what can we do if we want to set different proportion in different namespace? And if we don't set any proportion, we can use the cluster-scope settings above.

For instance, in namespace ns1, I want to set gpu:cpu:memory=1:4:4; and in ns2, gpu:cpu:memory=1:8:8. If there any chance for us to  set up plugin like:
```
tiers:
- plugins:
  - name: predicates
    arguments:
      predicate.ProportionalEnable: true
      predicate.resources.ns1: nvidia.com/gpu
      predicate.resources.ns1.nvidia.com/gpu.cpu: 4
      predicate.resources.ns1.nvidia.com/gpu.memory: 4
      predicate.resources.ns2: nvidia.com/gpu
      predicate.resources.ns2.nvidia.com/gpu.cpu: 8
      predicate.resources.ns2.nvidia.com/gpu.memory: 8
```

Is there any suggestions on these scenario? Thanks a lot.
