### ISSUE TITLE
Volcano scheduler executing jobs sequentially

### ISSUE THREAD

**Issue by garimachhabra20** [volcano-sh/volcano#2534]
**What happened**: Volcano scheduler executing jobs sequentially

**What you expected to happen**: Expectation was that volcano scheduler would schedule pods of jobs for which resources are available and not wait for jobs (created earlier and are waiting for resources to become available) to complete.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use training-operator in cluster and enable gang scheduling
2. Create a resource quota of 400Mi memory
```
NAME          AGE   REQUEST           LIMIT
memoryquota   23d   memory: 0/400Mi 
```
3. Create pytorch jobs using manifest below.
```
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple2
  namespace: resource-quota
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 240s']
              resources:
                limits:
                  memory: 100Mi
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 120s']
              resources:
                limits:
                  memory: 100Mi
---

apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple3
  namespace: resource-quota
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 120s']
              resources:
                limits:
                  memory: 100Mi
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 120s']
              resources:
                limits:
                  memory: 100Mi

---

apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple4
  namespace: resource-quota
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 120s']
              resources:
                limits:
                  memory: 100Mi
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: busybox
              imagePullPolicy: Always
              command: ['sh', '-c', 'sleep 120s']
              resources:
                limits:
                  memory: 100Mi
```
4. Check pods that are created. In the above example - 
```
NAME                       READY   STATUS    RESTARTS   AGE
pytorch-simple2-master-0   1/1     Running   0          15s
pytorch-simple2-worker-0   1/1     Running   0          14s
pytorch-simple3-worker-0   0/1     Pending   0          13s
pytorch-simple3-worker-1   0/1     Pending   0          13s
```
Expectation is - pytorch-simple4-worker-0 and pytorch-simple4-master-0 must be created because the resource is available to run simple4 job and not simple3 job. 
And the sequence in which job pods run are -
```
pytorch-simple2-master-0   0/1     Completed   0          24m
pytorch-simple2-worker-0   0/1     Completed   0          24m
pytorch-simple3-master-0   0/1     Completed   0          22m
pytorch-simple3-worker-0   0/1     Completed   0          24m
pytorch-simple3-worker-1   0/1     Completed   0          24m
pytorch-simple4-master-0   0/1     Completed   0          19m
pytorch-simple4-worker-0   0/1     Completed   0          19m
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: Latest (https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/values.yaml)
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
