### ISSUE TITLE
GPU Resource Are Not Taken into Account in Enqueue Action

### ISSUE THREAD

**Issue by yuyue9284** [volcano-sh/volcano#2564]
**What happened**:
Job with insufficient GPU resource get enqueued and pods get created.

**What you expected to happen**:
The job should be rejected in the enqueue action.

**How to reproduce it (as minimally and precisely as possible)**:

Create job with this spec:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test
spec:
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 2
      name: "pod"
      template:
        spec:
          containers:
            - command: ["sleep", "infinity"]
              image: ubuntu
              name: gpu
              resources:
                limits:
                  cpu: "1"
                  nvidia.com/gpu: "100"
                requests:
                  cpu: "1"
                  nvidia.com/gpu: "100"
          restartPolicy: OnFailure
```

**Anything else we need to know?**:
The extended resource original format are not keeped and only `requests.nvidia.com/gpu` are populated.
https://github.com/volcano-sh/volcano/blob/076f4393231c331f4dba1b2dec6bb587cd787f86/pkg/controllers/job/job_controller_actions.go#L786
https://github.com/volcano-sh/volcano/blob/076f4393231c331f4dba1b2dec6bb587cd787f86/vendor/k8s.io/kubernetes/pkg/quota/v1/evaluator/core/pods.go#L264-L275

When calculating the inqueue resource, the gpu resource with `requests` will not be considered as scalar resource and got skipped.
https://github.com/volcano-sh/volcano/blob/630e6e509f6642f4b5cb0d3dd4fc70eee9214da7/pkg/scheduler/api/resource_info.go#L86-L88

The min resource in the pod group:
```
  spec:
    minMember: 2
    minResources:
      count/pods: "2"
      cpu: "2"
      limits.cpu: "2"
      pods: "2"
      requests.cpu: "2"
      requests.nvidia.com/gpu: "200"
    minTaskMember:
      pod: 2
    queue: default
```

**Environment**:
- Volcano Version: 1.6
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Two nodes with one gpu on each node.
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
