### ISSUE TITLE
Priority preempt: high priority job could not evict pods with lowest priorityclass directly.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#2622]
**What happened**:

When I tried preempt action，I set 3 priorityclass: high, mid, and low. Then I found that high-priority job could not preempt low-priority job directly, but preempt mid-priority job at first, and after mid-priority job was evicted and turned pending, it would preempt low-priority job instead. 

It was probably caused by: https://github.com/volcano-sh/volcano/blob/3cebc5b50f5b4afd9159875ba60167bfd398c39a/pkg/scheduler/actions/preempt/preempt.go#L245-L247
Here all victims were push in a `priorityqueue` which sorted by `taskOrderFn`, whereas `priority` plugin registered `taskOrderFn` to make sure that low-priority task would always at front of high-priority task. But by default, task priority would not be set as the same with job priority:https://github.com/volcano-sh/volcano/blob/3cebc5b50f5b4afd9159875ba60167bfd398c39a/pkg/scheduler/api/job_info.go#L156-L196

So if we do not compare job priority, the task priority would be same, and victim priorityQueue would not take effect.

**What you expected to happen**:
High priority job preempt job with lowest priority directly.

**How to reproduce it (as minimally and precisely as possible)**:
1. create 3 priorityclass, like:
```shell
NAME                      VALUE        GLOBAL-DEFAULT   AGE
high                      1000         false            48d
low                       10           false            5h1m
mid                       100          false            5h1m
```
2. create low-priority job, like:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-low
spec:
  schedulerName: volcano
  minAvailable: 4
  queue: default
  priorityClassName: low
  tasks:
    - replicas: 2
      name: "task0"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
    - replicas: 2
      name: "task1"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
```
4 pod of low-priority job would be running.

3. create mid-priority job, like:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-mid
spec:
  schedulerName: volcano
  minAvailable: 2
  queue: default
  priorityClassName: mid
  tasks:
    - replicas: 1
      name: "task0"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
    - replicas: 1
      name: "task1"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
```
Then mid-priority job would preempt low-priority job, evicted 2 pod:

```shell
NAME              READY   STATUS        RESTARTS   AGE
job-low-task0-0   1/1     Running       0          15s
job-low-task0-1   1/1     Terminating   0          15s
job-low-task1-0   1/1     Running       0          15s
job-low-task1-1   1/1     Terminating   0          15s
job-mid-task0-0   0/1     Pending       0          3s
job-mid-task1-0   0/1     Pending       0          3s
```
4. create high-priority job, the yaml was the same with mid-priority job except `priorityClassName: high`.

Then high-priority job would preempt mid-priority job first:

```shell
NAME               READY   STATUS        RESTARTS   AGE
job-high-task0-0   0/1     Pending       0          2s
job-high-task1-0   0/1     Pending       0          2s
job-low-task0-0    1/1     Running       0          2m41s
job-low-task0-1    0/1     Pending       0          107s
job-low-task1-0    1/1     Running       0          2m41s
job-low-task1-1    0/1     Pending       0          107s
job-mid-task0-0    1/1     Terminating   0          2m29s
job-mid-task1-0    1/1     Terminating   0          2m29s
```

Then mid-priority job would preempt low-priority job:

```shell
NAME               READY   STATUS              RESTARTS   AGE
job-high-task0-0   0/1     ContainerCreating   0          36s
job-high-task1-0   0/1     ContainerCreating   0          36s
job-low-task0-0    1/1     Terminating         0          3m15s
job-low-task0-1    0/1     Pending             0          2m21s
job-low-task1-0    1/1     Terminating         0          3m15s
job-low-task1-1    0/1     Pending             0          2m21s
job-mid-task0-0    0/1     Pending             0          1s
job-mid-task1-0    0/1     Pending             0          1s
```

Logs also show the preempt timeline:

```shell
I1226 08:23:47.208994       1 preempt.go:261] Try to preempt Task <default/job-low-task1-1> for Task <default/job-mid-task0-0>
I1226 08:23:47.209413       1 preempt.go:261] Try to preempt Task <default/job-low-task0-1> for Task <default/job-mid-task1-0>
I1226 08:26:14.116276       1 preempt.go:261] Try to preempt Task <default/job-mid-task0-0> for Task <default/job-high-task0-0>
I1226 08:26:14.116847       1 preempt.go:261] Try to preempt Task <default/job-mid-task1-0> for Task <default/job-high-task1-0>
I1226 08:26:48.513051       1 preempt.go:261] Try to preempt Task <default/job-low-task1-0> for Task <default/job-mid-task0-0>
I1226 08:26:48.513420       1 preempt.go:261] Try to preempt Task <default/job-low-task0-0> for Task <default/job-mid-task1-0>
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
