### ISSUE TITLE
Preempt do not follow minAvailable.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#2627]
**What happened**:

When I tried preempt action with priority plugin. I set `minAvailable: 1` in high-priority job which has 4 tasks, and supposed that Volcano would evict only 1 task of low-priority job. But the result was that all 4 tasks from high-priority job started and evicted 4 low-priority tasks as below:

```shell
NAME               READY   STATUS        RESTARTS   AGE
job-high-task0-0   0/1     Pending       0          3s
job-high-task0-1   0/1     Pending       0          3s
job-high-task1-0   0/1     Pending       0          3s
job-high-task1-1   0/1     Pending       0          3s
job-low-task0-0    1/1     Terminating   0          13m
job-low-task0-1    1/1     Terminating   0          13m
job-low-task1-0    1/1     Terminating   0          13m
job-low-task1-1    1/1     Terminating   0          14m
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

`volcano-scheduler-configmap` was set as below:

```yaml
    actions: "enqueue, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enableJobStarving: false
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: nodeorder
      - name: binpack
```

1. Set priorityclass:

```shell
NAME                      VALUE        GLOBAL-DEFAULT   AGE
high                      1000         false            49d
low                       10           false            31h
```

2. Apply low-priority job with 4 task and fullfilled the cluster:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-low
spec:
  schedulerName: volcano
  minAvailable: 4
  queue: default
  priorityClassName: low
  tasks:
    - replicas: 2
      name: "task0"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
    - replicas: 2
      name: "task1"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
```

3. Apply high-priority job with 4 task but `minAvailable: 1`:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-high
spec:
  schedulerName: volcano
  minAvailable: 1
  queue: default
  priorityClassName: high
  tasks:
    - replicas: 2
      name: "task0"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
    - replicas: 2
      name: "task1"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 99999"]
              imagePullPolicy: IfNotPresent
              name: task
              resources:
                limits:
                  cpu: 3750m
                requests:
                  cpu: 3750m
          restartPolicy: OnFailure
```

4. Wait for preempt.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
