### ISSUE TITLE
For services other than job, such as deployment and pod, high priority cannot preempt low priority resources

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#2629]
**What happened**:
Deployment tasks are deployed through the Volcano scheduler, and high-priority jobs cannot preempt resources from low-priority jobs.

Three priority classes are set in the cluster, namely high, mid, and low. 
```
[root@ecs-4b42-0002 volcano]# kubectl get priorityclass
NAME                      VALUE        GLOBAL-DEFAULT   AGE
high-priority             100          false            102m
low-priority              10           false            102m
mid-priority              50           false            102m
```

First, a deployment `deploy-low` with a priority class of low is created, and the replicas  is 4, which occupies the idle resources of the cluster.
Then create a deployment `deploy-high` with a priorityClass of high and a replica number of 4.

- The result of kube-scheduler is that `deploy-high` preempts the resources of `deploy-low`, and all 4 copies of `deploy-high` are running
  ```
  NAME                          READY   STATUS    RESTARTS   AGE
  deploy-high-d66c9db75-6sjnt   1/1     Running   0          51s
  deploy-high-d66c9db75-92bkp   1/1     Running   0          51s
  deploy-high-d66c9db75-nnvhq   1/1     Running   0          51s
  deploy-high-d66c9db75-pjwnz   1/1     Running   0          51s
  deploy-low-b46c7466c-knz7j    0/1     Pending   0          51s
  deploy-low-b46c7466c-lb6n6    0/1     Pending   0          51s
  deploy-low-b46c7466c-vvz9m    0/1     Pending   0          51s
  deploy-low-b46c7466c-z4kkf    0/1     Pending   0          51s
  ```

- The results of the volcano scheduler and the kube-scheduler are inconsistent, `deploy-high` triggers the preemption action, and it is always pending
  ```
  NAME                           READY   STATUS    RESTARTS   AGE
  deploy-high-587b867944-54dtc   0/1     Pending   0          2m35s
  deploy-high-587b867944-5gs7s   0/1     Pending   0          2m35s
  deploy-high-587b867944-n6m8l   0/1     Pending   0          2m35s
  deploy-high-587b867944-xfc5z   0/1     Pending   0          2m35s
  deploy-low-67b97db94b-5g56g    1/1     Running   0          3m10s
  deploy-low-67b97db94b-6lztd    1/1     Running   0          3m10s
  deploy-low-67b97db94b-ggjrw    1/1     Running   0          3m10s
  deploy-low-67b97db94b-tddzf    1/1     Running   0          3m10s
  ```
- In volcano scheduling, the pod information of `deploy-high` is as follows
  ```
  Events:
    Type     Reason            Age                    From     Message
    ----     ------            ----                   ----     -------
    Warning  FailedScheduling  2m (x12 over 2m46s)    volcano  1/4 tasks in gang unschedulable: pod group is not ready, 1 minAvailable, 4 Pending; Pending: 4 Unschedulable
    Warning  FailedScheduling  119s (x13 over 2m47s)  volcano  all nodes are unavailable: 5 node(s) resource fit failed.
  ```

**What you expected to happen**:
The performance of the volcano is consistent with that of the kube-scheduler, and `deploy-high` can normally preempt the resources of `deploy-low`

**How to reproduce it (as minimally and precisely as possible)**:
- high_priorityclass.yaml
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100
globalDefault: false
description: "This priority class should be used for volcano job only."
```
- low_priorityclass.yaml
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 10
globalDefault: false
description: "This priority class should be used for volcano job only."
```
- high_deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-high
  labels:
    app: wy-high
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wy-high
  template:
    metadata:
      labels:
        app: wy-high
    spec:
      schedulerName: volcano
      containers:
      - name: high
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          requests:
            cpu: 3500m
          limits:
            cpu: 3500m
      priorityClassName: high-priority
```
- low_deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-low
  labels:
    app: wy-low
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wy-low
  template:
    metadata:
      labels:
        app: wy-low
    spec:
      schedulerName: volcano
      containers:
      - name: low
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          requests:
            cpu: 3500m
          limits:
            cpu: 3500m
      priorityClassName: low-priority
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): v1.25.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
