### ISSUE TITLE
how to create a service for every task pod

### ISSUE THREAD

**Issue by shuaiyy** [volcano-sh/volcano#2654]
#### What would you like to be added:

it seems vcjob use pod dns to discover each other, no service.

the task Pod labels don't  have a unique label （e.g. task_index or task_pod_name）,so i can't create a service manaully with service selector

#### Why is this needed:

i will create an ingress router for every taskPod  for provide http debugging service,  so service is need.

**Comment by wangyang0616** [comment]
@shuaiyy sorry to reply you so late.
Volcano's task supports the native semantics of k8s metadata. You can add labels to the template, which will take effect for all pods in the current task.

For example, add `mytest: dev` labels to a task in the job. The specific yaml file reference is as follows:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: priority-high
spec:
  schedulerName: volcano
  minAvailable: 2
  priorityClassName: high-priority
  tasks:
    - replicas: 12
      name: "test"
      template:
        metadata:
          labels:
            mytest: dev
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: running
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
```
