### ISSUE TITLE
The phase of evicted volcanojob is inconsistent

### ISSUE THREAD

**Issue by LivingCcj** [volcano-sh/volcano#2685]
**What happened**:
when we use the preempt action，the low priority volcanojob  will be preempted the high priority volcanojob , but the phase of  evicted volcanojob is still be Running，the phase of its' podGroup is Inqueue. 
```
name                     priority   status
cpu-resource-test-high   job-high   map[controlledResources:map[plugin-env:env plugin-svc:svc] minAvailable:5 running:5 state:map[lastTransitionTime:2023-02-16T04:06:21Z phase:Running]]
cpu-resource-test-low    job-low    map[controlledResources:map[plugin-env:env plugin-svc:svc] minAvailable:5 state:map[lastTransitionTime:2023-02-16T04:05:33Z phase:Running] unknown:5]
```
**What you expected to happen**:
when the resource changes to be Adequate, the evicted volcanojob could be rescheduled.
Or when evicting volcanojob，volcano-controller-manager could  delete the  low priority volcanojob.
**How to reproduce it (as minimally and precisely as possible)**:
we cloud add a phase type, like Preempted, for volcanojob crd. And add a configurable options for volcano-controller-manager, it let user choose to delete or reschedule the low priority volcanojob.

**Environment**:
- Volcano Version: v 1.2.0
- Kubernetes version (use `kubectl version`): 1.16.10

**Comment by william-wang** [comment]
If there is adequate resource, the evicted job should be changed from pending to running. 
@LivingCcj Would you like to provide your job yaml file?

**Comment by wangyang0616** [comment]
I reproduced the problem through master, please give me some time to fix it.

**Comment by LivingCcj** [comment]
There is some test yaml `cpu-resource-test-low.yaml` and `cpu-resource-test-high.yaml`. 
the first yaml `cpu-resource-test-low.yaml`:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: cpu-resource-test-low
  labels:
    app: "test"
    volcano.sh/preemptable: "true"
spec:
  minAvailable: 5
  schedulerName: volcano
  plugins:
    env: []
  policies:
    - action: RestartJob
      event: PodFailed
    - action: RestartJob
      event: TaskFailed
  priorityClassName: job-low
  tasks:
    - replicas: 5
      name: ps
      policies:
      - action: CompleteJob
        event: TaskCompleted
      template:
        metadata:
          annotations:
          labels:
            app: test-low
        spec:
          containers:
            - command:
              - bash
              args:
              - -c
              - exec sleep 5m
              image: xxx
              name: sidercar
              imagePullPolicy: Always
              resources:
                 requests:
                   cpu: "7"
                   memory: "14Gi"
                 limits:
                   cpu: "7"
                   memory: "14Gi"
            - command:
              - bash
              args:
              - -c
              - exec sleep 5m
              image: xxx
              name: main
              imagePullPolicy: Always
              resources:
                 requests:
                   cpu: "7"
                   memory: "14Gi"
                 limits:
                   cpu: "7"
                   memory: "14Gi"
          restartPolicy: Never
```
the first yaml `cpu-resource-test-high.yaml`:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: cpu-resource-test-high
  labels:
    app: "test"
spec:
  minAvailable: 5
  schedulerName: volcano
  plugins:
    env: []
  policies:
    - action: RestartJob
      event: PodFailed
    - action: RestartJob
      event: TaskFailed
  priorityClassName: job-high
  tasks:
    - replicas: 5
      name: ps
      policies:
      - action: CompleteJob
        event: TaskCompleted
      template:
        metadata:
          annotations:
          labels:
            app: test-high
        spec:
          containers:
            - command:
              - bash
              args:
              - -c
              - exec sleep 5m
              image: xxx
              name: sidercar
              imagePullPolicy: Always
              resources:
                 requests:
                   cpu: "7"
                   memory: "16Gi"
                 limits:
                   cpu: "7"
                   memory: "18Gi"
            - command:
              - bash
              args:
              - -c
              - exec sleep 5m
              image: xxx
              name: main
              imagePullPolicy: Always
              resources:
                 requests:
                   cpu: "7"
                   memory: "16Gi"
                 limits:
                   cpu: "7"
                   memory: "18Gi"
          restartPolicy: Never
```



> If there is adequate resource, the evicted job should be changed from pending to running. @LivingCcj Would you like to provide your job yaml file?
