### ISSUE TITLE
task container's  life-cycle hook not called

### ISSUE THREAD

**Issue by whitelilis** [volcano-sh/volcano#2687]
**What happened**:
I have added life-cycle hook 'postStart' and 'preStop', but no effect.
**What you expected to happen**:
Life-cycle hook work as k8s pod does;
**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-3
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: volcano-queue-box-b-1611246938842497024
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
              lifecycle:
                postStart:
                  exec:
                    command: ["/bin/sh", "-c", "echo start > /tmp/kkk"]
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "echo end > /tmp/kkk"]
          restartPolicy: Never
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.7.0
- Kubernetes version (use `kubectl version`): 1.20.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-48-generic
- Install tools:
- Others:
