### ISSUE TITLE
Reclaim is not working with GPUSharingEnable if resource used is volcano.sh/gpu-memory

### ISSUE THREAD

**Issue by igormish** [volcano-sh/volcano#2739]
**What happened**:
One node with 480 memory (factor 10)
Having two queues high with weight 3 and low with weight 1.
After adding 4 jobs with requested & limit with volcano.sh/gpu-memory=120 to low queue (weight 1).
Adding new job to high  with requested & limit volcano.sh/gpu-memory=120 queue with (weight 1) volcano does not reclaim the any one of the jobs running in the low queue (weight 1) 

**What you expected to happen**:
I expect one of the jobs in low queue (weight 1)  to move to pending state so that the job in the high queue (weight 3) can start.

**How to reproduce it (as minimally and precisely as possible)**:
Node with allocatble resources 
```
  volcano.sh/gpu-memory:  480
  volcano.sh/gpu-number:  4
```
Have two queues one with low weight 
```
kind: Queue
metadata:
  name: low
spec:
  reclaimable: true
  weight: 1
```
And queue with higher weight
```
kind: Queue
metadata:
  name: low
spec:
  reclaimable: true
  weight: 3
```
3 Jobs for running in low queue 
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
    volcano.sh/preemptable: "true"
    volcano.sh/revocable-zone: '*'
  labels:
    volcano.sh/preemptable: "true"
  name: low //1-4
  namespace: gpu-cluster
spec:
  maxRetry: 3
  minAvailable: 1
  plugins:
    env: []
    ssh: []
    svc:
    - --disable-network-policy=true
  policies:
  - action: RestartJob
    event: PodEvicted
  - action: RestartJob
    event: PodFailed
  queue: low
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 1
    name: low //1-4
    replicas: 1
    template:
      metadata:
        annotations:
          volcano.sh/preemptable: "true"
          volcano.sh/revocable-zone: '*'
        labels:
          volcano.sh/preemptable: "true"
        name: web
      spec:
        containers:
        - image: docker.io/library/nginx:1.14.2
          name: nginx
          resources:
            limits:
              volcano.sh/gpu-memory: 120
            requests:
              volcano.sh/gpu-memory: 120
        tolerations:
        - effect: NoSchedule
          key: gpu_cluster
          operator: Equal
          value: "true"  
```

Job for running in high queue 
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
    volcano.sh/preemptable: "true"
    volcano.sh/revocable-zone: '*'
  labels:
    volcano.sh/preemptable: "true"
  name: high
  namespace: gpu-cluster
spec:
  maxRetry: 3
  minAvailable: 1
  plugins:
    env: []
    ssh: []
    svc:
    - --disable-network-policy=true
  policies:
  - action: RestartJob
    event: PodEvicted
  - action: RestartJob
    event: PodFailed
  queue: high
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 1
    name: high
    replicas: 1
    template:
      metadata:
        annotations:
          volcano.sh/preemptable: "true"
          volcano.sh/revocable-zone: '*'
        labels:
          volcano.sh/preemptable: "true"
        name: web
      spec:
        containers:
        - image: docker.io/library/nginx:1.14.2
          name: nginx
          resources:
            limits:
              volcano.sh/gpu-memory: 120
            requests:
              volcano.sh/gpu-memory: 120
        tolerations:
        - effect: NoSchedule
          key: gpu_cluster
          operator: Equal
          value: "true"  
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version: v1.22.17
- Install tools: helm

- Others:
scheduler.conf:
```
actions: "enqueue, allocate, reclaim, preempt "
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: drf
- plugins:
  - name: proportion
  - name: predicates
    arguments:
      predicate.GPUSharingEnable: true # enable gpu sharing.
  - name: drf
  - name: overcommit
    arguments:
      overcommit-factor: 2.0
  - name: nodeorder
  - name: binpack
  - ```
