### ISSUE TITLE
[Question] How to restrict a certain team only submit jobs to a certain queue?

### ISSUE THREAD

**Issue by gengwg** [volcano-sh/volcano#2790]
*This is not a bug, but rather a question. Given that many people face similar challenges, there must be established best practices to address this issue. It is advisable to seek out these best practices rather than reinventing the wheel.*

For example, Suppose there are two teams, team A and team B. You want to enforce a restriction that only team A can submit jobs to a specific queue, let's say queueA, but not to queueB.

What I did was first create a ClusterRole that grants read permission to Queues since it's a cluster-wide object and not specific to a namespace.

```
# user should NOTE be able to create queues
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volcano-cluster-role
rules:
- apiGroups:
  - scheduling.volcano.sh
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
```

Then for each namespace, I create a role for the group of users to grant write access to Jobs, since it's namespaced.

```
  # user should be able to create jobs
  - apiGroups: ["batch.volcano.sh"]
    resources: ["*"]
    verbs: ["*"]
```

Granting read permission to Queues via ClusterRole allows users to submit jobs to queues, but it doesn't provide a restriction to team B from submitting jobs to queueA. How should I further restrict that? TIA.
