### ISSUE TITLE
can‘t inherit queue name from upper annotations

### ISSUE THREAD

**Issue by zhixian82** [volcano-sh/volcano#2813]
**What happened**:
I create a deployment with yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    scheduling.volcano.sh/queue-name: test
  name: test
  namespace: test
spec:
   ...
      schedulerName: volcano
   ...
```

what i expected is: use volcano to scheduler the deployment pod, and the podGroup(created Automatically).Spec.Queue = test。

But Actually the podGroup.Spec.Queue was set to default.

After dig into the code, I found pod can only inherit annotations with the "volcano.sh/" prefix from upper。However, if you want to set the queue for a PodGroup, the Pod's annotation must include "scheduling.volcano.sh/queue-name: queue-name".

related code：
https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/podgroup/pg_controller_handler.go#L160

https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/podgroup/pg_controller_handler.go#L199

https://github.com/volcano-sh/apis/blob/master/pkg/apis/scheduling/v1beta1/labels.go#L20

https://github.com/volcano-sh/apis/blob/master/pkg/apis/scheduling/v1beta1/labels.go#L44
