### ISSUE TITLE
resourcequota plugin calculate wrong

### ISSUE THREAD

**Issue by zhoushuke** [volcano-sh/volcano#2831]
**What happened**:
when I use resourcequota in my env, I found calculating wrong, may it is a bug..
I use volcano manager AI jobs and deployments , intending to replace kube-scheduler with volcano.

there is a deployment notebook-user-zsk-3 (see below) using veolcano to schedule in namespace which has a resourcequota, cpu: 5c,memory: 5g, requests and limit is the same, cluster resource is bigger than this.
when deployment have a resource, cpu: 2, memory: 2, apply to cluster, podgroup is running, all is find
namespace resourcequota set right,
but 
when deployment have a resource, cpu: 3, memory: 2, apply to cluster,  podgroup is pending, while resourcequota consume to 3/5c, 2/5g

and volcano-scheduler logs show:
```bash
enqueueable false for job: notebook-user-zsk/podgroup-92478a7f-fc17-440c-9cb8-5b3239bb99de, because :resource quota insufficient, requested: map[limits.cpu:{{3 0} {<nil>} 3 DecimalSI} requests.cpu:{{3 0} {<nil>} 3 DecimalSI}], used: map[limits.cpu:{{3 0} {<nil>} 3 DecimalSI} requests.cpu:{{3 0} {<nil>} 3 DecimalSI}], limited: map[limits.cpu:{{5 0} {<nil>} 5 DecimalSI} requests.cpu:{{5 0} {<nil>} 5 DecimalSI}]
```
I try so many times and result is the same. 

is it a race conditions?
when apply a deployment with volcano, resourcequota had consumed, but when session open, get resourcequota wrong value that was been calculating to compare?

**What you expected to happen**:
expecting podgroup in running

**How to reproduce it (as minimally and precisely as possible)**:
maybe it's a bug or a resource race?

**Anything else we need to know?**:
example queue
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: notebook-queue
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "6"
    memory: "8Gi"
  guarantee:
    resource:
      cpu: "2"
      memory: "4Gi"
```

example deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-user-zsk-3
  namespace: notebook-user-zsk
  labels:
    app: notebook-user-zsk-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-user-zsk-3
  template:
    metadata:
      labels:
        app: notebook-user-zsk-3
      annotations:
        #create test queue and use this annotation
        #to make deployment be scheduled into test queue
        scheduling.volcano.sh/queue-name: notebook-queue
    spec:
      # set spec.schedulerName to 'volcano' instead of
      # 'default-scheduler' for deployment.
      schedulerName: volcano
      containers:
        - name: ubuntu
          image: harbor.pl/bj/ubuntu:latest
          command: ['sh', '-c', 'sleep infinity']
          resources:
            requests:
              cpu: "3"
              memory: "2Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
```

volcano configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue,allocate,backfill,reclaim,preempt"
    tiers:
    - plugins:
      - name: priority
      - name: resourcequota
      - name: gang
        enablePreemptable: false
      - name: sla
      - name: nodegroup
        enablePredicate: true
      - name: conformance
    - plugins:
      - name: predicates
      - name: proportion
      - name: drf
      - name: nodeorder
      - name: binpack
```

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.22
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): rocky8.7
- Kernel (e.g. `uname -a`): 4.10
- Install tools: kubeadm
- Others:

**Comment by zhoushuke** [comment]
assign @merryzhou any ideals?

**Comment by zhoushuke** [comment]
after add some debug log in resourcequota.go, I found when apply deployment, resourcequota webhook can update quickly, but when open session, the resourceUsed variable including the value of requestedUsage, so calculated wrong
```golang
newUsage := quotav1.Add(resourcesUsed, requestedUsage)
```
but when use vcjob, everything is fine, so I doube it.

**Comment by wangyang0616** [comment]
I haven't reproduced the problem locally according to your configuration. The result I got is that the deployment can be scheduled normally, and the information is as follows:
```
[root@ecs-4b42-0002 2831]# kubectl describe deployment notebook-user-zsk-3 -n test-wy
Name:                   notebook-user-zsk-3
Namespace:              test-wy
CreationTimestamp:      Thu, 18 May 2023 10:50:05 +0800
Labels:                 app=notebook-user-zsk-3
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=notebook-user-zsk-3
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=notebook-user-zsk-3
  Annotations:  scheduling.volcano.sh/queue-name: notebook-queue
  Containers:
   alpine:
    Image:      alpine
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
      sleep 3600
    Limits:
      cpu:     3
      memory:  2Gi
    Requests:
      cpu:        3
      memory:     2Gi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   notebook-user-zsk-3-7b8d9b544 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  98s   deployment-controller  Scaled up replica set notebook-user-zsk-3-7b8d9b544 to 1
```

queue:
```
Spec:
  Capability:
    Cpu:     6
    Memory:  8Gi
  Guarantee:
    Resource:
      Cpu:      2
      Memory:   4Gi
  Reclaimable:  true
  Weight:       1
Status:
  Allocated:
    Cpu:     3
    Memory:  2Gi
  Reservation:
  Running:  1
  State:    Open
```

namespace:
```
[root@ecs-4b42-0002 2831]# kubectl describe ns test-wy
Name:         test-wy
Labels:       kubernetes.io/metadata.name=test-wy
Annotations:  <none>
Status:       Active

Resource Quotas
  Name:            mem-cpu-demo
  Resource         Used  Hard
  --------         ---   ---
  limits.cpu       3     5
  limits.memory    2Gi   5Gi
  requests.cpu     3     5
  requests.memory  2Gi   5Gi
```

config:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
