### ISSUE TITLE
numa aware 策略不支持deployment 类型的pod

### ISSUE THREAD

**Issue by dykhliww** [volcano-sh/volcano#2861]
**What happened**:
已经设置节点的cpu管理状态为static，拓扑管理器策略为restricted，设置方式是编辑/etc/kubernetes/kubelet文件，添加--cpu-manager-policy=static --topology-manager-policy=restricted,并且重启过kubelet。

deployment.yaml如下
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: numa-tset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: numa-tset
  template:
    metadata:
      labels:
        app: numa-tset
      annotations:
        volcano.sh/numa-topology-policy: single-numa-node    # set the topology policy
    spec:
      containers:
        - name: container-1
          image: nginx:alpine
          resources:
            requests:
              cpu: 2           # 必须为整数，且需要与limits中一致
              memory: 2048Mi
            limits:
              cpu: 2           # 必须为整数，且需要与requests中一致
              memory: 2048Mi
```

taskjob.yaml如下
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vj-test
spec:
  schedulerName: volcano
  minAvailable: 1
  tasks:
    - replicas: 1
      name: "test"
      topologyPolicy: single-numa-node # set the topology policy for task
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: running
              resources:
                limits:
                  cpu: 20
                  memory: "100Mi"
          restartPolicy: OnFailure
```
结果numa-test调度到该节点上，vj-test是pending。

**What you expected to happen**:
numa-test也该是pending状态

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.25.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
- worker节点有两个numa node,每个numa node分别有20个vCPU
