### ISSUE TITLE
After being preempted，vcjob is running，but pods is pending

### ISSUE THREAD

**Issue by renwenlong-github** [volcano-sh/volcano#2884]
**What happened**:
1、I created high and low priority；
2、First create a low-priority vcjob1, after the vcjob 1 runs, create a high-priority vcjob2 to preempt vcjob1;
3、vcjob2 completely preempts vcjob1, the pods of vcjob1 are pending, **but the status of vcjob1 is running**；

**What you expected to happen**:
After being preempted; vcjob1 can give a real response to the status of pods；

**How to reproduce it (as minimally and precisely as possible)**:
You need to ensure that your node is larger than **4c4g**
my config.yaml，Enable preempt actions
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
      - plugins:
          - name: priority
          - name: gang
            enablePreemptable: false
          - name: conformance
          - name: sla
      - plugins:
          - name: overcommit
            arguments:
            overcommit-factor: 1.0
          - name: drf
            enablePreemptable: false
          - name: predicates
          - name: proportion
          - name: nodeorder
          - name: binpack
```

test-queue.yaml
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-queue
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: "4"
    memory: "4Gi"
  guarantee: 
    resource:
      cpu: "4"
      memory: "4Gi"
```

priority-class.yaml
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-tenant-priority
value: 100
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-tenant-priority
value: 10
```

vcjob1.yaml
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob1
spec:
  minAvailable: 1
  schedulerName: volcano
  maxRetry: 5
  queue: test-queue
  priorityClassName: low-tenant-priority
  tasks:
    - replicas: 5
      minAvailable: 1
      name: "master"
      template:
        metadata:
          name: master
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
```

vcjob2.yaml
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob2
  annotations:
    sla-waiting-time: 10s
spec:
  minAvailable: 4
  schedulerName: volcano
  maxRetry: 5
  queue: test-queue
  priorityClassName: high-tenant-priority
  tasks:
    - replicas: 4
      minAvailable: 4
      name: "master"
      template:
        metadata:
          name: master
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
```

Example:
kubectl apply -f config.yaml
kubectl apply -f test-queue.yaml
kubectl apply -f priority-class.yaml
sleep 10
kubectl apply -f vcjob1.yaml

You have to wait for vcjob1 to running
```yaml
kubectl get pods |grep vcjob
vcjob1-master-0                                                 1/1     Running   0             54s
vcjob1-master-1                                                 1/1     Running   0             54s
vcjob1-master-2                                                 1/1     Running   0             54s
vcjob1-master-3                                                 1/1     Running   0             54s
vcjob1-master-4                                                 0/1     Pending   0             54s
```
kubectl apply -f vcjob2.yaml
Error Info:
```yaml
[root@]# kubectl get pods |grep vcjob
vcjob1-master-0                                                 0/1     Pending   0             7s
vcjob1-master-1                                                 0/1     Pending   0             9s
vcjob1-master-2                                                 0/1     Pending   0             9s
vcjob1-master-3                                                 0/1     Pending   0             83s
vcjob1-master-4                                                 0/1     Pending   0             7s
vcjob2-master-0                                                 1/1     Running   0             13s
vcjob2-master-1                                                 1/1     Running   0             13s
vcjob2-master-2                                                 1/1     Running   0             13s
vcjob2-master-3                                                 1/1     Running   0             13s
[root@]# kubectl get pg
NAME                                          STATUS    MINMEMBER   RUNNINGS   AGE
vcjob1-8ad13baa-e1ea-4b84-b6db-454f49287127   Pending   1                      10m
vcjob2-053e224f-e8c7-4c83-9c24-44a6a334b0ca   Running   4           4          26s
[root@]# kubectl get vj
NAME     STATUS    MINAVAILABLE   RUNNINGS   AGE
vcjob1   Running   1                         10m
vcjob2   Running   4              4          32s
```
**vcjob1 is Running, but it should be pending**

**Anything else we need to know?**:
none

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- OS (e.g. from /etc/os-release): any
- Kernel (e.g. `uname -a`): any
- Install tools: node
- Others: none
