### ISSUE TITLE
nuamaware plugin get error in predicates

### ISSUE THREAD

**Issue by dykhliww** [volcano-sh/volcano#2892]
**What happened**:
Using numaaware plugin in volcano, pod is pendind when node's resource is sufficient.  the topology policy is the same between a pod and a node.
**What you expected to happen**:
The pod is running.

**How to reproduce it (as minimally and precisely as possible)**:
The node set static cpu manager policy and singel-numa-node  topology policy.
One pod requests 16 cpu and limits 16 cpu，set single-numa-node policy, the pod is running and use 1-8,21-28 cpu.

cpu_manager_state:
```
{"policyName":"static","defaultCpuSet":"0,9-20,29-39","entries":{"8ef7539b-f3a2-44db-b4a0-1ce6de493159":{"container-1":"1-8,21-28"}}
```
The other pod requests 16 cpu and limit 16 cpu, set single-numa-node policy, but the pod is pending. why the pod is pending when resource is sufficient?

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.25.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
- 
cpu information of the node：
```
node 0 cpus: 0   1  2  3  4  5  6  7  8  9 
             20 21 22 23 24 25 26 27 28 29

node 1 cpus: 10 11 12 13 14 15 16 17 18 19 
             30 31 32 33 34 35 36 37 38 39
```

**Comment by wangyang0616** [comment]
Is it convenient to share your job yaml file? 

In addition, the scheduling log information of the volcano-scheduler, the keyword is the current pod name

**Comment by dykhliww** [comment]
@wangyang0616 

the pending pod yaml
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: numa-tset-single1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numa-tset-single1
  template:
    metadata:
      labels:
        app: numa-tset-single1
      annotations:
              volcano.sh/numa-topology-policy: single-numa-node
    spec:
      containers:
        - name: numa-tset-single1
          image: nginx:alpine
          resources:
            requests:
              cpu: 16           # 必须为整数，且需要与limits中一致
              memory: 2048Mi
            limits:
              cpu: 16          # 必须为整数，且需要与requests中一致
              memory: 2048Mi
      schedulerName: volcano
```
[log.txt](https://github.com/volcano-sh/volcano/files/11632519/log.txt)
