### ISSUE TITLE
podgroup events is inconsistent

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2924]
**What happened**:

![image](https://github.com/volcano-sh/volcano/assets/21003791/1e2d7055-60e1-4b19-b06b-7f76d1383631)

in podgroup events
https://github.com/volcano-sh/volcano/blob/ed5c215d415d98845949d0fde6707cab29621989/pkg/scheduler/cache/cache.go#L1211-L1216

in podgroup condition:
https://github.com/volcano-sh/volcano/blob/ed5c215d415d98845949d0fde6707cab29621989/pkg/scheduler/plugins/gang/gang.go#L181-L184

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy with yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduling.k8s.io/group-name: deploy-with-volcano-pg
    spec:
      schedulerName: volcano
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: deploy-with-volcano-pg
  namespace: default
spec:
  minMember: 2
```
2. `kubectl get podgroups.scheduling.volcano.sh deploy-with-volcano-pg -o yaml` and `kubectl get events |grep deploy-with-volcano-pg` check the event message

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
