### ISSUE TITLE
PodTopologySpread plugin violates maxSkew because pod is added twice in cache. 

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#2928]
**What happened**:
when pods specify topologySpreadConstraints, it should spread evenly across topology key and not violates maxSkew.
**What you expected to happen**:
pods specified topologySpreadConstraints spread evenly and not violates maxSkew.
**How to reproduce it (as minimally and precisely as possible)**:
1. deploy a k8s cluster with three nodes with label topology.kubernetes.io/zone="az1"
2. disable one node schedule with following commands:
`kubectl cordon $node`
3. run a deploy `demo` with replicas=2 and label app=test, also pod template has following spec
```yaml
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
``` 
4. modify node `$node` with with label topology.kubernetes.io/zone="az2"
5. recover $node schedule
`kubectl uncordon $node`
7. scale deploy with replicas=4
`kubectl scale deploy demo --replicas=4`
8. check pods spread 
we can find that new created two pods are not all in az2, az1 has 3 pods, but az2 only has one.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  master
- Kubernetes version (use `kubectl version`): v1.25
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
