### ISSUE TITLE
batch/v1/job is pending status but consume resourcequota

### ISSUE THREAD

**Issue by zhoushuke** [volcano-sh/volcano#2935]
**What happened**:
following is my test environment:
queue capability: 3c, 3Gi
ns resourcequota: 5c,5Gi
a batch/v1 job, resource is 4c,4Gi, apply to cluster,
job status is pending, pg is pending, pod is pending, but resourcequota consumed 4c,4Gi

volcano-scheduler configmap:
```yaml
actions: "enqueue, allocate,backfill,reclaim, preempt"
tiers:
- plugins:
    - name: priority
    - name: proportion
    - name: gang
      enablePreemptable: false
      enableJobStarving: false
      enableReclaimable: false
    - name: conformance
- plugins: 
  - name: predicates
  - name: nodegroup
  - name: resourcequota
  - name: drf
    enablePreemptable: false
  - name: nodeorder
  - name: binpack
```

**What you expected to happen**:
pg is pending is allright, but pod should not be created(as batch/v1 job controlled by build-in controller called job controller, so pod can't be create by delay???), meanwhile, ns resourcequota can't be token.

**How to reproduce it (as minimally and precisely as possible)**:
resourcequota can't be consumed becase pod is pending.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.22
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
