### ISSUE TITLE
The task-topology plugin cannot work with the tasks with empty resource request

### ISSUE THREAD

**Issue by loheagn** [volcano-sh/volcano#2941]
**What happened**:

Assume that we have a kubernetes cluster with two nodes and a simple job with topology annotations:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
    volcano.sh/task-topology-anti-affinity: "nginx"
  name: example-job-1
spec:
  minAvailable: 5
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 2
      name: nginx
      template:
        spec:
          containers:
            - image: nginx
              name: nginx-main
          restartPolicy: OnFailure
    - replicas: 3
      name: mysql
      template:
        spec:
          containers:
            - env:
                - name: MYSQL_ROOT_PASSWORD
                  value: "123456"
              image: mysql
              name: mysql-main
          restartPolicy: OnFailure
```

And the scheduler config file:

```yaml
actions: "enqueue, backfill"
tiers:
  - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: task-topology
```

We create two kind of tasks and we want the two nginx tasks are scheduled into different nodes using the task topology antiAffinity annotations.

But the two nginx tasks are scheduled into the same node in most time:

<img width="943" alt="image" src="https://github.com/volcano-sh/volcano/assets/33423736/fc5f5ef9-31e2-416d-9417-44b0857d854e">

If we add resource requests to the job spec, all things work well as expected:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
    volcano.sh/task-topology-anti-affinity: "nginx"
  name: example-job-1
spec:
  minAvailable: 5
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 2
      name: nginx
      template:
        spec:
          containers:
            - image: nginx
              name: nginx-main
              resources:
                requests:
                  cpu: "0.1"
          restartPolicy: OnFailure
    - replicas: 3
      name: mysql
      template:
        spec:
          containers:
            - env:
                - name: MYSQL_ROOT_PASSWORD
                  value: "123456"
              image: mysql
              name: mysql-main
              resources:
                requests:
                  cpu: "0.3"
          restartPolicy: OnFailure
```

<img width="922" alt="image" src="https://github.com/volcano-sh/volcano/assets/33423736/3e986442-538a-4150-a6d0-9474f2e1915c">

**What you expected to happen**:

The task-topology plugin should work no matter whether the tasks have resource requests.

**How to reproduce it (as minimally and precisely as possible)**:

As described above.

**Anything else we need to know?**:

After reading the code, I found that the allocate action will be skipped if the task has empty resource request: https://github.com/volcano-sh/volcano/blob/ed5c215d415d98845949d0fde6707cab29621989/pkg/scheduler/actions/allocate/allocate.go#L135-L139

This will cause the `TaskOrderFn` and `NodeOrderFn` in `topology.go` be not executed, which may cause the tasks are scheduled into incorrect nodes.

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
  Kustomize Version: v5.0.1
  Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: minikube using hyperkit driver on macOS(Intel)
- Kernel (e.g. `uname -a`): `Linux volcano-demo 5.10.57 #1 SMP Mon Apr 3 23:35:10 UTC 2023 x86_64 GNU/Linux`
