### ISSUE TITLE
volcano scheduler cannot work in 1.5.0 version

### ISSUE THREAD

**Issue by chanecho** [volcano-sh/volcano#2986]
**What happened**:

pod cannot be scheduled when the schedulerName is volcano.

```plain
[root@pc2 test]# kubectl get pods -o wide
NAME                 READY   STATUS    RESTARTS   AGE    IP       NODE     NOMINATED NODE   READINESS GATES
job-sample-nginx-0   0/1     Pending   0          6m4s   <none>   <none>   <none>           <none>

[root@pc2 test]# kubectl describe vcjob job-sample
Status:
  Conditions:
    Last Transition Time:  2023-07-21T06:47:11Z
    Status:                Pending
  Min Available:           1
  Pending:                 1
  State:
    Last Transition Time:  2023-07-21T06:47:11Z
    Phase:                 Pending
  Task Status Count:
    Nginx:
      Phase:
        Pending:  1
Events:
  Type     Reason           Age                    From                   Message
  ----     ------           ----                   ----                   -------
  Warning  PodGroupPending  7m44s (x2 over 7m44s)  vc-controller-manager  PodGroup default:job-sample unschedule,reason: 1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
  Warning  PodGroupPending  7m43s                  vc-controller-manager  PodGroup default:job-sample unschedule,reason: 1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable

[root@pc2 test]# kubectl describe pg job-sample
...
Spec:
  Min Member:  1
  Min Resources:
    Cpu:  1
  Min Task Member:
    Nginx:  1
  Queue:    default
Status:
  Conditions:
    Last Transition Time:  2023-07-21T06:53:43Z
    Message:               1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
    Reason:                NotEnoughResources
    Status:                True
    Transition ID:         2b98cff4-9acb-4aa6-8a2e-61be381fceb3
    Type:                  Unschedulable
  Phase:                   Inqueue
Events:
  Type     Reason         Age                     From     Message
  ----     ------         ----                    ----     -------
  Warning  Unschedulable  6m44s                   volcano  0/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
  Warning  Unschedulable  103s (x300 over 6m43s)  volcano  1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
```

sample yaml:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-sample
spec:
  minAvailable: 1
  schedulerName: volcano
  # schedulerName: default-scheduler
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      template:
        spec:
          containers:
            - command:
              - sleep
              - 12h
              image: nginx:stable-alpine
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
          restartPolicy: Never
```

But, it work when the schedulerName is default-scheduler.

**What you expected to happen**:

The expected status is that the pod can be scheduled when the schedulerName is volcano.

**Environment**:
- Volcano Version: 1.5.0
- Kubernetes version (use `kubectl version`): v1.21.14
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): 2 nodes
   master: Rocky Linux 8.7 (Green Obsidian) 
   worker: Fedora Linux 36 (Server Edition) 
- Kernel (e.g. `uname -a`): 6.1.0
- Install tools:
- Others:
