### ISSUE TITLE
Preemption does not work

### ISSUE THREAD

**Issue by dmitsh** [volcano-sh/volcano#3040]
**What happened**:
I'm trying to preempt a multi-node job in a cluster with 8 nodes.
I have two almost identical jobs. The only difference is that the first job has `low-priority`, while the second job has `high-priority`.
Each job utilizes the entire cluster.
When I start the first job, I can see that all 8 pods are in the `Running` state. But when I start the second job, its pods are `Pending`.

**What you expected to happen**:
I expect the second job to preempt the first one

**How to reproduce it (as minimally and precisely as possible)**:

First, I deploy a low-priority job that uses the entire cluster:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vc1
  namespace: default
spec:
  maxRetry: 5
  minAvailable: 8
  plugins:
    env: []
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodEvicted
  priorityClassName: low-priority
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 8
    name: vc1
    replicas: 8
    template:
      metadata:
        name: vc1
      spec:
        containers:
        - image: nvcr.io/nvidia/pytorch:21.10-py3
          imagePullPolicy: IfNotPresent
          name: vc1
          resources:
            limits:
              cpu: "64"
              memory: 400Gi
              nvidia.com/gpu: "8"
            requests:
              cpu: "64"
              memory: 400Gi
```
I can verify that all 8 pods are in the Running state:
```
$ kubectl get po
NAME        READY   STATUS    RESTARTS   AGE
vc1-vc1-0   1/1     Running   0          8s
vc1-vc1-1   1/1     Running   0          8s
vc1-vc1-2   1/1     Running   0          8s
vc1-vc1-3   1/1     Running   0          8s
vc1-vc1-4   1/1     Running   0          8s
vc1-vc1-5   1/1     Running   0          8s
vc1-vc1-6   1/1     Running   0          8s
vc1-vc1-7   1/1     Running   0          8s
```
Then, I deploy an identical high-priority job:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vc2
  namespace: default
spec:
  maxRetry: 5
  minAvailable: 8
  plugins:
    env: []
    ssh: []
    svc: []
  policies:
  - action: RestartJob
    event: PodEvicted
  priorityClassName: high-priority
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 8
    name: vc2
    replicas: 8
    template:
      metadata:
        name: vc2
      spec:
        containers:
        - image: nvcr.io/nvidia/pytorch:21.10-py3
          imagePullPolicy: IfNotPresent
          name: vc2
          resources:
            limits:
              cpu: "64"
              memory: 400Gi
              nvidia.com/gpu: "8"
            requests:
              cpu: "64"
              memory: 400Gi
```
I would expect that the first job would be preempted by the second job, but this is not happening:
```
$ kubectl get po
NAME        READY   STATUS    RESTARTS   AGE
vc1-vc1-0   1/1     Running   0          27s
vc1-vc1-1   1/1     Running   0          27s
vc1-vc1-2   1/1     Running   0          27s
vc1-vc1-3   1/1     Running   0          27s
vc1-vc1-4   1/1     Running   0          27s
vc1-vc1-5   1/1     Running   0          27s
vc1-vc1-6   1/1     Running   0          27s
vc1-vc1-7   1/1     Running   0          27s
vc2-vc2-0   0/1     Pending   0          21s
vc2-vc2-1   0/1     Pending   0          21s
vc2-vc2-2   0/1     Pending   0          21s
vc2-vc2-3   0/1     Pending   0          21s
vc2-vc2-4   0/1     Pending   0          21s
vc2-vc2-5   0/1     Pending   0          21s
vc2-vc2-6   0/1     Pending   0          21s
vc2-vc2-7   0/1     Pending   0          21s
```
Here is my volcano-scheduler.conf
```
$ kubectl -n volcano-system get cm volcano-scheduler-configmap -o yaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt, reclaim"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: true
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: true
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.7
- Kubernetes version (use `kubectl version`): 1.26
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dmitsh** [comment]
[volcano-scheduler.log](https://github.com/volcano-sh/volcano/files/12318444/volcano-scheduler.log)
[volcano-controllers.log](https://github.com/volcano-sh/volcano/files/12318447/volcano-controllers.log)
attaching logs

**Comment by lowang-bh** [comment]
It seems didn't consider the free resource. Could you please use `-o ` options to output at which node each pod is located.
Then I will check it.

**Comment by dmitsh** [comment]
I changed volcano-scheduler.conf to
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt, reclaim"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
```
Running same test gives same results:
```
$ kubectl get no
NAME                               STATUS   ROLES                  AGE    VERSION
minikube                           Ready    control-plane,master   13d    v1.26.3
virtual-kubelet-5b789d585b-5snnk   Ready    agent                  7m5s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-9tjm9   Ready    agent                  7m2s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-hj6p4   Ready    agent                  7m6s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-jgltj   Ready    agent                  7m3s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-mk5wb   Ready    agent                  7m7s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-mtmdq   Ready    agent                  7m9s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-smzdz   Ready    agent                  7m8s   v1.26.3-vk-nvidia-N/A
virtual-kubelet-5b789d585b-wd6gt   Ready    agent                  7m5s   v1.26.3-vk-nvidia-N/A

kubectl get po -o wide
NAME        READY   STATUS    RESTARTS   AGE   IP        NODE                               NOMINATED NODE   READINESS GATES
vc1-vc1-0   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-wd6gt   <none>           <none>
vc1-vc1-1   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-9tjm9   <none>           <none>
vc1-vc1-2   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-smzdz   <none>           <none>
vc1-vc1-3   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-hj6p4   <none>           <none>
vc1-vc1-4   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-jgltj   <none>           <none>
vc1-vc1-5   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-mtmdq   <none>           <none>
vc1-vc1-6   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-mk5wb   <none>           <none>
vc1-vc1-7   1/1     Running   0          26s   5.6.7.8   virtual-kubelet-5b789d585b-5snnk   <none>           <none>
vc2-vc2-0   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-1   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-2   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-3   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-4   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-5   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-6   0/1     Pending   0          20s   <none>    <none>                             <none>           <none>
vc2-vc2-7   0/1     Pending   0          20s   <none>    <none>                             <non
[volcano-controllers.log](https://github.com/volcano-sh/volcano/files/12318681/volcano-controllers.log)
e>           <none>
```
Logs are attached.
[volcano-scheduler.log](https://github.com/volcano-sh/volcano/files/12318680/volcano-scheduler.log)
