### ISSUE TITLE
Preemption conflicts with the anti-affinity

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#3068]
**What happened**:
The pod is set with a high priority and an anti-affinity policy is set. When the cluster resources are insufficient, preemption is triggered, and the pod is assigned to the node that violates the anti-affinity constraint. 

The next round of scheduling does not meet the anti-affinity policy, and allocate cannot Resources are allocated to pods, resulting in high-priority pods being stuck all the time, and preemptive scheduling fails.
**What you expected to happen**:
Resource preemptive scheduling succeeded.

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://github.com/volcano-sh/volcano/assets/36185952/d6896ee0-6e27-4e11-ae09-5ec86e7d7b29)

```
kubectl label nodes gotc-worker gotc-worker2 gotc-worker3 internal.test.topology/zone=bj
kubectl label nodes gotc-worker4 internal.test.topology/zone=sh
```

deploy1.yaml
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 10
globalDefault: false
description: "This priority class should be used for volcano job only."
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-sh
  labels:
    app: label-sh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-sh
  template:
    metadata:
      labels:
        app: label-sh
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: internal.test.topology/zone
                operator: In
                values:
                - sh
      priorityClassName: low-priority
      schedulerName: volcano
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 1
```
deploy2.yaml
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100
globalDefault: false
description: "This priority class should be used for volcano job only."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-test
  labels:
    app: anti-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anti-test
  template:
    metadata:
      labels:
        app: anti-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - anti-test
            topologyKey: internal.test.topology/zone
      priorityClassName: high-priority
      schedulerName: volcano
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 1
```

Create deploy1, and according to the nodeAffinity policy, all pods are scheduled to gotc-worker4, and the resources are fully occupied.

Create deploy2. According to the anti-affinity policy, at least one pod should be scheduled to gotc-worker4. The priority of deploy2 is higher than that of deploy1. Therefore, deploy2 is expected to preempt the resources of gotc-worker4 node and successfully schedule.

But the actual situation is that only one pod in deploy2 is successfully scheduled, and the other pod is randomly assigned to the gotc-worker or gotc-worker3 node in the preempt phase.

![image](https://github.com/volcano-sh/volcano/assets/36185952/28c2b801-ec63-4dd5-91a0-97808ccebcbe)
![image](https://github.com/volcano-sh/volcano/assets/36185952/fd4f0a4a-ad22-4bb0-bb57-f67e03026a01)

**Anything else we need to know?**:
volcano-scheduler-configmap:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enableJobStarving: false
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
