### ISSUE TITLE
The podgroup will update the status even if there is no change

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#3080]
**What happened**:
If the podgroup does not change, the status will be updated every 1 minute or so, causing unnecessary pressure on the apiserver.

![image](https://github.com/volcano-sh/volcano/assets/36185952/840cc0a9-4bcd-440f-acdc-7a7c89f0d239)

![image](https://github.com/volcano-sh/volcano/assets/36185952/745b9543-b24e-4e9d-b258-cdde3bd6e97d)

**What you expected to happen**:
When the podgroup changes, update it in time. If the podgroup does not change, there is no need to update the status information.

**How to reproduce it (as minimally and precisely as possible)**:
vcjob-test1.yaml
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test
spec:
  schedulerName: volcano
  minAvailable: 3
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: "ps"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: ps
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
    - replicas: 2
      name: "worker"
      policies:
        - event: PodFailed
          action: RestartTask
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: nginx
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: worker
              resources:
                requests:
                  cpu: "1"
```
Create a workload through `vcjob-test.yaml`, find the corresponding podgroup through `kubectl get pg`, and check the status information.

**Anything else we need to know?**:
https://github.com/volcano-sh/volcano/blob/c91eb07f2c300e4d5c826ff11a63b91781b3ac11/pkg/scheduler/framework/job_updater.go#L64-L66

Just remove the judgment here.

**Environment**: k8s v1.25
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
