### ISSUE TITLE
The pod anti-affinity policy does not meet expectations in certain scenarios.

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#3138]
**What happened**:
After a deployment is created and a node anti-affinity policy is configured, pods in the deployment are scheduled to the same node after a period of time, which does not comply with the node anti-affinity policy.

**What you expected to happen**:
The workload for which the node anti-affinity policy is configured cannot be scheduled to the same node.

**How to reproduce it (as minimally and precisely as possible)**:
1. A cluster has only one node. A workload is created and an anti-affinity policy is configured for the node. In this case, only one pod can be scheduled successfully, and the other pod cannot be scheduled due to the anti-affinity constraint, which meets the expectation.
anti-test.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-test
  labels:
    app: anti-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anti-test
  template:
    metadata:
      labels:
        app: anti-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - anti-test
            topologyKey: kubernetes.io/hostname
      priorityClassName: high-priority
      schedulerName: volcano
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
```
2. Create a workload without any affinity or anti-affinity policies.
wy-test.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wy-test
  labels:
    app: wy-test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: wy-test
  template:
    metadata:
      labels:
        app: wy-test
    spec:
      schedulerName: volcano
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 60']
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
```
3. The `wy-test` workload is successfully scheduled, and the pods that violate anti-affinity constraints in anti-test are also successfully scheduled.

**Anything else we need to know?**:
In a scheduling period, if both pods with affinity constraints and pods without affinity constraints are configured, the affinity filtering policy is skipped. As a result, the affinity filtering policy becomes invalid.

The involved code is as follows:
https://github.com/volcano-sh/volcano/blob/015f86b9879d9204ab1607bd6e0f07189c7ecb5e/pkg/scheduler/plugins/predicates/predicates.go#L494-L501

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
