### ISSUE TITLE
Does Volcano support scheduling of resource such as "amd.com/gpu" or "nvidia.com/gpu"?

### ISSUE THREAD

**Issue by dojoeisuke** [volcano-sh/volcano#3170]
#### What would you like to be added:

volcano supports "amd.com/gpu" and "nvidia.com/gpu" resource.

#### Why is this needed:

I want to schedule the launch of a Kubeflow notebook with a specified GPU using volcano.
It seems that Kubeflow notebook currently does not support "volcano.sh/vgpu-number" resouce.

https://www.kubeflow.org/docs/components/notebooks/quickstart-guide/

**Comment by lowang-bh** [comment]
You need to install relative device plugins about "amd.com/gpu" and "nvidia.com/gpu", and then request it in your pod yamls.

**Comment by william-wang** [comment]
@dojoeisuke How is the thing going. Did you try lowang-bh's suggestion?

**Comment by dojoeisuke** [comment]
> @dojoeisuke How is the thing going. Did you try lowang-bh's suggestion?

I attempted to integrate volcano with the GPU operator.

As a result, I found out that Volcano is capable of scheduling requests for "nvidia.com/gpu".

Env:
- volcano v1.8
- gpu operator
- kubernetes 1.24

GPU node:
```bash
root@k8s-tryvolcano-m001:~# k get node k8s-tryvolcano-w002 -ojson | jq .status.allocatable
{
  "cpu": "2",
  "ephemeral-storage": "93492209510",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "8050772Ki",
  "nvidia.com/gpu": "2",
  "pods": "110"
}
```

<details>
<summary>sample-vcjob.yaml</summary>

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job1
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: job
      template:
        spec:
          containers:
            - image: nvidia/cuda:12.2.2-base-ubuntu20.04
              name: gpu
              command: ["sleep"]
              args: ["100000"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "100m"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "100m"
          restartPolicy: Never
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job2
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: job
      template:
        spec:
          containers:
            - image: nvidia/cuda:12.2.2-base-ubuntu20.04
              name: gpu
              command: ["sleep"]
              args: ["100000"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "100m"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "100m"
          restartPolicy: Never
```

</details>

**Launch sample vcjobs**

```bash
root@k8s-tryvolcano-m001:~# k get vcjob
NAME   STATUS    MINAVAILABLE   RUNNINGS   AGE
job1   Running   1              1          2m51s
job2   Running   1              1          2m51s
root@k8s-tryvolcano-m001:~# k get po
NAME         READY   STATUS    RESTARTS   AGE
job1-job-0   1/1     Running   0          3m3s
job2-job-0   1/1     Running   0          3m3s
root@k8s-tryvolcano-m001:~# k exec job1-job-0 -- nvidia-smi -L
GPU 0: NVIDIA A100 80GB PCIe (UUID: GPU-304cf5cc-8ae1-3a75-a2e3-49e2180c23b1)
root@k8s-tryvolcano-m001:~# k exec job2-job-0 -- nvidia-smi -L
GPU 0: NVIDIA A100 80GB PCIe (UUID: GPU-6d4e62a3-44ea-c4ce-3d99-2e4754bc9c5b)
```

**Comment by dojoeisuke** [comment]
In a training job using mnist, it fails in the middle of the training. Is this a problem with Volcano, or is it a problem with the Python code?

<details>
<summary>vcjob manifest for training</summary>

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: train1
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: train1
      template:
        spec:
          containers:
            - image: dojoeisuke/mnist-train:0.1
              name: train1
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "100m"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "100m"
          restartPolicy: Never
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: train2
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: train2
      template:
        spec:
          containers:
            - image: dojoeisuke/mnist-train:0.1
              name: train2
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: "100m"
                limits:
                  nvidia.com/gpu: 1
                  cpu: "100m"
          restartPolicy: Never
```

</details>

<details>
<summary>python mnist</summary>

```python
import tensorflow as tf

gpu_devices = tf.config.experimental.list_physical_devices('GPU')
if gpu_devices:
    print(f"Number of available GPU devices: {len(gpu_devices)}")
    for device in gpu_devices:
        print(f"Device name: {device.name}")
else:
    print("There are no available GPU devices.")

mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

model = tf.keras.models.Sequential([
   tf.keras.layers.Flatten(input_shape=(28, 28)),
   tf.keras.layers.Dense(128, activation='relu'),
   tf.keras.layers.Dense(128, activation='relu'),
   tf.keras.layers.Dropout(0.2),
   tf.keras.layers.Dense(10, activation='softmax')])

model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, validation_split=0.2)
```

</details>


**launch vcjob and result**
```bash
root@k8s-tryvolcano-m001:~# k get vcjob
NAME     STATUS      MINAVAILABLE   RUNNINGS   AGE
train1   Failed      1                         78m
train2   Completed   1                         78m
root@k8s-tryvolcano-m001:~# k get po
NAME              READY   STATUS      RESTARTS   AGE
train1-train1-0   0/1     Error       0          78m
train2-train2-0   0/1     Completed   0          78m
```

[train1.log](https://github.com/volcano-sh/volcano/files/13302989/train1.log)
[train2.log](https://github.com/volcano-sh/volcano/files/13302993/train2.log)
