### ISSUE TITLE
Pods that are scheduled but in pending status cannot be preempted.

### ISSUE THREAD

**Issue by Lily922** [volcano-sh/volcano#3207]
**What happened**:
Pods that are scheduled but in pending status cannot be preempted.

**What you expected to happen**:
Pods that are scheduled but in pending status can be preempted.

**How to reproduce it (as minimally and precisely as possible)**:
1. enable `preempt` actions

```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
   ......
```

2. create deployment with low priority
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-priority-dep
  labels:
    app: low-priority-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: low-priority-dep
  template:
    metadata:
      labels:
        app: low-priority-dep
    spec:
      priorityClassName: low-priority
      schedulerName: volcano
      containers:
      - name: container-1
        image: busybox:none
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'sleep 100000']
        resources: 
          requests: 
            cpu: 500m
            memory: 500Mi
          limits: 
            cpu: 500m
            memory: 500Mi
```
the pods are starting failed because of  reason `ErrImagePull`   
```
#kubectl get pod
NAME                                  READY   STATUS         RESTARTS   AGE
low-priority-dep-7b4bf5d888-b7dz9   0/1     ErrImagePull   0          7s
low-priority-dep-7b4bf5d888-db4bk   0/1     ErrImagePull   0          7s
low-priority-dep-7b4bf5d888-dnkjc   0/1     ErrImagePull   0          7s
low-priority-dep-7b4bf5d888-fwgj4   0/1     ErrImagePull   0          7s
low-priority-dep-7b4bf5d888-grxgk   0/1     ErrImagePull   0          7s
```
3. create deployment with high priority
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100
globalDefault: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-priority-dep
  labels:
    app: high-priority-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: high-priority-dep
  template:
    metadata:
      labels:
        app: high-priority-dep
    spec:
      priorityClassName: high-priority
      schedulerName: volcano
      containers:
      - name: container-1
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'sleep 100000']
        resources: 
          requests: 
            cpu: 500m
            memory: 500Mi
          limits: 
            cpu: 500m
            memory: 500Mi
```
the pods are scheduled failed due to insufficient resources and the pods in the second step with lower priority could not be preempted.  
```

# kubectl get pod
NAME                                  READY   STATUS             RESTARTS   AGE
test-preempt-high-1-7f756b468-2s9hk   0/1     Pending            0          6s
test-preempt-high-1-7f756b468-77fns   0/1     Pending            0          6s
test-preempt-high-1-7f756b468-hjdn7   0/1     Pending            0          6s
test-preempt-high-1-7f756b468-mbnsx   0/1     Pending            0          6s
test-preempt-high-1-7f756b468-xjqrx   0/1     Pending            0          6s
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedScheduling  12s   volcano  0/3 nodes are unavailable: 1 Insufficient memory, 2 Insufficient cpu
```

**Environment**:
- Volcano Version:
- Kubernetes version : 1.23
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
