### ISSUE TITLE
All pods are scheduled in "allocate" action

### ISSUE THREAD

**Issue by Lily922** [volcano-sh/volcano#3227]
**What happened**:
All pods are scheduled in "allocate" action,  even without requesting any resources now.

This problem is caused by the following pull request: https://github.com/volcano-sh/volcano/pull/3188
https://github.com/volcano-sh/volcano/pull/3188/commits/11b7c70bb104156fb962ce5dd26a5cf73dc05a9c#diff-b361e185e6595bd52bd084dae3e830736c2ed7fc17fad7aef218d2a2527a02c9R68

All pods request one "pods" scalar resource now ,  resource function **IsEmpty()** always return **false** because the "one pod" scalar resource request.

**What you expected to happen**:
Schedule the pods which request none resource in "backfill" action.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pod which none of its containers have specified any requests.
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo-pod
  name: demo-pod
  namespace: default
spec:
 containers:
  - name: container-1
    image: busybox:none
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'sleep 100000']
    resources: 
```
2. The pod will be scheduled by "allocate" actions, got it by volcano logs.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
