### ISSUE TITLE
pods in queue's resource capacity will case share value to 1

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3255]
As the picture described,  a queue has allocated pods will cause queue's share to be 1 always, although each of other resource has not used up.

If you're looking for a help then check our [Slack Channel](https://cloud-native.slack.com/messages/volcano) or have a look at our [dev mailing](https://groups.google.com/forum/#!forum/volcano-sh) 
-->

**What happened**:
![image](https://github.com/volcano-sh/volcano/assets/21003791/f23025b6-df61-4ba4-b2bb-5f59b0436d2b)
![image](https://github.com/volcano-sh/volcano/assets/21003791/2defdce8-2586-4218-b212-98d0c2a66e26)

**What you expected to happen**:

share value should less than 1

**How to reproduce it (as minimally and precisely as possible)**:

create a job in one queue, example yaml
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue-a
spec:
  capability:
    cpu: "4"
    memory: "2Gi"
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-high
spec:
  schedulerName: volcano
  priorityClassName: high-priority
  queue: queue-a
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14.2
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "3"
                  memory: "1Gi"
          restartPolicy: OnFailure
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): 1.27
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
```
