### ISSUE TITLE
default queue with a pod has pvc will be overused

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3271]
**What happened**:
<img width="1278" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/bdcae97d-d085-431d-8971-5ae31ebff719">

**What you expected to happen**:

pod scheduled succcessfully with pvc

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-volcano-pvc
spec:
  selector:
    matchLabels:
      app: deployment-volcano-pvc
  replicas: 1
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: pg-volcano-pvc
      labels:
        app: deployment-volcano-pvc
    spec:
      schedulerName: volcano
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '100m'
              memory: 100Mi
            limits:
              cpu: '100m'
              memory: 100Mi
          volumeMounts:
            - mountPath: /mnt/claim
              name: local-vol
      volumes:
        - name: local-vol
          persistentVolumeClaim:
            claimName: claim-for-deployment-volcano-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-for-deployment-volcano-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # storageClassName: csi-lvm # null to use default storage class
  volumeMode: Filesystem
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: pg-volcano-pvc
  namespace: default
spec:
  minMember: 1
  queue: default
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  guarantee:
    resource:
      cpu: 2
      memory: 1Gi
  reclaimable: true
  weight: 1
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): client v1.27.1, server: v1.28.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
