### ISSUE TITLE
Preempt action does not work well when gang is enabled.

### ISSUE THREAD

**Issue by yuyue9284** [volcano-sh/volcano#3291]
**What happened**:
Two nodes in the cluster, one is free, and the other is occupied by a low priority job. Submitting a high priority job requires 2 nodes, the high priority job keeps pending instead of preempting the low priority one.

**What you expected to happen**:
The low priority job should be preempted, and high priority job should run.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Both the preempt and allocate action contains similar logic to discard decision if job is not pipelined. In the case mentioned above, the high priority job will be discarded in the allocate action because there is only one available node, and in the preempt action, the empty node is not considered since there's no victim on that node, and after preempting the low priority job, the high priority job still missing one node to run, thus this decision is also discarded. Ideally in the preempt action, it is better to consider the empty node as well.

https://github.com/volcano-sh/volcano/blob/797e10c321550981dda5e765e652566a70a44254/pkg/scheduler/actions/preempt/preempt.go#L138C1-L144C5

https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/actions/allocate/allocate.go#L277-L284

```golang
                        // Commit changes only if job is pipelined, otherwise try next job.
                        if ssn.JobPipelined(preemptorJob) {
                                stmt.Commit()
                        } else {
                                stmt.Discard()
                                continue
                        }
```

Scheduler config:
```yaml
    actions: "enqueue, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
        enableJobStarving: false
      - name: sla 
        arguments:
          sla-waiting-time: 1m
        enableJobOrder: false
        enableJobPipelined: false 
      - name: conformance
    - plugins:
      - name: gang
      - name: drf
        enablePreemptable: false
    - plugins:
      - name: overcommit
        arguments:
          overcommit-factor: 100
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```

**Environment**:
- Volcano Version: 1.7
- Kubernetes version (use `kubectl version`):
  > Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"7ffcdf755d47c73903854cc5955afcdcd8c95225", GitTreeState:"clean", BuildDate:"2023-10-09T14:43:34Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
