### ISSUE TITLE
PG minResource cal unreasonable，the minReq of minAvailable  tasks  only consider the order in yaml when the priority of tasks  are same

### ISSUE THREAD

**Issue by henrenzhenjumin1111hao** [volcano-sh/volcano#3319]
**What happened**:
If only have 2 GPU in cluster，pg would be pending，pod can not be created, yaml like this.

apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: testVcjob
spec:
  minAvailable: 2
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  tasks:
    - replicas: 1
      name: worker1
      template:
        spec:
          containers:
            - image: ubuntu:latest
              command: ["sh", "-c","sleep 1000000"]
              name: worker1
              resources:
                limits:
                  nvidia.com/gpu: "2"
                requests:
                  nvidia.com/gpu: "2"
          restartPolicy: Never
    - replicas: 2
      name: worker2
      template:
        spec:
          containers:
            - image: ubuntu:latest
              command: ["sh", "-c","sleep 1000000"]
              name: worker2
              resources:
                limits:
                  nvidia.com/gpu: "1"
                requests:
                  nvidia.com/gpu: "1"
          restartPolicy: Never

**What you expected to happen**:
pg minResource should be 2 NOT 3, cluster have 2 GPU, worker2 could be scheduled, so vcjob also could running

**How to reproduce it (as minimally and precisely as possible)**:
acoording to the yaml, could reproduce,the logic in code(job_controller_action.go) onlly in order for same pripority tasks

	minReq := v1.ResourceList{}
	podCnt := int32(0)
	for _, task := range tasksPriority {
		for i := int32(0); i < task.Replicas; i++ {
			if podCnt >= job.Spec.MinAvailable {
				break
			}

			podCnt++
			pod := &v1.Pod{
				Spec: task.Template.Spec,
			}
			minReq = quotav1.Add(minReq, *util.GetPodQuotaUsage(pod))
		}
	}

**Anything else we need to know?**:
no
**Environment**:
- Volcano Version: 1.8.1
- Kubernetes version (use `kubectl version`): 1.28.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
You can set a higher priority for second worker.

**Comment by yaoyinnan** [comment]
@lowang-bh I encountered similar problem.

If the cluster has 2 nodes and each node has 8 nvidia.com/gpu, the following yaml deployment will not be satisfied. The yaml is as follows:

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-1
spec:
  maxRetry: 3
  schedulerName: volcano
  tasks:
    - maxRetry: 3
      name: task-1
      replicas: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-2
      replicas: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-3
      replicas: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-4
      replicas: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-5
      replicas: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
          restartPolicy: OnFailure
```

In theory, there exists a deployment order that can meet the requirements of 5 tasks.

Node w-1: task-5(4) + task-4(4) = 8
Node w-2: task-3(3) + task-2(3) + task-1(2) = 8
Deploying in the order of task-5, task-4, task-3, task-2, task-1 can succeed. However, the order of task deployment is random and may not be satisfied every time. For example, the following order would fail:

In the order of task-5(4), task-3(3), task-4(4), task-2(3), task-1(2), task-1 would fail, and to satisfy the gang plugin, none of the pods would be deployed. According to your suggestion, this situation could be resolved by setting priorities, but setting priorities in multiple task scenarios is relatively complex.

To address this issue, I made some modifications and temporarily added taskOrder to the binpack plugin, sorting based on the descending order of requested extended resources, which can ensure that the scheduling order remains task-5, task-4, task-3, task-2, task-1. However, this has not been thoroughly tested; it is just a temporary attempt.

However, I found that there is still a scenario that cannot be satisfied. When setting minAvailable to 5 and having 3 tasks, each with 5 replicas, the minAvailable is equal to the number of tasks with the same resources in the previous YAML. The YAML is as follows:

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-2
spec:
  maxRetry: 3
  schedulerName: volcano
  minAvailable: 5
  tasks:
    - maxRetry: 3
      name: task-1
      replicas: 5
      minAvailable: 1
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-2
      replicas: 5
      minAvailable: 2
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
          restartPolicy: OnFailure
    - maxRetry: 3
      name: task-3
      replicas: 5
      minAvailable: 2
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: lgl-test
              image: ske.local.cloud.scp:30011/system/lgl_gpu:1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
          restartPolicy: OnFailure
```

In this case, due to the setting of taskOrder in binpack, it will lead to scheduling the 5 pods of task3 that use 4 GPUs first. Therefore, it ultimately cannot be deployed successfully. However, the configuration of minAvailable actually satisfies task3(4) * 2 + task2(3) * 2 + task1(2) * 1, which can meet the requirements of the gang.

I need your advice and assistance regarding these two issues.
