### ISSUE TITLE
use issue: Does it still support other functionalities of the native scheduler after using the Volcano scheduler feature?

### ISSUE THREAD

**Issue by googs1025** [volcano-sh/volcano#3378]
如果我使用 volcano 调度器后，原生defaultscheulder的功能还会保留吗？
我记得是 KubeSchedulerConfiguration 资源对象可以配？我不确定 volcano是怎么样的配置
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        #create test queue and use this annotation
        #to make deployment be scheduled into test queue
        scheduling.volcano.sh/queue-name: test
    spec:
      # set spec.schedulerName to 'volcano' instead of
      # 'default-scheduler' for deployment.
      schedulerName: volcano
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 300m

```
