### ISSUE TITLE
vgpu not restricting memory in the container

### ISSUE THREAD

**Issue by kunal642** [volcano-sh/volcano#3384]
**What happened**:

When running the vgpu example provided in the docs. When vgpu memory limit is set, the container does not respect this limit as shown by the nvidia-smi command(32GB memory is shown as output for V100)

**What you expected to happen**:

The memory inside the container should be limited to vgpu-memory configuration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Nvidia-smi version: 545.23.08
MIG M: NA 

**Environment**:
- Volcano Version: 1.8.x
- Kubernetes version (use `kubectl version`): v1.28.x
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kunal642** [comment]
Hey @archlitchi, Can you suggest something for this?

**Comment by archlitchi** [comment]
> Hey @archlitchi, Can you suggest something for this?

can you show me the yaml file you submitted?

**Comment by kunal642** [comment]
```
 cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod12
spec:
  schedulerName: volcano
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          volcano.sh/vgpu-number: 1
          volcano.sh/vgpu-memory: 3000

nodeSelector: ...
tolerations: ...
EOF
```

**NodeSelector** and **tolerations** are private, therefore can't show them here. Let me know if these properties can also affect the behavior of vgpu
