### ISSUE TITLE
Hard time understanding how PodGroup exactly works

### ISSUE THREAD

**Issue by Gygrus** [volcano-sh/volcano#3431]
This is more of a question about Volcano PodGroup functionality rather than an issue, because I am almost certain that I misunderstood how it works and it confuses me. I tried to find answer in other Github issues topics as well as in the official documentation, but no luck there. 

I have a Kubernetes cluster (created via Minikube) with 4 nodes and Volcano is properly configured. I created a simple queue,

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: tq
  namespace: default
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "4"
    memory: "4096Mi"
```

Then a simple PodGroup with no constraints on resources,

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: pg
  namespace: default
spec:
  queue: tq
```

and finally, a simple job that runs 3 tasks simultaneously, that just sleep for 30 seconds:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob1
  namespace: default
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: tq
  tasks:
    - replicas: 3
      template:
        spec:
          containers:
          - name: dummy-job
            image: gcr.io/k8s-staging-perf-tests/sleep:latest
            imagePullPolicy: IfNotPresent
            args: ["30s"]
            resources:
              requests:
                cpu: 1
                memory: "200Mi"
          restartPolicy: Never
``` 

So now, when I deploy both the queue and the PodGroup, I (wrongly) expected that all created `vcjob1` jobs would run on pods that belong to the defined `pg` PodGroup (as job is connected to the `tq` queue and queue is connected to the `pg` PodGroup), however when the job is running, Volcano creates a new dynamic PodGroup, as if there was no PodGroup assigned to the queue to which jobs were assigned:

![image](https://github.com/volcano-sh/volcano/assets/92525166/52e6916c-c557-4cf1-add1-10fa4670ba52)
![image](https://github.com/volcano-sh/volcano/assets/92525166/b80d14cd-1dfc-407e-845e-486aeb02a5ae)

I've tried multiple different PodGroup configurations, with some MinMembers and MinResources flags defined as well (and I am quite certain that the cluster/jobs have resources to meet those demands), but the result was always the same: jobs were starting a new PodGroup and were executed on pods belonging to that group. So it's clearly how this system should work, but then it raises a couple of questions:

1. What I need to do to make my newly created jobs use my custom PodGroup?
2. What is the exact reason for PodGroups to exist? I thought it was to  What are some use cases that would showcase those reasons? I don't think that documentation covers that part very well, at least the "PodGroup" section.
3. Is `MinMember` PodGroup property the minimum number of pods that a job would require to run? For example, we want to run a job with 3 replicas on our PodGroup, but the PodGroup won't start if its `MinMember` field is set to 4?

Sorry if those questions are trivial and only come from my system misunderstanding, but maybe I'm not the only one who didn't get the idea of PodGroup from the sole documentation and this thread might help them as well.

**Comment by lowang-bh** [comment]
You can have the docs at https://volcano.sh/zh/docs/. Your vcjob doesn't specify a queue and use the default queue

- podgroup: https://volcano.sh/zh/docs/podgroup/
- queue : https://volcano.sh/zh/docs/queue/
- vcjob: https://volcano.sh/zh/docs/vcjob/

**Comment by Gygrus** [comment]
> You can have the docs at https://volcano.sh/zh/docs/. Your vcjob doesn't specify a queue and use the default queue
> 
> * podgroup: https://volcano.sh/zh/docs/podgroup/
> * queue : https://volcano.sh/zh/docs/queue/
> * vcjob: https://volcano.sh/zh/docs/vcjob/

In the yaml file defining my vcjob there is a `queue: tq` tag, so I guess it should point to `tq` queue, not default?

**Comment by PigNatovsky** [comment]
Probably You need to add pod annotation `scheduling.k8s.io/group-name: grouoname`.
This can be done through task.spec.metafata (I think so). If You don't explicity set a podgroup (which is taken from this pod annotation), pod will be added to default podgroup.

**Comment by Gygrus** [comment]
@PigNatovsky Sorry for not being active lately. I tried to add annotation, however I'm not sure if I did this in the right place in the vcjob yaml:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob
  namespace: default
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: tq
  tasks:
    - replicas: 3
      template:
        metadata:
            annotations:
              scheduling.k8s.io/group-name: pg
        spec:
          containers:
          - name: dummy-job
            image: gcr.io/k8s-staging-perf-tests/sleep:latest
            imagePullPolicy: IfNotPresent
            args: ["30s"]
            resources:
              requests:
                cpu: 1
                memory: "200Mi"
          restartPolicy: Never
```

I entered my created podgroup name as the value of annotation. Unfortunately, my vcjobs still don't get assigned to the right podgroup and when the jobs are submited, a dynamic podgroup is being created:
![image](https://github.com/volcano-sh/volcano/assets/92525166/d6d0fb0f-e51d-4b46-ab9c-3ecb7b2266ec)
![image](https://github.com/volcano-sh/volcano/assets/92525166/b4607f01-4779-45af-aef7-ed8626e1454c)

What changed though, is that now dynamic podgroups, as well as created vcjobs, have `tq` as the queue (which is generally good, as I connected the podgroup with `tq` queue). What is weird though is that the dynamic podgroup doesn't run the job, which stay in the pending status. In the dynamic podgroup yaml we can see:
![image](https://github.com/volcano-sh/volcano/assets/92525166/d46c6cb4-e349-4b63-a791-3eef3bb09823)
which isn't very understandable for me. Why Volcano created a podgroup which cannot run specified jobs?

So to conclude, now my vcjobs don't execute, but at least they are assigned to the right queue, so that's progress :)

Actually, now when I removed this additional annotation from the same vcjob yaml file, it seems that the behavior of those jobs is actually the same regardless of the annotation. It's getting more and more confusing, it seems like now I get different results 
then when I created this thread (different queues are getting assigned to the dynamic podgroups and vcjobs, vcjobs stuck in pending status while they were normally executed earlier) and it's somehow nondeterministic (??)

Still, I really appreciate your help and thanks for replying!

**Comment by PigNatovsky** [comment]
Well, `pod group is not ready, 3 minAvailable` and `NotEnoughResources` is pretty self descriptive. You've created a job that has minAvailable set to 3. So it will be not scheduled till will be enough resources in the cluster. How much CPU and Memory do You have as a allocatable resources per node?

**Comment by PigNatovsky** [comment]
Sorry for late response, but I've did some experiments with raw pods. It works as it should:
```
---                                                                                                                                                                                                                                                             
apiVersion: scheduling.volcano.sh/v1beta1                                                                                                                                                                                                                       
kind: PodGroup                                                                                                                                                                                                                                                  
metadata:                                                                                                                                                                                                                                                       
  name: PG                                                                                                                                                                                                                                                      
  namespace: default                                                                                                                                                                                                                                            
spec:                                                                                                                                                                                                                                                           
  minMember: 1                                                                                                                                                                                                                                                  
---                                                                                                                                                                                                                                                             
apiVersion: v1                                                                                                                                                                                                                                                  
kind: Pod                                                                                                                                                                                                                                                       
metadata:                                                                                                                                                                                                                                                       
  annotations:                                                                                                                                                                                                                                                  
    scheduling.volcano.sh/queue-name: QUEUE                                                                                                                                                                                                                     
    scheduling.k8s.io/group-name: PG                                                                                                                                                                                                                            
  name: "pod-QUEUE-NUM"                                                                                                                                                                                                                                         
spec:                                                                                                                                                                                                                                                           
  schedulerName: volcano                                                                                                                                                                                                                                        
  containers:                                                                                                                                                                                                                                                   
  - name: nginx                                                                                                                                                                                                                                                 
    image: nginx:1.14.2                                                                                                                                                                                                                                         
    ports:                                                                                                                                                                                                                                                      
      - containerPort: 80                                                                                                                                                                                                                                       
    resources:                                                                                                                                                                                                                                                  
      requests:                                                                                                                                                                                                                                                 
        cpu: 100m                                                                                                                                                                                                                                               
        memory: 100Mi
```

And then:
```
#!/bin/bash                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                
for n in $(seq 1 $1)                                                                                                                                                                                                                                            
do                                                                                                                                                                                                                                                              
    cat ./pod_template.yaml | sed "s/NUM/$n/g" | sed  "s/QUEUE/$2/g" | sed "s/PG/$3/g" | kubectl apply -f -                                                                                                                                                     
done 
```
in a script called `spawn.sh`. After `./spawn.sh 5 very-important-project exn-u1` I have:

```                                                                                                                                                             
NAME     STATUS    MINMEMBER   RUNNINGS   AGE                                                                                                                                                                                                                   
exn-u1   Running   1           5          16s 
```
So it works perfectly.
