### ISSUE TITLE
How to set different scheduling policies based on different resources?

### ISSUE THREAD

**Issue by microyahoo** [volcano-sh/volcano#3535]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
I deploy volcano with default configmap like below. How to set different scheduling policies based on different resources? For example,  I hope that the allocation of GPU resources is scheduled to the same node as much as possible, in which case `binpack` is satisfied. However, for CPU resources, we hope to schedule them across different nodes as much as possible.
```yaml
~/go/src/deeproute/smd_exporter (release-1.14 ✔) kubectl get -n volcano-system cm volcano-scheduler-configmap -o yaml  
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
```

**Comment by microyahoo** [comment]
We can set the resource weight to 0, so that this resource will not excluded in the score calculation.
https://github.com/volcano-sh/volcano/blob/34836851e6317807267230b1b9508194f81a6f67/pkg/scheduler/plugins/binpack/binpack.go#L213

```yaml
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: binpack
    arguments:
      binpack.weight: 10
      binpack.cpu: 0
      binpack.memory: 0
      binpack.resources: nvidia.com/gpu
      binpack.resources.nvidia.com/gpu: 6
  - name: priority
  - name: gang
    enablePreemptable: false
  - name: conformance
- plugins:
  - name: overcommit
  - name: drf
    enablePreemptable: false
  - name: predicates
  - name: proportion
  - name: nodeorder
```
