### ISSUE TITLE
volcano 案例demo无法调度

### ISSUE THREAD

**Issue by cheng-hunter** [volcano-sh/volcano#3565]
**What do you think about this question?**:
背景:  需要通过volcano代替默认调度器，调度在线业务（deployment与statefulset）和离线业务(目前spark), 发现按照文档安装volcano之后，无法调度任何在线与离线pod.
**Environment**:
- Volcano Version: v1.9.0
- Kubernetes version (use `kubectl version`):  v1.19.9
- Spark on operator version ：v1beta2-1.3.4-3.1.1
1. 安装方式
   kubectl apply -f   https://github.com/volcano-sh/volcano/blob/release-1.9/installer/volcano-development.yaml
2. 安装结果
```
SIT [root@k8s-sit-dcn-share03-master0001 ~]# kubectl get po -n volcano-system 
NAME                                   READY   STATUS      RESTARTS   AGE
volcano-admission-66f5f8dd87-kfbwn     1/1     Running     0          17h
volcano-admission-init-5gzzl           0/1     Completed   0          17h
volcano-controllers-5dbfdf6454-k8j8j   1/1     Running     0          17h
volcano-scheduler-c9c6b6dfc-qwprj      1/1     Running     0          17h
```
3. 部署deployment, ns: spark
queue.yaml
```
#create test queue and then run deployment.
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
  namespace: spark
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: 10
```
nginx.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  namespace: spark
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: spark
      labels:
        app: nginx
      annotations:
        #create test queue and use this annotation
        #to make deployment be scheduled into test queue
        scheduling.volcano.sh/queue-name: test
    spec:
      # set spec.schedulerName to 'volcano' instead of
      # 'default-scheduler' for deployment.
      schedulerName: volcano
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 300m
```
4. 部署结果
```
SIT [root@k8s-sit-dcn-share03-master0001 demo]# kubectl get po -n spark
NAME                                   READY   STATUS    RESTARTS   AGE
deploy-with-volcano-5d55c6649c-g6jvw   0/1     Pending   0          18s
spark-test-pi-driver                   0/1     Pending   0          18h
SIT [root@k8s-sit-dcn-share03-master0001 demo]# kubectl describe po -n spark deploy-with-volcano-5d55c6649c-g6jvw
Name:           deploy-with-volcano-5d55c6649c-g6jvw
Namespace:      spark
Priority:       0
Node:           <none>
Labels:         app=nginx
                pod-template-hash=5d55c6649c
Annotations:    scheduling.k8s.io/group-name: podgroup-2a41bfcb-bf86-4f8a-8814-963709abc9be
                scheduling.volcano.sh/queue-name: test
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/deploy-with-volcano-5d55c6649c
Containers:
  nginx:
    Image:      nginx
    Port:       80/TCP
    Host Port:  0/TCP
    Requests:
      cpu:        300m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pthmp (ro)
Volumes:
  default-token-pthmp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pthmp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```
4. 部署spark
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-test-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "artifactory-dcn.k8s.local/docker-k8sprivate-local/apache/spark:v3.1.3"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - "harbor-secret"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar"
  sparkVersion: "3.1.1"
  batchScheduler: "volcano"
  #hadoopConfigMap: hadoop-conf
  sparkConf:
    #spark.eventLog.enabled: false
    spark.rss.storage.type: MEMORY_LOCALFILE
    spark.executor.extraJavaOptions: "-DlogTarget=Console -DbootstrapServers=127.0.0.1:9092"
    spark.driver.extraJavaOptions: "-DlogTarget=Console -DbootstrapServers=127.0.0.1:9092"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    schedulerName: volcano
    #cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: sfke.role.kubernetes.io/nodeType
              operator: In
              values: 
              - realNode
  executor:
    annotations:
      scheduling.k8s.io/group-name: spark-pi-group
    schedulerName: volcano
    #cores: 1
    coreRequest: "1m"
    coreLimit: "500m"
    instances: 20
    memory: "5000m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: sfke.role.kubernetes.io/nodeType
              operator: DoesNotExist
    tolerations:
    - key: "hollow"
      operator: "Equal"
      value: "true"
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: spark-pi-group
  namespace: spark
spec:
  minMember: 1
  queue: test
```
6. 部署结果
```
SIT [root@k8s-sit-dcn-share03-master0001 demo]# kubectl get po -n spark
NAME                                   READY   STATUS    RESTARTS   AGE
deploy-with-volcano-5d55c6649c-g6jvw   0/1     Pending   0          7m20s
spark-test-pi-driver                   0/1     Pending   0          18h
SIT [root@k8s-sit-dcn-share03-master0001 demo]# kubectl describe po -n spark spark-test-pi-driver
Name:           spark-test-pi-driver
Namespace:      spark
Priority:       0
Node:           <none>
Labels:         spark-app-selector=spark-test-pi
                spark-role=driver
                sparkoperator.k8s.io/app-name=spark-test-pi
                sparkoperator.k8s.io/launched-by-spark-operator=true
                sparkoperator.k8s.io/submission-id=b795f8e7-507e-418b-9548-010585a8e1e1
                version=3.1.1
Annotations:    scheduling.k8s.io/group-name: podgroup-846edf6c-9a1c-4ce9-a2ee-9101f14ca9fd
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  SparkApplication/spark-test-pi
Containers:
  spark-kubernetes-driver:
    Image:       artifactory-dcn.k8s.local/docker-k8sprivate-local/apache/spark:v3.1.3
    Ports:       7078/TCP, 7079/TCP, 4040/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Args:
      driver
      --properties-file
      /opt/spark/conf/spark.properties
      --class
      org.apache.spark.examples.SparkPi
      local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar
    Limits:
      cpu:     1200m
      memory:  896Mi
    Requests:
      cpu:     1
      memory:  896Mi
    Environment:
      SPARK_USER:                 root
      SPARK_APPLICATION_ID:       spark-test-pi
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_DRIVER_POD_NAME:      spark-test-pi-driver (v1:metadata.name)
      SPARK_LOCAL_DIRS:           /var/data/spark-3573e790-8803-417b-b119-b9f3aa61a3df
      SPARK_CONF_DIR:             /opt/spark/conf
    Mounts:
      /opt/spark/conf from spark-conf-volume-driver (rw)
      /tmp from test-volume (rw)
      /var/data/spark-3573e790-8803-417b-b119-b9f3aa61a3df from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-hvjrr (ro)
Volumes:
  spark-local-dir-1:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  spark-conf-volume-driver:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spark-drv-df9438909177b6ca-conf-map
    Optional:  false
  spark-token-hvjrr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spark-token-hvjrr
    Optional:    false
  test-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp
    HostPathType:  Directory
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                   node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:            <none>
```
