### ISSUE TITLE
gpu调度问题

### ISSUE THREAD

**Issue by 13567436138** [volcano-sh/volcano#3624]
**What happened**:
<img width="865" alt="94a5466ab6b9e61d62fc8f42391fb19" src="https://github.com/user-attachments/assets/ad038cff-1c82-4d67-b70a-0198c49f48ac">

<img width="355" alt="181cac69a12fc3a61769eaa739c34b0" src="https://github.com/user-attachments/assets/5c0ccc5b-e9da-4254-988b-0ad6bb6fcd56">
<img width="697" alt="588c270a243cbf2718c20082920b3e9" src="https://github.com/user-attachments/assets/aaa73163-ee78-48e9-ab24-494e16f70cb0">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
apply
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
spec:
  schedulerName: volcano
  containers:
    - name: cuda-container
      image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
      command: ["nvidia-smi"]
      args: ["-l", "30"]
      resources:
        limits:
          volcano.sh/vgpu-cores: 2
          volcano.sh/gpu-memory: 1024 
          volcano.sh/vgpu-number: 1 
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  schedulerName: volcano
  containers:
    - name: cuda-container
      image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
      command: ["nvidia-smi"]
      args: ["-l", "30"]
      resources:
        limits:
          volcano.sh/gpu-memory: 1024
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.9.0
- Kubernetes version (use `kubectl version`): 1.29.0
- Cloud provider or hardware configuration: pve 8
- OS (e.g. from /etc/os-release): unbuntu 2204 server
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Monokaix** [comment]
Please paste the pod event.

**Comment by 13567436138** [comment]
![image](https://github.com/user-attachments/assets/9dc12c0a-1478-454b-95bd-01852990df63)
this is event

**Comment by Monokaix** [comment]
Please also add `volcano.sh/vgpu-number` request for pod.

**Comment by Monokaix** [comment]
Refer the example here: https://github.com/Project-HAMi/volcano-vgpu-device-plugin?tab=readme-ov-file#running-vgpu-jobs

**Comment by 13567436138** [comment]
第一个pod请求了啊，也不能调度

**Comment by 13567436138** [comment]
顺序有关系么？

**Comment by Monokaix** [comment]
> 第一个pod请求了啊，也不能调度

Please try to specify volcano.sh/vgpu-number for all pods.

**Comment by 13567436138** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
spec:
  schedulerName: volcano
  containers:
    - name: cuda-container
      image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
      command: ["nvidia-smi"]
      args: ["-l", "30"]
      resources:
        limits:
          volcano.sh/vgpu-number: 1 
          volcano.sh/vgpu-cores: 2
          volcano.sh/gpu-memory: 1024 
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  schedulerName: volcano
  containers:
    - name: cuda-container
      image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
      command: ["nvidia-smi"]
      args: ["-l", "30"]
      resources:
        limits:
          volcano.sh/vgpu-number: 1 
          volcano.sh/vgpu-cores: 2
          volcano.sh/gpu-memory: 1024
```

不行
