### ISSUE TITLE
Frequent creation and deletion of vcjobs with the same name will cause newly submitted vcjobs to fail directly

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#3770]
### Description

vcjob sets the vcjob policy:
```
policies：
  - event: PodEvicted
     action: TerminateJob
```

Delete the running vcjob, and recreate the vcjob with the same name during the terminating process of its corresponding pod. The newly created vcjob will be affected by the deletion of the old pod and will fail directly.

### Steps to reproduce the issue

1. Create a vcjob, set the corresponding policy, and wait for the vcjob to run. The vcjob example is as follows:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test
spec:
  schedulerName: volcano
  minAvailable: 3
  policies:
    - event: PodEvicted
      action: TerminateJob
  tasks:
    - replicas: 3
      name: "worker"
      template:
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: worker
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
```
2. Delete the vcjob, and recreate a vcjob with the same name during the pod cleanup process
3. Wait for about a minute, and the status of the newly submitted vcjob will be terminated

### Describe the results you received and expected

The newly submitted vcjob with the same name can run successfully

### What version of Volcano are you using?

master
