### ISSUE TITLE
cluster-autoscaler doesn't scale on EKS using volcano scheduler

### ISSUE THREAD

**Issue by Ridhamz-nd** [volcano-sh/volcano#3804]
### Please describe your problem in detail

**Issue**:
When using EKS with CA and min nodes set to 0 for ASG, I am unable to get CA to scale up nodes when using Volcano as the scheduler.
When using `apiVersion: batch/v1` I am able to get ASG to scale up and jobs to be scheduled (config included below).

**Observation**:
After applying volcano job, it stays in `Phase=Pending` state.
I didn't see any errors in scheduler or controller or admission.

**Questions**:
1. Since CA needs have Pods in pending state, is this use case currently supported by Volcano?
1.1. If yes, what next steps can I try for debugging why CA is not detecting pending pods?
1.2 If no, do you recommend any other scheduler?
2. Does the gang plugin in volcano scheduler component have anything to do with this?

Any help is greatly appreciated :)

<details>
<summary>Volcano Installation:</summary>

```bash
#  commit 3ef3bdd7457f380513cfb094e9ad0bc3643c167d
❯ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/refs/heads/master/installer/volcano-development.yaml
```
</details>

<details>
<summary>EKS Node Groups Configuration:</summary>
<br>

```yaml
  - name: worker-nodes-g5-2xlarge-az1
    instanceType: g5.2xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    labels:
      role: worker
      instance: g5.2xlarge
    privateNetworking: true
    availabilityZones: 
      - us-west-2a
    volumeSize: 500
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudwatch: true
    propagateASGTags: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/training-cluster: "owned"

  - name: worker-nodes-g5-2xlarge-az2
    instanceType: g5.2xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    labels:
      role: worker
      instance: g5.2xlarge
    privateNetworking: true
    availabilityZones: 
      - us-west-2b
    volumeSize: 500
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudwatch: true
    propagateASGTags: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/training-cluster: "owned"
```
</details>

<details>
<summary>Cluster Autoscaler:</summary>

```
helm repo add autoscaler https://kubernetes.github.io/autoscaler
helm repo update

helm install cluster-autoscaler autoscaler/cluster-autoscaler --namespace kube-system -f cluster_autoscaler.yaml
```
</details>

<details>
<summary>Job Yaml:</summary>

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: gpu-job-g5-2xlarge
spec:
  minAvailable: 2
  schedulerName: volcano
  # parallelism: 2 # Specifies that the job should run with 2 pods in parallel
  # completions: 2 # Ensures the job completes once all parallel pods have run
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: default

  tasks:
    - replicas: 2
      name: "gpu-container-volcano"
      template:
        metadata:
          labels:
            app: gpu-job
        spec:
          containers:
            - image: <ecr_image>:latest
              imagePullPolicy: IfNotPresent
              name: gpu-container
              command: ["sh", "-c", "echo Hello, Volcano + Kubernetes on g5.2xlarge! && sleep 30"]
              resources:
                limits:
                  nvidia.com/gpu: 1
                requests:
                  nvidia.com/gpu: 1
          restartPolicy: OnFailure
          nodeSelector:
            # node.kubernetes.io/instance-type: g5.2xlarge
            instance: g5.2xlarge
            role: worker
```
</details>

<details>
<summary>Without volcano batch job:</summary>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job-g5-2xlarge
spec:
  parallelism: 2 # Specifies that the job should run with 2 pods in parallel
  completions: 2 # Ensures the job completes once all parallel pods have run
  template:
    metadata:
      labels:
        app: gpu-job
    spec:
      containers:
      - name: gpu-container
        # image: nvidia/cuda:11.0-base
        image: <ecr_image>:latest
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["sh", "-c", "echo Hello, Kubernetes on g5.2xlarge! && sleep 30"]
      restartPolicy: Never
      nodeSelector:
        instance: g5.2xlarge
        role: worker
  backoffLimit: 4
```
</details>

### Any other relevant information

```
❯ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.6-eks-7f9249a
❯ uname -a
Darwin <user>.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
```
OS: Mac OS 14.6.1 (23G93
