### ISSUE TITLE
When a Job is stuck in pending, I would like to know why

### ISSUE THREAD

**Issue by albcui** [volcano-sh/volcano#3834]
### What is the problem you're trying to solve

The scenario I'm having trouble with has to do with Jobs that are stuck in pending due to lack of resources in the cluster.

The Job's status looks something like:
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-11-20T02:39:54Z"
    status: Pending
  state:
    lastTransitionTime: "2024-11-20T02:39:54Z"
    phase: Pending
```

And the PodGroup's status looks like
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-11-20T02:43:26Z"
    message: '1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable'
    reason: NotEnoughResources
    status: "True"
    transitionID: b323ee3f-aed7-42a4-84c4-6131adaa45da
    type: Unschedulable
``` 

The useful information is actually in the PodGroup. However, as a user, I typically just want to interact with `Job` and not the underlying `PodGroup`.

### Describe the solution you'd like

It would be useful if the `Reason` and `Message` in the PodGroup section can propagate to the Job in this scenario.

For example, given the PodGroup above, the Job would now look like

```yaml
status:
  conditions:
  - lastTransitionTime: "2024-11-20T02:39:54Z"
    status: Pending
  state:
    lastTransitionTime: "2024-11-20T02:39:54Z"
    phase: Pending
    reason: NotEnoughResources
    message: '1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable' 
```
