### ISSUE TITLE
Valid policy action `RestartTask` is prevented

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#386]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

```
kubectl apply -f - <<EOF
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job2
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartTask
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: q2
  tasks:
    - replicas: 6
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
          restartPolicy: OnFailure
EOF
```

```
Error from server: error when creating "STDIN": admission webhook "validatejob.volcano.sh" denied the request: 1 error occurred:
	* spec.policies: Invalid value: "RestartTask": invalid policy action

 valid events are [TaskCompleted * PodFailed PodEvicted Unknown], valid actions are [RestartJob TerminateJob CompleteJob ResumeJob AbortJob];
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
