### ISSUE TITLE
How to configure resource reclaim between queues?

### ISSUE THREAD

**Issue by subnet-dev** [volcano-sh/volcano#3861]
### Please describe your problem in detail

Hello Volcano team,  

First of all, thank you for the amazing work on Volcano! I’m evaluating its use to provide GPU access for a large university campus, involving more than 100 research labs and over a thousand users.  

Here are the requirements we are trying to meet:  
- All labs should have equal priority (preemption/reclaim allowed).  
- All users within a lab should have equal priority (preemption/reclaim allowed).  
- GPU types should be prioritized accordingly, as this is a heterogeneous cluster.  
- Users should be able to request a single GPU without preemption/reclaim (e.g., for Jupyter notebooks).  
- GPU allocation should maximize utilization with no resource reservation.  
- Jobs should follow a bin-packing strategy.  
- Job priority should be configurable per lab and per user.  

To evaluate these requirements, I deployed Volcano using the following command:  
```bash  
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml  
```  

I then modified the scheduler configuration as follows:  
```yaml  
volcano-scheduler.conf: |  
  actions: "enqueue, allocate, backfill, reclaim, preempt"  
  tiers:  
  - plugins:  
    - name: priority  
    - name: gang  
      enablePreemptable: false  
    - name: conformance  
    - name: sla  
  - plugins:  
    - name: overcommit  
    - name: drf  
      enablePreemptable: false  
    - name: predicates  
    - name: proportion  
    - name: nodeorder  
    - name: binpack  
```  

I also created two queues to test reclaim:  
```yaml  
apiVersion: scheduling.volcano.sh/v1beta1  
kind: Queue  
metadata:  
  name: queue001  
spec:  
  weight: 1  
  reclaimable: true  
---  
apiVersion: scheduling.volcano.sh/v1beta1  
kind: Queue  
metadata:  
  name: queue002  
spec:  
  weight: 1  
  reclaimable: true  
```  

I simulated full cluster utilization by running jobs in `queue001`:  
```bash  
kubectl create -f - <<EOF  
apiVersion: batch.volcano.sh/v1alpha1  
kind: Job  
metadata:  
  generateName: job-user-a-  
spec:  
  schedulerName: volcano  
  queue: queue001  
  tasks:  
    - replicas: 1  
      name: ubuntu  
      template:  
        spec:  
          terminationGracePeriodSeconds: 2  
          containers:  
            - command:  
              - sleep  
              - 1h  
              image: ubuntu:latest  
              name: ubuntu  
              resources:  
                requests:  
                  cpu: 1  
                limits:  
                  cpu: 1  
          restartPolicy: Never  
EOF  
```  

Finally, I created a job in `queue002` to test reclaim:  
```bash  
kubectl create -f - <<EOF  
apiVersion: batch.volcano.sh/v1alpha1  
kind: Job  
metadata:  
  generateName: job-user-b-  
spec:  
  schedulerName: volcano  
  queue: queue002  
  tasks:  
    - replicas: 1  
      name: ubuntu  
      template:  
        spec:  
          terminationGracePeriodSeconds: 2  
          containers:  
            - command:  
              - sleep  
              - 5m  
              image: ubuntu:latest  
              name: ubuntu  
              resources:  
                requests:  
                  cpu: 1  
                limits:  
                  cpu: 1  
          restartPolicy: Never  
EOF  
```  

Pods, Jobs and queues:
```bash
kubectl get pods,podgroups.scheduling.volcano.sh,queues.scheduling.volcano.sh

NAME                            READY   STATUS    RESTARTS   AGE
pod/job-user-a-4bdpn-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-a-55wbj-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-a-dtvqq-ubuntu-0   1/1     Running   0          5m15s
pod/job-user-a-fpl5c-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-a-gmpcf-ubuntu-0   0/1     Pending   0          5m10s
pod/job-user-a-gpxfz-ubuntu-0   1/1     Running   0          5m15s
pod/job-user-a-j64vz-ubuntu-0   1/1     Running   0          5m15s
pod/job-user-a-kcj2v-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-a-lpxmp-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-a-sdnkm-ubuntu-0   1/1     Running   0          5m10s
pod/job-user-b-7hqzq-ubuntu-0   0/1     Pending   0          4m29s

NAME                                                                                   STATUS    MINMEMBER   RUNNINGS   AGE
podgroup.scheduling.volcano.sh/job-user-a-4bdpn-f3f194ed-85a8-4412-b3f9-235bdd52de86   Running   1           1          5m13s
podgroup.scheduling.volcano.sh/job-user-a-55wbj-dfd4b9eb-d71f-42c8-8f1d-0ed92aa90ad5   Running   1           1          5m15s
podgroup.scheduling.volcano.sh/job-user-a-dtvqq-32b3540c-0fe9-4ebf-ad10-30c36e2a7da7   Running   1           1          5m16s
podgroup.scheduling.volcano.sh/job-user-a-fpl5c-923b55fa-6341-400d-b7aa-2de10ba05793   Running   1           1          5m14s
podgroup.scheduling.volcano.sh/job-user-a-gmpcf-8782584d-007f-4d65-832a-e2404cc941db   Inqueue   1                      5m11s
podgroup.scheduling.volcano.sh/job-user-a-gpxfz-3cdcea49-29eb-4239-ac96-98ae8f384d85   Running   1           1          5m16s
podgroup.scheduling.volcano.sh/job-user-a-j64vz-4d5d1998-0f50-403c-b43d-4175a60a902f   Running   1           1          5m17s
podgroup.scheduling.volcano.sh/job-user-a-kcj2v-aabe950a-99e5-4dd8-89c6-f10485137ffd   Running   1           1          5m12s
podgroup.scheduling.volcano.sh/job-user-a-lpxmp-d865bbad-c2cc-4d31-8229-77497ace9366   Running   1           1          5m12s
podgroup.scheduling.volcano.sh/job-user-a-sdnkm-79460c83-2cbd-4b31-b0d5-84ecba0ef3c0   Running   1           1          5m14s
podgroup.scheduling.volcano.sh/job-user-b-7hqzq-c29b220c-9170-4ae3-8997-506f8127a7af   Inqueue   1                      4m34s

NAME                                   STATUS   RECLAIMABLE   WEIGHT   GUARANTEE   DESERVED   ALLOCATED                             RESERVATION   PARENT
queue.scheduling.volcano.sh/default    Open     true          1        {}                     {"cpu":"0","memory":"0"}              {}
queue.scheduling.volcano.sh/queue001   Open     true          10       {}                     {"cpu":"9","memory":"0","pods":"9"}   {}
queue.scheduling.volcano.sh/queue002   Open     true          10       {}                     {"cpu":"0","memory":"0"}              {}

```

However, it seems that even though reclaim is enabled, the job in `queue002` is unable to reclaim resources from `queue001`.  

Could you please help me achieve the desired result?

### Any other relevant information

Nodes list:
```bash
kubectl get nodes -o wide
NAME            STATUS   ROLES                        AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
talos-5aa-mle   Ready    control-plane,storage-node   6d15h   v1.30.6   192.168.12.11   <none>        Talos (v1.8.3)   6.6.60-talos     containerd://2.0.0
talos-fec-rly   Ready    control-plane,storage-node   6d15h   v1.30.6   192.168.12.13   <none>        Talos (v1.8.3)   6.6.60-talos     containerd://2.0.0
talos-l9h-h79   Ready    storage-node                 6d16h   v1.30.6   192.168.12.14   <none>        Talos (v1.8.3)   6.6.60-talos     containerd://2.0.0
talos-z7n-b0v   Ready    control-plane,storage-node   6d15h   v1.30.6   192.168.12.12   <none>        Talos (v1.8.3)   6.6.60-talos     containerd://2.0.0
```
Nodes taint:
```bash
kubectl get nodes -o='custom-columns=NodeName:.metadata.name,TaintKey:.spec.taints[*].key,TaintValue:.spec.taints[*].value,TaintEffect:.spec.taints[*].effect'
NodeName        TaintKey   TaintValue   TaintEffect
talos-5aa-mle   <none>     <none>       <none>
talos-fec-rly   <none>     <none>       <none>
talos-l9h-h79   <none>     <none>       <none>
talos-z7n-b0v   <none>     <none>       <none>
```

Nodes capacity
```
kubectl get node -o yaml |grep -A 5 capacity:
    capacity:
      cpu: "8"
      ephemeral-storage: 31500Mi
      hugepages-2Mi: "0"
      memory: 16360856Ki
      pods: "110"
--
    capacity:
      cpu: "8"
      ephemeral-storage: 31500Mi
      hugepages-2Mi: "0"
      memory: 16360872Ki
      pods: "110"
--
    capacity:
      cpu: "8"
      ephemeral-storage: 31500Mi
      hugepages-2Mi: "0"
      memory: 16360848Ki
      pods: "110"
--
    capacity:
      cpu: "8"
      ephemeral-storage: 31500Mi
      hugepages-2Mi: "0"
      memory: 16360852Ki
      pods: "110"
```

Scheduler logs: [volcano-scheduler-scheduling-cycle.log](https://github.com/user-attachments/files/18052450/volcano-scheduler-scheduling-cycle.log)

**Comment by hwdef** [comment]
I recommend replacing the `proportion` plugin with the `capacity` plugin. `capacity` is a completely new implementation.
https://github.com/volcano-sh/volcano/blob/master/docs/design/capacity-scheduling.md

By the way, `enqueue` and `preempt` can't coexist

**Comment by PigNatovsky** [comment]
@hwdef What do You mean by `By the way, enqueue and preempt can't coexist`? These two actions can't be used together?

**Comment by hwdef** [comment]
@PigNatovsky Yes, `enqueue` will prevent preemptors from joining the queue

**Comment by PigNatovsky** [comment]
@hwdef So this config used in CI tests is invalid? https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/config/volcano-scheduler-ci.conf

**Comment by subnet-dev** [comment]
Hi @hwdef, thanks for your reply. So I modified the volcano config with the configuration below but the reclaim doesn't seem to work:

```yaml
  volcano-scheduler.conf: |
    actions: "allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
      - name: sla
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: capacity
      - name: nodeorder
      - name: binpack
```

```bash
kubectl get pods,podgroups.scheduling.volcano.sh,queues.scheduling.volcano.sh 
NAME                            READY   STATUS    RESTARTS   AGE
pod/job-user-a-4lptt-ubuntu-0   1/1     Running   0          7m40s
pod/job-user-a-7856f-ubuntu-0   1/1     Running   0          7m41s
pod/job-user-a-dglw8-ubuntu-0   1/1     Running   0          7m41s
pod/job-user-a-dgzsv-ubuntu-0   1/1     Running   0          7m40s
pod/job-user-a-fw4lv-ubuntu-0   1/1     Running   0          7m41s
pod/job-user-a-gl9sl-ubuntu-0   1/1     Running   0          7m40s
pod/job-user-a-jbtg7-ubuntu-0   1/1     Running   0          7m40s
pod/job-user-a-vpdtt-ubuntu-0   0/1     Pending   0          7m40s
pod/job-user-a-z9c6m-ubuntu-0   1/1     Running   0          7m40s
pod/job-user-a-zz9lc-ubuntu-0   1/1     Running   0          7m46s
pod/job-user-b-8l8f4-ubuntu-0   0/1     Pending   0          6m10s

NAME                                                                                   STATUS    MINMEMBER   RUNNINGS   AGE
podgroup.scheduling.volcano.sh/job-user-a-4lptt-9d15dea0-f969-4448-937c-91e316f470d4   Running   1           1          7m44s
podgroup.scheduling.volcano.sh/job-user-a-7856f-b52278fe-e9a0-4709-ab17-e9e9ca8967e0   Running   1           1          7m44s
podgroup.scheduling.volcano.sh/job-user-a-dglw8-711af0f7-cc28-4e63-9c98-466899a4156d   Running   1           1          7m44s
podgroup.scheduling.volcano.sh/job-user-a-dgzsv-9fc60a1f-5949-4c54-86eb-f0b1b58e9745   Running   1           1          7m45s
podgroup.scheduling.volcano.sh/job-user-a-fw4lv-28e2a164-d101-477f-af0f-96e1a225616a   Running   1           1          7m44s
podgroup.scheduling.volcano.sh/job-user-a-gl9sl-52e6d392-c1b9-4c4f-90a6-5e5a3a9880df   Running   1           1          7m45s
podgroup.scheduling.volcano.sh/job-user-a-jbtg7-ed782856-c15a-4165-8be0-8dce91a1d2b0   Running   1           1          7m46s
podgroup.scheduling.volcano.sh/job-user-a-vpdtt-4fcfca44-3c6a-4405-a877-0d6cc5c72846   Inqueue   1                      7m43s
podgroup.scheduling.volcano.sh/job-user-a-z9c6m-278d42ba-cbbc-4d2a-bd96-f838b3e15dfd   Running   1           1          7m45s
podgroup.scheduling.volcano.sh/job-user-a-zz9lc-3d9a8b42-ffaa-4a26-bc1e-439ddf9af1e4   Running   1           1          7m46s
podgroup.scheduling.volcano.sh/job-user-b-8l8f4-8fbce52f-521b-4951-bb93-1475da014de7   Inqueue   1                      6m14s

NAME                                   STATUS   RECLAIMABLE   WEIGHT   GUARANTEE   DESERVED   ALLOCATED                             RESERVATION   PARENT
queue.scheduling.volcano.sh/default    Open     true          1        {}                     {"cpu":"0","memory":"0"}              {}            
queue.scheduling.volcano.sh/queue001   Open     true          1        {}                     {"cpu":"9","memory":"0","pods":"9"}   {}            
queue.scheduling.volcano.sh/queue002   Open     true          1        {}                     {"cpu":"0","memory":"0"}              {} 
```

Do you have any idea why it's not working as expected?

[volcano-scheduler-scheduling-cycle.log](https://github.com/user-attachments/files/18061021/volcano-scheduler-scheduling-cycle.log)

**Comment by hwdef** [comment]
Please set `deserved` for queue

**Comment by JesseStutler** [comment]
I don't think the problem is because `enqueue` and `reclaim` conflict with each other. There is a sla plugin in the first tier that directly allows podgroup enqueue, so there is no conflict. And we can see that podgroup of job-b is already inqueued. Do you have this log:
https://github.com/volcano-sh/volcano/blob/1d9b36f4659fb5fcbaa3873dc93da948bc3ffb5f/pkg/scheduler/actions/reclaim/reclaim.go#L152
And you can set log-level to 4 and check this log:
https://github.com/volcano-sh/volcano/blob/1d9b36f4659fb5fcbaa3873dc93da948bc3ffb5f/pkg/scheduler/plugins/proportion/proportion.go#L226-L227

Besides, I'm wondering that your job just consumed 9 cpus, but your cluster have total of 36 cpus, why can't job-b's pods be allocated normally.

**Comment by subnet-dev** [comment]
Hi @hwdef,

After setting `spec.deserved.cpu` to `1` in the queue configuration, one of the jobs running in `queue001` was indeed suspended to free up a CPU for the job in `queue002`.

I conducted this test using the following Volcano configuration:
```yaml
  volcano-scheduler.conf: |
    actions: "allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
      - name: sla
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: capacity
      - name: nodeorder
      - name: binpack
```

---

Hi @JesseStutler ,

I increased the verbosity level to 4 and defined `spec.deserved.cpu` to `1` for each queue.

Here’s the configuration I used for this test:
```yaml
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
      - name: sla
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: capacity
      - name: nodeorder
      - name: binpack
```

Here are the logs after adding the `enqueue` action and increasing the verbosity to 4: 
[volcano-scheduler-scheduling-cycle.log](https://github.com/user-attachments/files/18081578/volcano-scheduler-scheduling-cycle.log)

Regarding the question of CPU allocation limited to 9, on this small test cluster I have other applications to manage/monitor the cluster installed (rook-ceph, flux, prometheus,...) which use the other CPUs. But the aim is simply to test the scheduler's logic on CPU servers before creating a test cluster with a few GPUs.

---

In both cases, a job from `queue001` was suspended to free up 1 CPU for `queue002`. However, I am still not getting the desired behavior. If I start a second job in `queue002`, it remains pending instead of suspending another job from `queue001`. 

I also tried setting the quota to 100 CPUs for each queue, but in this case, the queues are within their desired quota, so resources are not reclaimed.

What I need is for all queues to have equal priority for resource usage, not just when they are below their quota.

In our context, we will have a situation where each lab has its own queue (+100 labs) sharing 500 GPUs. Ideally, if no other labs are using the cluster, a single lab should be able to utilize all 500 GPUs. However, if a second lab submits jobs, the GPUs should be divided equally (250 GPUs each), and so on.

Do you have any suggestions to achieve this?

Thank you for taking the time to help me!
