### ISSUE TITLE
Why does load plugin depend on GetPluginBuilder

### ISSUE THREAD

**Issue by jxs1211** [volcano-sh/volcano#3892]
### Description

When I walk through the scheduler initialization, I found if the PluginDir is not specified(byDefault), the plugin will not be stored in the `pluginBuilders` at the `server.Run`:
```go
	if opt.PluginsDir != "" {
		err := framework.LoadCustomPlugins(opt.PluginsDir)
		if err != nil {
			klog.Errorf("Fail to load custom plugins: %v", err)
			return err
		}
	}
```
that means the plugin defined in the configmap can't be found and registered through `OnSessionOpen` by plugin name:
```go
func OpenSession(cache cache.Cache, tiers []conf.Tier, configurations []conf.Configuration) *Session {
	ssn := openSession(cache)
	ssn.Tiers = tiers
	ssn.Configurations = configurations
	ssn.NodeMap = GenerateNodeMapAndSlice(ssn.Nodes)
	ssn.PodLister = NewPodLister(ssn)

	for _, tier := range tiers {
		for _, plugin := range tier.Plugins {
			if pb, found := GetPluginBuilder(plugin.Name); !found {
				klog.Errorf("Failed to get plugin %s.", plugin.Name)
			} else {
				plugin := pb(plugin.Arguments)
				ssn.plugins[plugin.Name()] = plugin
				onSessionOpenStart := time.Now()
				plugin.OnSessionOpen(ssn)
				metrics.UpdatePluginDuration(plugin.Name(), metrics.OnSessionOpen, metrics.Duration(onSessionOpenStart))
			}
		}
	}
	return ssn
}
```
So I think the plugin's registration depends on the `pluginBuilders`'s loading, but I don't find the `pluginsDir`'s setting in the manifest
```yaml
      containers:
        - name: volcano-scheduler
          image: docker.io/volcanosh/vc-scheduler:latest
          args:
            - --logtostderr
            - --scheduler-conf=/volcano.scheduler/volcano-scheduler.conf
            - --enable-healthz=true
            - --enable-metrics=true
            - --leader-elect=false
            - --kube-api-qps=2000
            - --kube-api-burst=2000
            - --schedule-period=1s
            - --node-worker-threads=20
            - -v=3
            - 2>&1
```
Is there anything I miss or misunderstand?

### Describe the results you received and expected

the plugin can be registered through manifest without loading `pluginDir`.

### What version of Volcano are you using?

master
