### ISSUE TITLE
PodGroup stuck in Pending Phase 

### ISSUE THREAD

**Issue by caushie-akamai** [volcano-sh/volcano#3910]
### Description

We are currently running the Kubeflow spark-operator on Linode LKE kubernetes with auto-scaling enabled.

I have noticed that when trying to trigger a large auto-scaling (i.e. trying to trigger to use all possible nodes in a node-pool) Volcano pods are stuck in Pending phase and PodGroup is also stuck on pending. 
If I reduce the RAM and CPU request to half, the scaling up will then be triggered and the PodGroup is successful. Not sure why or how the calculation is done in the volcano side.
My volcano config is: 
```
actions: "enqueue, allocate,preempt, backfill"
tiers:
- plugins:
  - name: priority
  - name: conformance
- plugins:
  - name: overcommit
    arguments:  
    overcommit-factor: 15.0
  - name: drf
    enablePreemptable: false
  - name: predicates
  - name: capacity
  - name: nodeorder
  - name: binpack
```
My queue: 
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: myqueue
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "200"
    memory: "1200G"
status:
  state: Open
```
My K8s cluster has auto-scaling enabled in the node-pool with Min 1 and Max 10 nodes (16C,300GB Ram) 

My spark job conf: 
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sleep-2
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: "redacted-private-repo/spark:k8s-3.5.1"
  imagePullSecrets:
    - "regcred"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/sleep_forever.py"
  sparkVersion: "3.5.1"
  batchScheduler: volcano
  batchSchedulerOptions:
    priorityClassName: urgent
    queue: myqueue
  restartPolicy:
    type: Never
  driver:
    cores: 2
    memory: "8G"
    labels:
      version: 3.5.1
    serviceAccount: spark
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "node.kubernetes.io/instance-type"
                  operator: In
                  values:
                    - "g6-dedicated-32"
  executor:
    cores: 15
    instances: 8
    memory: "200G"
    labels:
      version: 3.5.1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "node.kubernetes.io/instance-type"
                  operator: In
                  values:
                    - "g7-highmem-16"
```
I have tried various volcano-scheduler.conf options but the same error persists. 
PodGroup reports:
`1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable`
`queue resource quota insufficient`
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: spark-spark-sleep-2-pg
  namespace: spark
.
.
.
.
status:
  phase: Pending
spec:
  minMember: 1
  minResources:
    cpu: '122'
    memory: 1608G
  priorityClassName: urgent
  queue: myqueue
```

Is anyone aware on how to fix this issue? I removed gang scheduling plugin as per https://github.com/volcano-sh/volcano/issues/2558 but that did not work. 

### Describe the results you received and expected

PodGroup stuck on Pending

### What version of Volcano are you using?

1.10

### Any other relevant information

k8s 1.29

**Comment by lowang-bh** [comment]
`1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
queue resource quota insufficient` your quota in queue spec. capability is not enough.

**Comment by lowang-bh** [comment]
the spec in podgroup shows it need at least 112c and 1608g memory. Does your cluster has enouth idle resource with a overcommit factor equasl 15.0 (real idle resource multiple 15 should large than 112C-608G)？
`spec:
  minMember: 1
  minResources:
    cpu: '122'
    memory: 1608G
`

**Comment by lowang-bh** [comment]
Please paste a log of scheduler.

**Comment by lowang-bh** [comment]
> @lowang-bh Attaching some of the scheduler logs with Log Level =5
> 
> ```
> I1228 20:17:24.110348       1 capacity.go:304] job spark-spark-sleep-2-pg min resource <cpu 132000.00, memory 1708000000000.00>, queue myqueue capability <cpu 112000.00, memory 518674661376.00, hugepages-2Mi 0.00, pods 440.00, attachable-volumes-csi-linodebs.csi.linode.com 252.00, ephemeral-storage 3975709572275000.00, hugepages-1Gi 0.00> allocated <cpu 0.00, memory 0.00> inqueue <cpu 0.00, memory 0.00> elastic <cpu 0.00, memory 0.00>
> I1228 20:17:24.110370       1 capacity.go:310] job spark-spark-sleep-2-pg inqueue false
> I1228 20:17:24.110408       1 enqueue.go:104] Leaving Enqueue ...
>```

queue myqueue capability <cpu 112000.00...> this is real capability, which can not exceed cluster's physical resource.

**Comment by Monokaix** [comment]
> Cluster has auto-scaling enabled, so even though the cluster's physical resources are lower than what the job is asking, that should't that trigger a scale out? (given also that `cluster resources * overcommit < minResources` i guess) In theory be that taken into consideration right?
> 
> If not, what should be the solution in cases like these where the cluster has autoscaling and scales down to 1 node in idle and can scale up to multiple nodes when required?

Thanks for using Volcano! Please feel free to comment on https://github.com/volcano-sh/volcano/issues/3855 if you are convenient so that we can know each other better and gain more help.
1. First of all, The autoscaler and scheduler need to work in coordination, meaning that the autoscaler needs to walk through a simulated scheduling to decide whether it needs to expand or not, so the scaling up and down is predicated on the assumption that they both believe there are not enough resources in cluster.
2. The`enqueue` action is enabled by default, which means pg is in Pending state and Pods under the vcjob weill not be created, and autoscaler actually cann't see the Pending Pod and will not trigger a scale out, you can check the whether the Pods are created.

**Comment by hwdef** [comment]
By the way: 
`enqueue` is conflict with `preempt`. You can only keep one.

**Comment by hwdef** [comment]
Assume that the queue resource is full and job `A` needs to preempt job `B`, but job `A` will be intercepted by `enqueue` and cannot be `inqueue`.

Your problem may be due to other reasons

**Comment by lowang-bh** [comment]
> 2\. The`enqueue` action is enabled by default, which means pg is in Pending state and Pods under the vcjob weill not be created, and autoscaler actually cann't see the Pending Pod and will not trigger a scale out, you can check the whether the Pods are created.

Hi, @caushie-akamai , you can try to remove enqueue plugin and let the job enqueue, so that controller will create those pods, and then autoscaler can see those pending pods and try to scale up.

**Comment by noobzzw** [comment]
Hi，could you give more info in pod status.   Auto-scaling like Karpenter trigger scaling rule is:
- spec.nodeName==“”
- status.phase!=“Succeeded”
- status.phase!=“Failed”
- status.Conditions is PodScheduled ，and status is false，reason is Unschedulable
In my partice, cause by gang plugin, volcnao will mark pod as reason is Schedulable mean Pod can find scheduled, casue by gang plugin it can't run immediately.

**Comment by Monokaix** [comment]
Hi guys, the Karpenter community is willing to solve gang related issue and support custom scheduler, feel free to give some feedbacks to the Karpenter community to make some progress！

**Comment by Monokaix** [comment]
@caushie-akamai Maybe you can enable `overcommit` plugin.

**Comment by igorcalabria** [comment]
HI, we're also evaluating volcano + an autoscaler and hitting a similar issue. Overcommit might mitigate the issue but it's fundamentally at odds with an auto scalable cluster with many different workloads since idle resources might be very low. 

Is it possible to add a config to make queue capacity authoritative when queueing pod groups? If a queue has a capacity for 1000 cpu, it could accommodate groups up to that limit, regardless of current cluster resources. Basically assuming that the auto scaler will be able to fill it.

**Comment by igorcalabria** [comment]
> Were you able to eventually fix this by using the resource "guarantee"?

Yes. 

> How has your testing been so far? 

It works well. We've hit a minor issue with our autoscaler, but that seems unrelated to volcano. 

> I think this would limit us to using a single queue

It works with multiple queues as long as all the other queues configure its resources with "guarantee" instead of deserved. Our use-case is super simple since we're only using queues to limit resource usage in groups, but this may be limiting for more complex scenarios.

> I wonder what the Volcano maintainers think of this proposed solution and if this is the only way to go forward.

Yeah, i think using guarantees is more of a workaround than a solution. From my limited exploration of the code, it seems that current cluster resources is pretty central to the plugins. I think it makes sense to eventually add the concept of cluster elasticity somehow.

**Comment by caushie-akamai** [comment]
I tested this issue on version 1.12 and can confirm that it still persists.

To the Volcano maintainers - do you have any guidance on the recommended path forward? We’re very interested in adopting the Volcano scheduler at our company, as its features align well with our use cases, but this issue is currently a blocker.

I appreciate your insights and look forward to your response.

**Comment by Monokaix** [comment]
> Hi, [@lowang-bh](https://github.com/lowang-bh) sorry for late reply, i got pulled over into some other work and did not have a chance to reply.
> 
> > you can try to remove enqueue plugin and let the job enqueue, so that controller will create those pods, and then autoscaler can see those pending pods and try to scale up.
> 
> Yes this works! But is this the only way to fix this? For context, it might be useful to have enqueue as a plugin enabled with scenarios that require it. Is there any way to make this work with the enqueue plugin enabled?
> 
> Hi [@noobzzw](https://github.com/noobzzw) this is an example of the pod status: (we use the default [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) for now and not Karpenter
> 
> status:
>   conditions:
>   - lastProbeTime: null
>     lastTransitionTime: "2025-03-20T17:40:20Z"
>     message: 'pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable'
>     reason: Unschedulable
>     status: "False"
>     type: PodScheduled
>   phase: Pending
>   qosClass: Burstable

Acatully `enqueue` action  designed for [pod delay creation](https://github.com/volcano-sh/volcano/blob/master/docs/design/delay-pod-creation.md) when using volcano job, if you didn't use volcano job, `enqueue` is not necessary.

**Comment by JesseStutler** [comment]
@caushie-akamai Sorry for the late reply, I think your scenario is very helpful to us. Now after removing the enqueue action, you still can't trigger the cluster autoscaler? BTW, If you have any questions, you can also communicate with us on Slack at any time. We are happy to help you implement Volcano in your company.

**Comment by caushie-akamai** [comment]
Hi @Monokaix  and @JesseStutler  Thank you for your response. 

> Acatully enqueue action designed for [pod delay creation](https://github.com/volcano-sh/volcano/blob/master/docs/design/delay-pod-creation.md) when using volcano job, if you didn't use volcano job, enqueue is not necessary.

Removing `enqueue` works, but I loose on a lot of functionality that `enqueue` provides which is really helpful. 
I actually prefer the functionality of `enqueue` because when I tested this by submitting multiple jobs, the cluster would hit the maximum scale up and while it was able to submit all the jobs, there was a lot of resource fragentation, where I would have expected some jobs to actually be pending because there were not enough resources. I have to note that this also happens when i keep `enqueue` but remove `preempt`. 

Is there anyway to make this work with `enqueue`? 

> @caushie-akamai Sorry for the late reply, I think your scenario is very helpful to us. Now after removing the enqueue action, you still can't trigger the cluster autoscaler? BTW, If you have any questions, you can also communicate with us on Slack at any time. We are happy to help you implement Volcano in your company. 

Hi Jesse, thank you. Please see my response above regarding `enqueue`.  I will also reach out in slack! :D

**Comment by JesseStutler** [comment]
@caushie-akamai 
I tested it and found that the conditions of the pending Pod are the same whether there is an enqueue action or not. I don't know why the cluster autoscaler can work normally after you delete the enqueue action. I want to confirm it. 

In addition, if you don't use vcjob, enqueue action isn't helpful, because allocate action also has alloctable validation, it also has queue-level check, so the effect is the same. Or is there anything you think is helpful but I didn't pay attention to? From your current statement, I can't clearly understand.

If possible, we can actually arrange a meeting to discuss :D

**Comment by caushie-akamai** [comment]
We met with @JesseStutler  and @Monokaix 1-2 weeks ago to discuss this issue and after various rounds of testing we arrived in the same conclusion that the capacity plugin - like @igorcalabria  also suggested - uses whatever cluster resources are available on that moment to determine the realCapability of a queue.
While this is great, it does not work well for elastic systems where autoscaling is needed.

After talking to the maintainers we think that adding a an argument to the capacityPlugin would be the best approach to fix this. 

I am proposing the following argument: 
`overwriteQueueCapability: bool` 

This can be then used as: 

```
volcano-scheduler.conf: |
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: capacity
     overwriteQueueCapability: true
  - name: nodeorder
  - name: binpack
```

This would then allow cases like this to work: 
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: myqueue
spec:
  reclaimable: true
  guarantee:
    resource:
      cpu: "240"
      memory: "4500G" 
status:
  state: Open
```
For example: if a K8s cluster on idle has 48 CPU cores and 96GB ram, when `overwriteQueueCapability: false` then we would get the same behavior like we currently do. The realCapability would be the current cluster resources: {48CPU,96GB RAM}

When `overwriteQueueCapability: true` the realCapability of the cluster capability would be {240CPU,4500G RAM} even though the real cluster resources would be less, this would mean that we could schedule pods and thus trigger a scale-up. 

This would also work well when in cases of hierarchical queues where we can set the root queue capacity equal to the theoretical maximum of a cluster's scale-up resources. 

What do you all think of this approach?

**Comment by JesseStutler** [comment]
```yaml
volcano-scheduler.conf: |
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: capacity
     arguments:
       overwriteQueueCapability: true
  - name: nodeorder
  - name: binpack
```

@caushie-akamai I think writing `overwriteQueueCapability` under capacity's arguments is better. Yes, you're right, we can do it in this way 👍
