### ISSUE TITLE
volcano-sh kube-state-metrics监控项目bug，还维护么

### ISSUE THREAD

**Issue by gsmini** [volcano-sh/volcano#3949]
### Description

1. 我在根据官方文档指引部署指标收集的时候发现收集代码有bug，我在那个仓库提了pr，但是看起来好像大家都不怎么维护那个项目了，所以我过来这边问一下指标收集那个项目还维护么（volcano-sh/kube-state-metrics）：https://github.com/volcano-sh/kube-state-metrics/pull/3

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

理论上收集的应该是只有volcano 标签pod的指标，当前bug是把k8s pod的指标都收集进去了，所以在根据指标配置grafana 看板的时候和v olcano的task匹配不上

### What version of Volcano are you using?

volcanosh/vc-webhook-manager:v1.10.0

**Comment by hwdef** [comment]
Yes, it is also maintained. 
PTAL @Monokaix @JesseStutler

**Comment by gsmini** [comment]
> Yes, it is also maintained.
谢谢辛苦看一下 我的那个pr

**Comment by Monokaix** [comment]
> Yes, it is also maintained. PTAL @Monokaix @JesseStutler

Maybe we can find another way to solve the metrics Introduced in that repo, it's not a good way to do intrusive modification of kube-state-metrics.

**Comment by hwdef** [comment]
> > Yes, it is also maintained. PTAL @Monokaix @JesseStutler
> 
> Maybe we can find another way to solve the metrics introduced in that repo, it's not a good way to do intrusive modification of kube-state-metrics.

I agree with this. I have long wanted to replace the current solution, but I have no good ideas. We may need a new exporter component

**Comment by Monokaix** [comment]
Hi, please use English first, which can allow other users around the world to understand.

**Comment by gsmini** [comment]
> > Yes, it is also maintained. PTAL @Monokaix @JesseStutler
> 
> Maybe we can find another way to solve the metrics introduced in that repo, it's not a good way to do intrusive modification of kube-state-metrics.

Yes, but I saw that the volcano task indicator implementation of the submission record history is also implemented in an intrusive way based on the original k8s kube-state-metrics. So I also adopted this solution at present. In the long run, it may not be the best solution. I also hope that you can come up with a separate component to facilitate the subsequent grafana dashboard business implementation based on the volcano business implementation of custom indicators.
I hope that day will come as soon as possible, and I wish this project will get better and better.

**Comment by gsmini** [comment]
> Hi, please use English first, which can allow other users around the world to understand.

Sorry, the current text has been changed to English.

**Comment by yccharles** [comment]
My temp solution is :  only  keep  volcano's metrics when prometheus scrape kube-state-metrics.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: volcano-monitoring
  name: volcano-kube-state-metrics
  namespace: volcano-monitoring
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      port: http-metrics
      path: /metrics
      scheme: http
      scrapeTimeout: 30s
      metricRelabelings:
        - action: keep
          regex: .*_volcano_.*
          sourceLabels:
            - __name__
        - action: keep
          regex: '.+'
          sourceLabels:
            - queue
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics

``` 

or  config prometheus.yaml by hand 

```
- job_name: volcano-kube-state-metrics
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: .*_volcano_.*
    replacement: $1
    action: keep
  - source_labels: [queue]
    separator: ;
    regex: .+
    replacement: $1
    action: keep

```
