### ISSUE TITLE
Restartjob Action Not Working with PodFailed Event When Job Phase Entering Finished Job State

### ISSUE THREAD

**Issue by yuyue9284** [volcano-sh/volcano#3967]
### Please describe your problem in detail

vcjob with one worker pod and policy like following, if the pod failed, the vcjob will transit into failed state without restarting the job/pod.
```yaml
      policies:
        - events:
          - PodFailed
          - PodEvicted
          action: RestartJob
```

According to the code, the finished state won't execution the action defined in the policies, just want to confirm if this is the by design behaviour: https://github.com/volcano-sh/volcano/blob/68fba2ccb3a6ba00eb511722b6b777eda375e9b4/pkg/controllers/job/state/finished.go#L28-L31

**Comment by Monokaix** [comment]
We are working on that https://github.com/volcano-sh/volcano/pull/3813

**Comment by yuyue9284** [comment]
Hi @Monokaix , in the current implementation, with the above setup, if the pod state changes from running to failed, the failed event should trigger a restart action on the job. However, if the Volcano controller restarts and the default out-of-sync request is handled first, the job's state will become finished before the next failed event, preventing the restart action from being executed, will this be covered by #3813?

Happy path:
job running -> pod failed event -> request with restart -> running state with restart job action executed.

Corner case:
job running -> pod failed event -> somehow out of sync request handled -> job status changed to failed -> request with restart (generated by pod failed) -> finished state won't execute the actions.

**Comment by Monokaix** [comment]
> We are working on that #3813

You can config like
```
spec:
  policies:
  - event: PodFailed
    action: RestartPod
  - event: PodEvicted
    action: RestartJob
    timeout: 10m
```
after that merged.
