### ISSUE TITLE
Karpenter cannot provision node for application when use Volcano

### ISSUE THREAD

**Issue by tieungao88** [volcano-sh/volcano#4030]
**Hi everyone,**
I have a problem:  "Karpenter cannot provision node for application when use Volcano"
**Detail:**
Volcano version: volcano-1.11.0
EKS version: 1.30.0

I deploy a deployment. When bootup, Karpenter worked and provisioned for me one node. After 2 mins, I scaled deployment from one replica to two replica, while the node had cpu ~ 100%. Then, Pod is pendding infinity!.
Deployment:
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: cpu-hog-group
  namespace: default
  annotations:
    scheduling.volcano.sh/pod-group-type: "deployment"
spec:
  minMember: 1
  queue: default
  # priorityClassName: high-priority  # Tùy chọn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog-active-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog-active-01
  template:
    metadata:
      labels:
        app: cpu-hog-active-01
      annotations:
        scheduling.k8s.io/group-name: cpu-hog-group
        scheduling.volcano.sh/pod-group-type: "deployment"
    spec:
      schedulerName: volcano    # Chỉ định sử dụng Volcano scheduler
      # priorityClassName: high-priority    # Tùy chọn
      nodeSelector:
        workload-type: app-schplugin
      tolerations:
        - key: workload-type
          operator: Equal
          value: app-schplugin
          effect: NoSchedule
      containers:
      - name: cpu-hog-active-01
        image: busybox
        resources:
          requests:
            cpu: "100m"
          # limits:
          #   cpu: "1500m"
        command: ["/bin/sh", "-c"]
        args:
        - |
          N=$(nproc)
          for i in $(seq 1 $N); do
            yes > /dev/null &
          done
          wait
```
volcano-scheduler-configmap:
```yaml
actions: "enqueue, allocate, backfill"  
tiers:
  - plugins:
      - name: priority
      - name: gang
      - name: conformance
      - name: usage  # usage based scheduling plugin
        enablePredicate: true  # If the value is false, new pod scheduling is not disabled when the node load reaches the threshold. If the value is true or left blank, new pod scheduling is disabled.
        arguments:
          usage.weight: 5
          cpu.weight: 1
          memory.weight: 1
          thresholds:
            cpu: 80    # The actual CPU load of a node reaches 80%, and the node cannot schedule new pods.
            prometheusMetrics:
              - name: "cpu_usage"
                query: "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)"
                step: 5
  - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
metrics:                               # metrics server related configuration
  type: prometheus                     # Optional, The metrics source type, prometheus by default, support "prometheus", "prometheus_adaptor" and "elasticsearch"
  address: http://dev-ext-prometheus-kube-pr-prometheus.prometheus:9090    # Mandatory, The metrics source address
  interval: 30s                        # Optional, The scheduler pull metrics from Prometheus with this interval, 30s by default
```

Please help me!
