### ISSUE TITLE
Panic when capacity limits the total resource of subqueues

### ISSUE THREAD

**Issue by wzshiming** [volcano-sh/volcano#4104]
### Please describe your problem in detail

<details><summary>volcano-scheduler.conf</summary>
<p>

``` yaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim"
    tiers:
    - plugins:
      - name: priority
      # - name: gang
      #   enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: capacity
        enableHierarchy: true
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
```

</p>
</details> 

<details><summary>2 Jobs</summary>
<p>

``` yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-job-0-1
  namespace: default
spec:
  maxRetry: 3
  minAvailable: 10
  policies:
  - action: RestartJob
    event: PodEvicted
  queue: test-queue-0
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 10
    name: task
    replicas: 10
    template:
      metadata:
        labels:
          test-instance: "1"
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kwok
        containers:
        - args:
          - 30s
          image: hello-world
          name: sleep
          resources:
            requests:
              cpu: "1"
              memory: 100Mi
        restartPolicy: Never
        tolerations:
        - effect: NoSchedule
          key: kwok.x-k8s.io/node
          operator: Exists
  ttlSecondsAfterFinished: 1
status:
  conditions:
  - lastTransitionTime: "2025-03-18T05:54:48Z"
    status: Pending
  minAvailable: 10
  state:
    lastTransitionTime: "2025-03-18T05:54:48Z"
    phase: Pending
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-job-1-2
  namespace: default
spec:
  maxRetry: 3
  minAvailable: 10
  policies:
  - action: RestartJob
    event: PodEvicted
  queue: test-queue-1
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 10
    name: task
    replicas: 10
    template:
      metadata:
        labels:
          test-instance: "1"
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kwok
        containers:
        - args:
          - 30s
          image: hello-world
          name: sleep
          resources:
            requests:
              cpu: "1"
              memory: 100Mi
        restartPolicy: Never
        tolerations:
        - effect: NoSchedule
          key: kwok.x-k8s.io/node
          operator: Exists
  ttlSecondsAfterFinished: 1
status:
  conditions:
  - lastTransitionTime: "2025-03-18T05:54:48Z"
    status: Pending
  minAvailable: 10
  state:
    lastTransitionTime: "2025-03-18T05:54:48Z"
    phase: Pending
```

</p>
</details> 

<details><summary>Queues</summary>
<p>

``` yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  guarantee: {}
  parent: root
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "0"
    memory: "0"
  reservation: {}
  state: Open
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: root
spec:
  deserved:
    cpu: "32"
    ephemeral-storage: "75125227520"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 65418208Ki
    pods: "110"
  guarantee:
    resource:
      cpu: "0"
      memory: "0"
  reclaimable: false
  weight: 1
status:
  allocated:
    cpu: "0"
    memory: "0"
  reservation: {}
  state: Open
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-queue-0
spec:
  deserved:
    cpu: 8
    memory: 100Gi
  guarantee:
    resource:
      cpu: 6
      memory: 50Gi
  parent: test-queue-root
  reclaimable: true
  weight: 1
status:
  allocated: {}
  state: Open
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-queue-1
spec:
  deserved:
    cpu: 8
    memory: 100Gi
  guarantee:
    resource:
      cpu: 6
      memory: 50Gi
  parent: test-queue-root
  reclaimable: true
  weight: 1
status:
  allocated: {}
  state: Open
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test-queue-root
spec:
  capability:
    cpu: 10
    memory: 150Gi
  parent: root
  reclaimable: true
  weight: 1
status:
  allocated: {}
  state: Open
```

</p>
</details> 

It seems that the sum of the guarantee of the two queues exceeds the capability of the parent, but we should not Panic

<details><summary>Panic Logs</summary>
<p>

```
I0318 05:54:49.501864       1 cache.go:1559] The metrics type is not set in the volcano scheduler configmap file. As a result, the CPU and memory load information of the node is not collected.
I0318 05:54:49.502621       1 cache.go:1416] There are <2> Jobs, <5> Queues and <6> Nodes in total for scheduling.
I0318 05:54:49.502691       1 session.go:198] Open Session d9a5b669-c6a0-4a9d-9a3d-e552146c692a with <2> Job and <5> Queues
E0318 05:54:49.503462       1 assert.go:33] "Observed a panic" panic="resource is not sufficient to do operation: <cpu 10000.00, memory 161061273600.00, pods 660.00, ephemeral-storage 75125227520000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00> sub <cpu 12000.00, memory 107374182400.00>" stacktrace=<
        goroutine 426 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x28f8258, 0x3ef6500}, {0x206a720, 0xc00089c8c0})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
        k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x28f8258, 0x3ef6500}, {0x206a720, 0xc00089c8c0}, {0x3ef6500, 0x0, 0x10000000043d705?})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
        k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00072b880?})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
        panic({0x206a720?, 0xc00089c8c0?})
                /usr/local/go/src/runtime/panic.go:770 +0x132
        volcano.sh/volcano/pkg/scheduler/util/assert.Assert(0xa0?, {0xc0008300e0?, 0xc0008090a0?})
                /go/src/volcano.sh/volcano/pkg/scheduler/util/assert/assert.go:33 +0x165
        volcano.sh/volcano/pkg/scheduler/util/assert.Assertf(0x0, {0x26070a0?, 0x7f509eecc500?}, {0xc0008090a0?, 0xc000b80008?, 0xc000bf7860?})
                /go/src/volcano.sh/volcano/pkg/scheduler/util/assert/assert.go:43 +0x4a
        volcano.sh/volcano/pkg/scheduler/api.(*Resource).Sub(0xc000bad840, 0xc000bad800)
                /go/src/volcano.sh/volcano/pkg/scheduler/api/resource_info.go:260 +0x90
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).checkHierarchicalQueue(0xc0008a5710, 0xc0009e6750)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:679 +0x407
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).checkHierarchicalQueue(0xc0008a5710, 0xc0009e67e0)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:705 +0x845
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).buildHierarchicalQueueAttrs(0xc0008a5710, 0xc0001d8c00)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:503 +0xf45
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).OnSessionOpen(0xc0008a5710, 0xc0001d8c00)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:105 +0x230
        volcano.sh/volcano/pkg/scheduler/framework.OpenSession({0x2911618?, 0xc00029fb88?}, {0xc000177230, 0x2, 0x2}, {0x0, 0x0, 0x0})
                /go/src/volcano.sh/volcano/pkg/scheduler/framework/framework.go:45 +0x312
        volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000648180)
                /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:117 +0x29d
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00005a5d0, {0x28d6380, 0xc000981140}, 0x1, 0xc000214480)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
        k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005a5d0, 0x3b9aca00, 0x0, 0x1, 0xc000214480)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
        k8s.io/apimachinery/pkg/util/wait.Until(...)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
        created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 1
                /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:91 +0x1a7
 >
panic: resource is not sufficient to do operation: <cpu 10000.00, memory 161061273600.00, pods 660.00, ephemeral-storage 75125227520000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00> sub <cpu 12000.00, memory 107374182400.00> [recovered]
        panic: resource is not sufficient to do operation: <cpu 10000.00, memory 161061273600.00, pods 660.00, ephemeral-storage 75125227520000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00> sub <cpu 12000.00, memory 107374182400.00>

goroutine 426 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x28f8258, 0x3ef6500}, {0x206a720, 0xc00089c8c0}, {0x3ef6500, 0x0, 0x10000000043d705?})
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:89 +0xee
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00072b880?})
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
panic({0x206a720?, 0xc00089c8c0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
volcano.sh/volcano/pkg/scheduler/util/assert.Assert(0xa0?, {0xc0008300e0?, 0xc0008090a0?})
        /go/src/volcano.sh/volcano/pkg/scheduler/util/assert/assert.go:33 +0x165
volcano.sh/volcano/pkg/scheduler/util/assert.Assertf(0x0, {0x26070a0?, 0x7f509eecc500?}, {0xc0008090a0?, 0xc000b80008?, 0xc000bf7860?})
        /go/src/volcano.sh/volcano/pkg/scheduler/util/assert/assert.go:43 +0x4a
volcano.sh/volcano/pkg/scheduler/api.(*Resource).Sub(0xc000bad840, 0xc000bad800)
        /go/src/volcano.sh/volcano/pkg/scheduler/api/resource_info.go:260 +0x90
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).checkHierarchicalQueue(0xc0008a5710, 0xc0009e6750)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:679 +0x407
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).checkHierarchicalQueue(0xc0008a5710, 0xc0009e67e0)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:705 +0x845
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).buildHierarchicalQueueAttrs(0xc0008a5710, 0xc0001d8c00)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:503 +0xf45
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).OnSessionOpen(0xc0008a5710, 0xc0001d8c00)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:105 +0x230
volcano.sh/volcano/pkg/scheduler/framework.OpenSession({0x2911618?, 0xc00029fb88?}, {0xc000177230, 0x2, 0x2}, {0x0, 0x0, 0x0})
        /go/src/volcano.sh/volcano/pkg/scheduler/framework/framework.go:45 +0x312
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000648180)
        /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:117 +0x29d
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00005a5d0, {0x28d6380, 0xc000981140}, 0x1, 0xc000214480)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005a5d0, 0x3b9aca00, 0x0, 0x1, 0xc000214480)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 1
        /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:91 +0x1a7
```

</p>
</details>
