### ISSUE TITLE
Is it possible to setting CNI IP capacity for per Queue?

### ISSUE THREAD

**Issue by openxxs** [volcano-sh/volcano#4130]
### Please describe your problem in detail

Volcano Version: 1.7.0

There is requirement to limit the IP amounts for some Queue, Queue Yaml Example:
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  labels:
    queue-scene: offline
    queue-type: public
  name: default-offline
spec:
  capability:
    cpu: 120
    memory: 960Gi
    cce.baidubce.com/ip: 100  # setting this special CNI IP Resource
  guarantee:
    resource:
      cpu: 0
      memory: 0
  reclaimable: false
  weight: 1
```
