### ISSUE TITLE
:bug: ENV 'WORLD_SIZE' counting method of pytorch-plugin

### ISSUE THREAD

**Issue by Hcryw** [volcano-sh/volcano#4166]
### Description

In a PyTorch job, the `RANK` is calculated based on the `taskType`, with only "master" and "worker" tasks being considered. However, when calculating `WORLD_SIZE` with the `getTotalReplicas` function, replicas of all tasks within the VCJob will be counted: 

https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go#L94-L115

This causes an issue when we try to add an extra `Task` specifically for collecting and displaying TensorBoard logs. The calculated `WORLD_SIZE` is 1 greater than the actual number, leading to a mismatch between the expected number of connections and `WORLD_SIZE` in PyTorch DDP, which ultimately results in a timeout during node synchronization.

### Steps to reproduce the issue

1. Create a VCJob with `pytorch` plugin which contains 2 tasks, a master with replicas 1 and a worker with replicas 1.
2. Add a 'tensorboard' task with replicas 1 to gather logs.
3. `WORLD_SIZE` will be 3 instead of 2.
4. eg: 
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test
  namespace: default
spec:
  plugins:
    svc: []
    pytorch:
      - '--master=master'
      - '--worker=worker'
      - '--port=23456'
  maxRetry: 3
  tasks:
    - replicas: 1
      name: master
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          imagePullSecrets: null
          containers:
            - image: nvcr.io/nvidia/cuda:12.4.1-cudnn-devel-ubuntu20.04
              imagePullPolicy: IfNotPresent
              name: master
              args:
                - sleep inf
              command:
                - bash
                - '-c'
              resources:
                requests:
                  cpu: '1'
                  memory: 1Gi
                limits:
                  cpu: '1'
                  memory: 1Gi
          restartPolicy: Never
    - replicas: 1
      name: worker
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          imagePullSecrets: null
          containers:
            - image: nvcr.io/nvidia/cuda:12.4.1-cudnn-devel-ubuntu20.04
              imagePullPolicy: IfNotPresent
              name: worker
              args:
                - sleep inf
              command:
                - bash
                - '-c'
              resources:
                requests:
                  cpu: '1'
                  memory: 1Gi
                limits:
                  cpu: '1'
                  memory: 1Gi
          restartPolicy: Never
    - replicas: 1
      name: tensorboard
      template:
        spec:
          containers:
            - args:
                - tensorboard --logdir=/data --port=6006
              command:
                - bash
                - '-c'
              image: tensorflow/tensorflow:latest
              imagePullPolicy: IfNotPresent
              name: tensorboard
              ports:
                - containerPort: 6006
                  name: tensorboard
                  protocol: TCP
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                requests:
                  cpu: '1'
                  memory: 1Gi
          restartPolicy: Never
  queue: default
  schedulerName: volcano
```

### Describe the results you received and expected

We hope that env 'WORLD_SIZE' can be calculated according to `taskType`, counting only the replicas under the `master` and `worker` tasks.

### What version of Volcano are you using?

v1.11.0
