### ISSUE TITLE
Is it possible to block podgroups from transitioning from "Completed" to "Inqueue"?

### ISSUE THREAD

**Issue by igorcalabria** [volcano-sh/volcano#4195]
### Please describe your problem in detail

Is it possible to prevent a PodGroup from transitioning back to the "InQueue" state once it has reached the "Completed" state?

## Use Case
- I have a workflow manager responsible for creating the PodGroup
- This workflow manager creates the first pod associated with the PodGroup, which is the primary controller that manages tasks
- This "master" pod launches several other pods associated with the PodGroup
- The success/failure of the entire job is determined solely by this first "master" pod
- Ideally, I would set the ownership of the PodGroup to the first pod, but there's a circular dependency (need the PodGroup before creating the "master" pod)
- The main issue occurs when the first pod is cleaned up after completion while the associated PodGroup remains
- This orphaned PodGroup then transitions back to "InQueue" state and continues holding queue resources
Currently, we delete the PodGroup after completion, but this approach isn't robust enough

I'm sorry if this was asked before or is in the documentation. Tried to find some info, with no success. Thanks!

**Comment by hwdef** [comment]
Please set pod.spec.restartPolicy=Never

**Comment by igorcalabria** [comment]
It doesn't help. Consider the following example: 

create a pg
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  generateName: test-pg-
spec:
  minMember: 1
  minResources:
    cpu: "1"
  queue: test
```

Then run a pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  annotations:
    scheduling.k8s.io/group-name: test-pg-zv8jv
spec:
  schedulerName: volcano
  restartPolicy: Never
  schedulerName: volcano
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 1']
```

after the pod completes (or fails). The Podgroup is marked as completed:
```
NAME            STATUS      MINMEMBER   RUNNINGS   AGE
test-pg-n2vmp   Completed   1                      21s
```

But, if some other process deletes the pod

```
pod "busybox-sleep" deleted
```

The podgroup goes back to "InQueue" status

```
NAME            STATUS    MINMEMBER   RUNNINGS   AGE
test-pg-n2vmp   Inqueue   1                      88s
```

There are some workarounds to this, like ensuring that you also delete the podgroup when your workflow finishes, or patching the pg ownerReferences to the pod

```
kubectl patch --type=merge pg test-pg-8gwg4 -p '{"metadata": {"ownerReferences": [{"apiVersion": "v1", "kind": "pod", "name": "busybox-sleep", "uid": "0fa0f054-4ce1-4a67-b081-d5ce38e43216"}]}}'
```

Both are a bit clunky and that's why I was asking if its possible to make the podgroup lifecycle more strict. By strict, I mean never transitioning from "Completed" to other states.

**Comment by hwdef** [comment]
OK, I understand what you mean, this may be a bug, it should be fixed

**Comment by hwdef** [comment]
> But, if some other process deletes the pod

Why do other processes only delete pods instead of podgroups? They should be bound relationship

**Comment by igorcalabria** [comment]
> Why do other processes only delete pods instead of podgroups?

This system in particular has some garbage collection strategies where it occasionally deletes completed pods. 

> They should be bound relationship

Yes. I agree and this can be achieved using the patching strategy I mentioned earlier. If the pod is deleted, so is the podgroup. The only annoying part is this circular dependency between the pod and the pogroup: The pod is only created after the podgroup but the podgroup "needs" its ownership reference to be set to the pod. This can is mitigated by patching the podgroup after the pod is created, but not really ideal.

**Comment by hwdef** [comment]
How about create pod directly.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
# delete this
#  annotations:
#    scheduling.k8s.io/group-name: test-pg-zv8jv
spec:
  schedulerName: volcano
  restartPolicy: Never
  schedulerName: volcano
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 1']
```

The podgroup will be create automatically.
And the podgroup will be delete automatically when pod is deleted
