### ISSUE TITLE
PyTorch plugin set `WORLD_SIZE` to total number of replicas in the job, not just the ones for master and worker tasks

### ISSUE THREAD

**Issue by antoinebrl** [volcano-sh/volcano#4238]
### Description

Hello 👋 !

I am currently working on a training job that utilizes PyTorch, where each rank needs to interact with an service that leaves outside of the GPU machine. The lifecycle of this service is aligned with the training. To facilitate this, I have activated the pytorch plugin in Volcano and added an additional task with its corresponding replicas. Below, you will find a minimal job manifest illustrating the structure:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: multi-node-with-extra
spec:
  schedulerName: volcano
  queue: default
  maxRetry: 1
  ttlSecondsAfterFinished: 300
  plugins:
    pytorch: [--master=master, --worker=worker, --port=23456]
  tasks:
  - replicas: 1
    name: master
    template:
      spec:
        containers:
        - name: main
          image: alpine
          command:
            - printenv

  - replicas: 3
    name: worker
    template:
      spec:
        containers:
        - name: main
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - printenv

  - replicas: 4
    name: extras
    template:
      spec:
        containers:
        - name: main
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - printenv
```

### Describe the results you received and expected

The challenge I am encountering is that the `WORLD_SIZE` environment variable is:
1. being set across all pods. Just like `RANK`, I was expecting it to only be available on the master and workers.
2. its value is being set to 8, instead of the expected 4 (1+3). My assumption was that the PyTorch plugin would calculate the world size based on the aggregate number of replicas for the master and worker, as specified by `--master=master --worker=worker`. In short, `WORLD_SIZE=max(RANK)+1`.

I tried to manually add `WORLD_SIZE` to the container specs for the master and workers, but this env get overridden by Volcano.

I would appreciate any guidance or insights on whether this is intentional or not, and what would be a workaround to inject the expected `WORLD_SIZE` value into the different pods. Thank you in advance for your help! 

### What version of Volcano are you using?

1.11
