### ISSUE TITLE
an ability to include / exclude nodes for users when scheduling a job

### ISSUE THREAD

**Issue by sfc-gh-sbekman** [volcano-sh/volcano#4259]
### What is the problem you're trying to solve

slurm has a convenient `--include node_x` and `--exclude node_y` when requesting a job. 

With volcano we users have to wait for admins to solve problem with nodes, while 
1. there are perfectly good available nodes sitting there, but we can't tell k8s to select those, and the scheduler insists on using an node that say doesn't match the requested resources
2. when nodes break in non-obvious way - delete/apply usually results in giving the user the exact same broken node - once the user knows the node isn't good they should be able not to get it again on rescheduling.

It's have been much easier for us users if we could optionally tell the scheduler to include a node we know is available and exclude a node we know has a problem, while waiting for admins to resolve things and unblocking our work.

Thank you!

**Comment by JesseStutler** [comment]
Hi @sfc-gh-sbekman, thanks for your feature issue. Are these `--include` and `--exclude` user-controlled? Is the current nodeAffinity or nodeSelector not meeting your needs?

**Comment by sfc-gh-sbekman** [comment]
user-controlled yes.

Let's say I have 4 nodes that are all exactly the same (other than ip), and they are n1, n2, n3, n4. And I want to schedule a 2-node job.

How do I tell the scheduler:
1. to schedule n1,n2
2. to schedule any but n1,n2

i.e. 2 different scenarios.

can this be done via nodeAffinity or nodeSelector? 

Thank you, Jesse.

**Comment by JesseStutler** [comment]
```yaml
#1. Scenario 1, only n1,n2
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n1
          - n2

# 2. Scenario 2, not on n1,n2
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - n1
          - n2
```
Like this,  can nodeAffinity meet your need?

**Comment by sfc-gh-sbekman** [comment]
If you're saying that it should work then  thank you, Jesse.  That would be very useful!

Though that's very verbose. Can these things be added to the CLI instead of the yml file, as in:

```
kubectl apply -f job.yml -c affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms. matchExpressions.... ... n1,n2 
```

or something like that?

Alternatively is there a way to remap a big yaml section to a short key? i.e. could I declare all of the above into an alias or something of the kind? i.e. converting the above into something like:

```
cli_alias: include_nodes:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
```
and then it could be invoked from CLI?

```
kubectl apply -f job.yml -c include_nodes n1,n2
```

My apologies if I'm reinventing the wheel - I'm new to k8s/volcano and I super-appreciate your insight, Jesse.

**Comment by JesseStutler** [comment]
> If you're saying that it should work then thank you, Jesse. That would be very useful!
> 
> Though that's very verbose. Can these things be added to the CLI instead of the yml file, as in:
> 
> ```
> kubectl apply -f job.yml -c affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms. matchExpressions.... ... n1,n2 
> ```
> 
> or something like that? Ideally I won't want to change the template yml so that it could be easily shared and invoke the overrides from the CLI instead.
> 
> Alternatively is there a way to remap a big yaml section to a short key? i.e. could I declare all of the above into an alias or something of the kind? i.e. converting the above into something like:
> 
> ```
> cli_alias: include_nodes:
>   affinity:
>     nodeAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>         nodeSelectorTerms:
>         - matchExpressions:
>           - key: kubernetes.io/hostname
>             operator: In
>             values:
> ```
> 
> and then it could be invoked from CLI?
> 
> ```
> kubectl apply -f job.yml -c include_nodes n1,n2
> ```
> 
> My apologies if I'm reinventing the wheel - I'm new to k8s/volcano and I super-appreciate your insight, Jesse.

k8s prefers to use yaml instead of cli, and afik kubectl didn't have such a -c parameter. If you are using volcanojob, the example yaml for configuring a vcjob can be as follows:
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-job-n1-n2
spec:
  minAvailable: 1
  schedulerName: volcano
  tasks:
    - name: "task-n1-n2"
      replicas: 1
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - n1
                    - n2
          containers:
            - name: busybox
              image: busybox
              command: ["echo", "Running on n1 or n2"]
          restartPolicy: OnFailure
```
