### ISSUE TITLE
[Hierarchical Queues] Optimize parent node checks in hierarchical queues

### ISSUE THREAD

**Issue by XbaoWu** [volcano-sh/volcano#4306]
### What is the problem you're trying to solve

Allow creation of child nodes for parent queues that already have children.

### Describe the solution you'd like

When checking the parent node, allow creation of additional child nodes if children already exist.
Check if the parent node has children,
1. true
   child node can be created.
2. false
   child node creation is permitted based on whether a task is running under the parent queue.

### Additional context

**Why we need it**
This improves the creation of child nodes in large multi-level queues.

**Reproduction process**
1. Create the following queues:
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: tenant-a
spec:
  reclaimable: true
  parent: root
  capability:
    cpu: 4
    memory: 4Gi 
  deserved:
    cpu: 4
    memory: 4Gi
---
# The parent of tenant-a-q1 is tenant-a
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: tenant-a-q1
spec:
  reclaimable: true
  parent: tenant-a
  # You can set deserved values as needed. If the allocated resources of the queue exceed the deserved value, tasks in the queue can be reclaimed.
  capability:
    cpu: 4
    memory: 4Gi
  deserved:
    cpu: 2
    memory: 2Gi
```

2. Submit the task to queue tenant-a-q1
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: tenant-a-q1
  annotations:
    scheduling.volcano.sh/queue-name: tenant-a-q1
spec:
  schedulerName: volcano
  containers:
    - name: test-container
      image: busybox:stable
      imagePullPolicy: IfNotPresent
      command: ["sleep", "600s"]
      resources:
        requests:
          cpu: 1
          memory: 1Gi
```

3. Create child queue tenant-a-q2 under node tenant-a:
```bash
$ kubectl apply -f tenant-a-q2.yaml
Error from server: error when creating "tenant-a-q2.yaml": admission webhook "validatequeue.volcano.sh" denied the request: queue tenant-a cannot be the parent queue of queue tenant-a-q2 because it has allocated Pods: 1
```
