### ISSUE TITLE
When some scalar resources are 0 in deserved, hierarychical queues validation can not pass

### ISSUE THREAD

**Issue by JesseStutler** [volcano-sh/volcano#4346]
### Description

Configure the hierarchical queue, if the scalar resources is set to 0 in deserved of queue(for example, configure `hugepages-1Gi: 0` in deserved), the hierarchical queue validation will fail, and it will report: `queue <%s> deserved resources <%s> are less than the sum of its child queues' deserved resources <%s>` error

### Steps to reproduce the issue

0. Set capacity plugin and set `enableHierarchy` to true
1. Create a parent queue, and set some scalar resources to 0 (For example, set `hugepages-1Gi:0`) in deserved, an example yaml:
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: parent-queue
spec:
  reclaimable: true
  weight: 1
  parent: root
  deserved:
    memory: "10Gi"
    ephemeral-storage: 40m
    nvidia.com/gpu: "32"
    nvidia.com/hostdev: "36"
    hugepages-1Gi: "0"
    pods: "50"
    cpu: "4"
  guarantee:
    resource:
      memory: "10Gi"
      ephemeral-storage: 40m
      nvidia.com/gpu: "32"
      nvidia.com/hostdev: "36"
      hugepages-1Gi: "0"
      pods: "50"
      cpu: "4"

```
2. Create a child queue, similarly, set some scalar resources to 0 in deserved
3. Check the logs

Then the logs in scheduler will have these error logs:
```
queue <%s> deserved resources <%s> are less than the sum of its child queues' deserved resources <%s>"
```

### Describe the results you received and expected

Hierarchical queues validation can successfully pass

### What version of Volcano are you using?

v1.11.2/v1.12.1
