### ISSUE TITLE
Inconsistent Scheduling with NodeSelector and NodeAffinity in Volcano Scheduler

### ISSUE THREAD

**Issue by nitindhiman314e** [volcano-sh/volcano#4390]
### Description

I am experiencing an issue where the Volcano scheduler does not consistently respect the nodeSelector and nodeAffinity fields in my Kubernetes deployment. Initially, the scheduler attempts to place the pod on nodes that do not match the specified labels. After some time and failures, it eventually schedules the pod on the correctly labeled node. This behavior suggests that the scheduler might be prioritizing nodes based on usage rather than respecting the nodeSelector or nodeAffinity constraints from the start.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Expected Behavior:

The scheduler should respect nodeSelector and nodeAffinity constraints from the start, scheduling pods only on nodes with the specified labels.

Actual Behavior:

The scheduler initially attempts to place pods on nodes without the specified labels, seemingly prioritizing low usage nodes before respecting the label constraints.

### What version of Volcano are you using?

v1.11.1

### Any other relevant information

Scheduler Configuration:

```
actions: "enqueue, allocate, backfill"
  tiers:
    - plugins:
        - name: priority
        - name: gang
          enablePreemptable: false
        - name: conformance
        - name: usage
          enablePredicate: false
          arguments:
            usage.weight: 5
            cpu.weight: 1
            memory.weight: 1
            thresholds:
              cpu: 80    
              mem: 70
  metrics:
    type: prometheus
    address: http://vmselect-vm-cluster.monitoring-system.svc.cluster.local:8481/select/0/prometheus
    interval: 30s
```

Steps to Reproduce:

1. Deploy a Kubernetes Deployment with the following nodeSelector:

```
spec:
     template:
       spec:
         schedulerName: volcano
         nodeSelector:
           app: "abc"
```

2. Observe that the pod initially attempts to schedule on nodes without the app=314e label, taking time before eventually scheduling on the correct node.

3. Change the deployment to use nodeAffinity:

```
   spec:
     template:
       spec:
         schedulerName: volcano
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: app
                   operator: In
                   values: ["abc"]
```

4. Observe similar behavior where the pod initially attempts to schedule on incorrectly labeled nodes.

Please use below Volcano Scheduler logs:

`{"file":"/var/log/pods/volcano-system_volcano-scheduler-644c97dc-pjbst_719ddb9f-104b-483e-8451-575c8ec06adf/volcano-scheduler/0.log","kubernetes":{"container_id":"containerd://03ef3a4c99428fxxxxxb1b8e9831bbe32404e2a4e035db","container_image":"docker.io/volcanosh/vc-scheduler:v1.11.1","container_image_id":"docker.io/volcanosh/vc-scheduler@sha256:b50b31efb47d3axxxxx29c9fcc4b3ac7dd3866ed56de","container_name":"volcano-scheduler","namespace_labels":{"kubernetes.io/metadata.name":"volcano-system","name":"volcano-system"},"node_labels":{"app":"314e","beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"xx-02","kubernetes.io/os":"linux","node-role.kubernetes.io/control-plane":"","node.kubernetes.io/exclude-from-external-load-balancers":"","storageclass":"longhorn","svc":"xxxx-service"},"pod_annotations":{"kubectl.kubernetes.io/restartedAt":"2025-06-04T01:30:13.706Z"},"pod_ip":"xxxx","pod_ips":["xxx"],"pod_labels":{"app":"volcano-scheduler","pod-template-hash":"644c97dc"},"pod_name":"volcano-scheduler-644c97dc-pjbst","pod_namespace":"volcano-system","pod_node_name":"xx-02","pod_owner":"ReplicaSet/volcano-scheduler-644c97dc","pod_uid":"xxx-104b-483e-xxx-575c8ec06adf"},"message":"I0618 12:32:49.891584       1 binder.go:396] \"AssumePodVolumes: all PVCs bound and nothing to do\" pod=\"inttest/xxxx-cli-585c8d66f-tftfp\" node=\"it-xxx-runner\"","source_type":"kubernetes_logs","stream":"stderr"}`

	
`{"file":"/var/log/pods/volcano-system_volcano-scheduler-644c97dc-pjbst_719ddb9f-104b-483e-8451-575c8ec06adf/volcano-scheduler/0.log","kubernetes":{"container_id":"containerd://03ef3a4c99xxx2b2979b1b8e9831bbe3240xxxx35db","container_image":"docker.io/volcanosh/vc-scheduler:v1.11.1","container_image_id":"docker.io/volcanosh/vc-scheduler@sha256:b50b31efb47d3ac8xxxxa3d79ab2229c9fcc4b3ac7dd3866ed56de","container_name":"volcano-scheduler","namespace_labels":{"kubernetes.io/metadata.name":"volcano-system","name":"volcano-system"},"node_labels":{"app":"314e","beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"xx-02","kubernetes.io/os":"linux","node-role.kubernetes.io/control-plane":"","node.kubernetes.io/exclude-from-external-load-balancers":"","storageclass":"longhorn","svc":"xxx-service"},"pod_annotations":{"kubectl.kubernetes.io/restartedAt":"2025-06-04T01:30:13.706Z"},"pod_ip":"xxx","pod_ips":["xxx"],"pod_labels":{"app":"volcano-scheduler","pod-template-hash":"644c97dc"},"pod_name":"volcano-scheduler-644c97dc-pjbst","pod_namespace":"volcano-system","pod_node_name":"xx-02","pod_owner":"ReplicaSet/volcano-scheduler-644c97dc","pod_uid":"xx-104b-483e-8451-xxx"},"message":"I0618 12:32:49.891580       1 binder.go:388] \"AssumePodVolumes\" pod=\"inttest/xxx-cli-585c8d66f-tftfp\" node=\"it-github-runner\"","source_type":"kubernetes_logs","stream":"stderr"}`
