### ISSUE TITLE
How to recognize GPU Type in Queue Resource

### ISSUE THREAD

**Issue by Wonki4** [volcano-sh/volcano#4404]
### Please describe your problem in detail

I have many types of GPU in GPU Cluster and want to control these GPU resource in Queue.
For example, there are 3 three type of GPU (T4, V100, A100). I set up the servers like this.

V100
```
kind: Node
metadata:
  labels:
    gpu: "true"
    gpu-type: V100 # Check
    nvidia.com/gpu: "true"
  name: v100server1
spec:
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
    value: "true"
  allocatable:
    cpu: 95400m
    ephemeral-storage: "144884367121"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 514651576Ki
    nvidia.com/gpu: "10"
    pods: "110"
  capacity:
    cpu: "96"
    ephemeral-storage: 153525Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 527336888Ki
    nvidia.com/gpu: "10"
    pods: "110"
```

T4
```
kind: Node
metadata:
  labels:
    gpu: "true"
    gpu-type: T4 # Check
    nvidia.com/gpu: "true"
  name: t4server1
spec:
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
    value: "true"
  allocatable:
    cpu: 95400m
    ephemeral-storage: "144884367121"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 514651576Ki
    nvidia.com/gpu: "10"
    pods: "110"
  capacity:
    cpu: "96"
    ephemeral-storage: 153525Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 527336888Ki
    nvidia.com/gpu: "10"
    pods: "110"
```

A100
```
kind: Node
metadata:
  labels:
    gpu: "true"
    gpu-type: A100 # Check
    nvidia.com/gpu: "true"
  name: a100server1
spec:
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
    value: "true"
  allocatable:
    cpu: 95400m
    ephemeral-storage: "144884367121"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 514651576Ki
    nvidia.com/gpu: "10"
    pods: "110"
  capacity:
    cpu: "96"
    ephemeral-storage: 153525Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 527336888Ki
    nvidia.com/gpu: "10"
    pods: "110"
```

The only way to recognize gpu type is the labels.
How could the queue recognize the labels or gpu type? I can't find docs or example in this repo.
