### ISSUE TITLE
Fail to get /etc/volcano/.ssh

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#450]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
when i use ssh(no-root=true) and svc plugins, there is no `/etc/volcano/.ssh`.

**What you expected to happen**:
`/etc/volcano/.ssh` existed.

**How to reproduce it (as minimally and precisely as possible)**:
use ssh(no-root=true) and svc plugins

**Anything else we need to know?**:

**Environment**:
- Volcano Version:v0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
@wangyuqing4 , would you help to check that?

**Comment by wangyuqing4** [comment]
@chenyangxueHDU , i check it, i can see file (/etc/volcano/.ssh),  use **ssh: ["--no-root"]**, can you help to check it?

**Comment by k82cn** [comment]
@chenyangxueHDU , would you help to share the yaml file and the log of controller?

**Comment by chenyangxueHDU** [comment]
> @chenyangxueHDU , would you help to share the yaml file and the log of controller?

sure.

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: mxnet-job
spec:
  minAvailable: 5
  schedulerName: volcano
  policies:
  - event: PodEvicted
    action: RestartJob
  - event: PodFailed
    action: RestartJob
  plugins:
    svc: []
    ssh:
    - "--no-root=true"
  tasks:
  - replicas: 2
    name: worker
    template:
      spec:
        imagePullSecrets:
        - name: default-secret
        containers:
        - image: sivanzcw/mxnet-train-mnist:cpu
          args:
          - --kv-store=dist_sync
          imagePullPolicy: IfNotPresent
          name: mxnet
          env:
          - name: DMLC_PS_ROOT_PORT
            value: "9000"
          - name: DMLC_PS_ROOT_URI
            value: mxnet-job-scheduler-0.mxnet-job
          - name: DMLC_NUM_SERVER
            value: "2"
          - name: DMLC_NUM_WORKER
            value: "2"
          - name: DMLC_ROLE
            value: "worker"
          - name: DMLC_USE_KUBERNETES
            value: "1"
        restartPolicy: OnFailure
  - replicas: 2
    name: server
    template:
      spec:
        imagePullSecrets:
        - name: default-secret
        containers:
        - image: sivanzcw/mxnet-train-mnist:cpu
          imagePullPolicy: IfNotPresent
          name: mxnet
          env:
          - name: DMLC_PS_ROOT_PORT
            value: "9000"
          - name: DMLC_PS_ROOT_URI
            value: mxnet-job-scheduler-0.mxnet-job
          - name: DMLC_NUM_SERVER
            value: "2"
          - name: DMLC_NUM_WORKER
            value: "2"
          - name: DMLC_ROLE
            value: "server"
          - name: DMLC_USE_KUBERNETES
            value: "1"
        restartPolicy: OnFailure
  - replicas: 1
    name: scheduler
    template:
      spec:
        imagePullSecrets:
        - name: default-secret
        containers:
        - image: sivanzcw/mxnet-train-mnist:cpu
          imagePullPolicy: IfNotPresent
          name: mxnet
          env:
          - name: DMLC_PS_ROOT_PORT
            value: "9000"
          - name: DMLC_PS_ROOT_URI
            value: mxnet-job-scheduler-0.mxnet-job
          - name: DMLC_NUM_SERVER
            value: "2"
          - name: DMLC_NUM_WORKER
            value: "2"
          - name: DMLC_ROLE
            value: "scheduler"
          - name: DMLC_USE_KUBERNETES
            value: "1"
        restartPolicy: OnFailure
```
