### ISSUE TITLE
Podgroup conditions set wrong

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#457]
When i tested MPI, and I used volcano to schedule 3 pods by creating a podgroup. 

After running up, then one pod exited. And there are now only 2 pods running. But i can see the podgroup.status.conditions is wrong.

```
  status:
    conditions:
    - lastTransitionTime: "2019-09-19T04:13:19Z"
      message: '1/2 tasks in gang unschedulable: job is not ready, 2 Running, 3 minAvailable.'
      reason: NotEnoughResources
      status: "True"
      transitionID: d02318a0-da93-11e9-ad67-fadd1cf7d37b
      type: Unschedulable
    phase: Unknown
    running: 2

```

It has already scheduled all the pods, this status is absolutely not what i expect.
