### ISSUE TITLE
In the k8s cluster, PDB does not set MinAvailable, causing job_info.setpdb (), panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by chenshaojin** [volcano-sh/volcano#522]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
>I am trying to install volcano, but scheduler is not running. The log is as follows:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x119d737]

goroutine 259 [running]:
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x137efa0, 0x2406db0)
	/Users/arvin/GoProjects/go1.12.6/src/runtime/panic.go:522 +0x1b5
volcano.sh/volcano/pkg/scheduler/api.(*JobInfo).SetPDB(...)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/pkg/scheduler/api/job_info.go:201
volcano.sh/volcano/pkg/scheduler/cache.(*SchedulerCache).setPDB(0xc00019a700, 0xc000936000, 0xc00019a700, 0xc0001bc240)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/pkg/scheduler/cache/event_handlers.go:591 +0x187
volcano.sh/volcano/pkg/scheduler/cache.(*SchedulerCache).AddPDB(0xc00019a700, 0x1519dc0, 0xc000936000)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/pkg/scheduler/cache/event_handlers.go:631 +0xb5
volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache/controller.go:195
volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x42c96c, 0xc0004395e8, 0x0)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554 +0x26d
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc00074de38, 0x42c47f, 0xc000452120)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0xde
volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x89
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000439768)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00074df68, 0xdf8475800, 0x0, 0x1, 0xc000454060)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0001b0600)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x9c
volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002347d0, 0xc000450020)
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/Users/arvin/GoProjects/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```
> So I check the error code in the source code as follows:
```
// SetPDB sets PDB to a job
func (ji *JobInfo) SetPDB(pdb *policyv1.PodDisruptionBudget) {
	ji.Name = pdb.Name
->	ji.MinAvailable = pdb.Spec.MinAvailable.IntVal
	ji.Namespace = pdb.Namespace

	ji.CreationTimestamp = pdb.GetCreationTimestamp()
	ji.PDB = pdb
}
```
>So I looked at the PDB created in the k8s cluster and found that one of them was not MinAvailable：
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  name: quickstart-es-default
  namespace: default
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: quickstart
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name: quickstart

```

**What you expected to happen**:
>If the MinAvailable parameter is not available, set a default value of 0 ?
