### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by silenceli** [volcano-sh/volcano#648]
1. What's the different from vcctl and kubectl? why we need vcctl?
2. Why vcctl **only** support queue/job?
3. In master branch install yaml configure file, There are two Queue CRD. Is this duplicate?
4. As the document mentioned, volcano support podgroup/command，I don't know how to create/list/use these CRD resource
5. I don't know why volcano-admission will do something for pod. volcano focus on batch scheduler, why volcano validate/admiss for pod?
6. Queue CRD now not support quota, but this feature is very important for us

looking forward to your reply, thanks

**Comment by hzxuzhonghu** [comment]
>What's the different from vcctl and kubectl? why we need vcctl?

vcctl is to provide a high level useer tool, actually if you are familiar with `kubectl`, can use it directly.''

>Why vcctl only support queue/job?

Supporting other resources such as podgroup is on schedule, but is low priority

>In master branch install yaml configure file, There are two Queue CRD. Is this duplicate?

Good catch


> As the document mentioned, volcano support podgroup/command，I don't know how to create/list/use these CRD resource

let's take queue as an example 
running ` kubectl get queues.scheduling.sigs.dev -oyaml`, you can see the output
```
...
spec:
  conversion:
    strategy: None
  group: scheduling.sigs.dev
  names:
    kind: Queue
    listKind: QueueList
    plural: queues
    shortNames:
    - q
    - queue-v1alpha2
    singular: queue
  preserveUnknownFields: true
  scope: Cluster
...
```

And you can see the `shortNames`, and then try kubectl get/create q
