### ISSUE TITLE
Queue capability can overuse

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#834]
/kind bug

**What happened**:

I have limited the queue capability, but all jobs can be scheduled!!!

![1590466546(1)](https://user-images.githubusercontent.com/38552291/82860187-68553680-9f4b-11ea-99ca-d3cad0844693.png)

`queue1` capability is 2 CPU, but can run 3 jobs each with 1CPU

**What you expected to happen**:

Only 2 jobs can be scheduled

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue1
spec:
  weight: 1
  capability:
    cpu: 2
    memory: 4Gi
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job1
  labels:
    volcano.sh/job-type: ElasticJob
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  tasks:
  - name: worker
    replicas: 1
    template:
      spec:
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 5
        containers:
        - image: ubuntu:16.04
          name: worker
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          args: ["sleep", "1000"]
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job2
  labels:
    volcano.sh/job-type: ElasticJob
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  tasks:
  - name: worker
    replicas: 1
    template:
      spec:
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 5
        containers:
        - image: ubuntu:16.04
          name: worker
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          args: ["sleep", "1000"]
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job3
  labels:
    volcano.sh/job-type: ElasticJob
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  tasks:
  - name: worker
    replicas: 1
    template:
      spec:
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 5
        containers:
        - image: ubuntu:16.04
          name: worker
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          args: ["sleep", "1000"]
```

or replicas set 3 

```yaml
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue1
spec:
  weight: 1
  capability:
    cpu: 2
    memory: 4Gi
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job1
  labels:
    volcano.sh/job-type: ElasticJob
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  tasks:
  - name: worker
    replicas: 3
    template:
      spec:
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 5
        containers:
        - image: ubuntu:16.04
          name: worker
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          args: ["sleep", "1000"]
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 
0.4
- Kubernetes version (use `kubectl version`): 
v1.18.2
- OS (e.g. from /etc/os-release): 
Ubuntu18.04
- Kernel (e.g. `uname -a`): 
Linux 4.18.0-25-generic

**Comment by hzxuzhonghu** [comment]
cc @k82cn

**Comment by hzxuzhonghu** [comment]
Duplicate with https://github.com/volcano-sh/volcano/issues/921, fixed in v0.4.2

**Comment by zen-xu** [comment]
@hzxuzhonghu 
I don't think #921 has fixed all this problem.
I have try to use v0.4.2, queue still can overuse when job specify with **replicas case**
```yaml
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue1
spec:
  weight: 1
  capability:
    cpu: 2
    memory: 4Gi
---
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job1
  labels:
    volcano.sh/job-type: ElasticJob
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: queue1
  tasks:
  - name: worker
    replicas: 3
    template:
      spec:
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 5
        containers:
        - image: ubuntu:16.04
          name: worker
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          args: ["sleep", "1000"]
```
