### ISSUE TITLE
Support BytePS in volcano

### ISSUE THREAD

**Issue by jasonliu747** [volcano-sh/volcano#866]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

[BytePS](https://github.com/bytedance/byteps) is a high performance and generic framework for distributed DNN training. As discussed in WeChat group, it would be awesome that volcano could support BytePS. 
Opening this issue to track the progress.

**Comment by hzxuzhonghu** [comment]
Yeah, pr is welcome. We have been working on 1.0 release, which will be scheduled by the end of this month.

**Comment by jasonliu747** [comment]
@hzxuzhonghu Consider adding this feature request into v1.0 milestone?

**Comment by hzxuzhonghu** [comment]
@jasonliu747 Could you add an example here?

**Comment by jasonliu747** [comment]
Sure, made a few changes on mxnet-operator so it could support BytePS. Here is an example.
```
apiVersion: "kubeflow.org/v1beta1"
kind: "MXJob"
metadata:
  name: "byteps-mxnet-job"
spec:
  jobMode: MXTrain
  cleanPodPolicy: Running
  successPolicy: AllWorkers
  mxReplicaSpecs:
    Scheduler:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet
              command: ["bpslaunch"]
    Server:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet
              command: ["bpslaunch"]
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet
              command: ["bpslaunch"]
              args: ["python3", "/usr/local/byteps/example/mxnet/train_imagenet_byteps.py", "--benchmark", "1", "--batch-size=32"]
              volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              resources:
                limits:
                  nvidia.com/gpu: 8
          volumes:
          - name: dshm
            emptyDir: 
              medium: Memory
```
