### ISSUE TITLE
can volcano svc plugin inject the current host env ?

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#868]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:

currently, i can generate the current host string in container, i.e. by `volcano-job-name`, `volcano task group name` and the index of task, i'd like the current host can generate directly by the yaml

**What you expected to happen**:

```
              - name: MA_VJ_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['volcano.sh/job-name']
              - name: MA_TASKGROUP_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['volcano.sh/task-spec']
              - name: MA_CURRENT_HOST
                 value: $(MA_VJ_NAME)-$(MA_TASKGROUP_NAME)-$(VC_TASK_INDEX)
```

and `MA_CURRENT_HOST` indicates the current host of container
