### ISSUE TITLE
default Queue “default” and webhook startup sequence

### ISSUE THREAD

**Issue by QizhouYang** [volcano-sh/volcano#882]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
1. first , start volcano-scheduler，After, start volcano-admission
default queue information:

```
spec:
  weight: 1
status:
  state: Open
```

2. start volcano-admission，After, start volcano-scheduler
default queue information:

```
spec:
  reclaimable: true
  state: Open
  weight: 1
status:
  state: Open
```

**What you expected to happen**:
Always this information
```
spec:
  reclaimable: true
  state: Open
  weight: 1
status:
  state: Open
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): v1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
