### ISSUE TITLE
how to avoid pod deletion after job finished

### ISSUE THREAD

**Issue by nicklhy** [volcano-sh/volcano#916]
Recently, I met a problem about collecting worker pods' logs when using volcano.

For instance, I have a distributed job which includes 1 master pod and 4 worker pods. After the job finished, I may noticed volcano only let the master pod exists in "Completed" status while the other 4 worker pods being deleted directly. Is there a way to avoid the deletion and make all the pods in "Completed" status ?

----------
I also tried to set the Job and Tasks' policies like below:
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: mxnet-frcnn
  namespace: mdt
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: TaskCompleted
      action: CompleteJob
    - event: PodEvicted
      action: AbortJob
    - event: PodFailed
      action: AbortJob
  plugins:
    svc: []
  tasks:
  - replicas: 2
    name: worker
    policies:
      - event: TaskCompleted
        action: CompleteJob
      - event: PodEvicted
        action: AbortJob
      - event: PodFailed
        action: AbortJob
    template:
      spec:
        containers:
        - image: xxx
          command:
            - /bin/bash
            - -c
            - |
              set -o pipefail;
              python3 tools/train_faster_rcnn.py
          imagePullPolicy: IfNotPresent
          name: mxnet-worker
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /mnt/local_disk
              name: local-disk
          resources:
            limits:
              nvidia.com/gpu: 2

...
```
But after the job finished, I found worker 0 was deleted while worker 1 still exists.
```shell
$ kubectl get pods -n mdt
NAME                          READY   STATUS      RESTARTS   AGE
mx-utest-frcnn0-scheduler-0   0/1     Completed   0          10m
mx-utest-frcnn0-worker-1      0/2     Completed   0          10m
```
Can someone briefly explain why this happened and how exactly should I do to precisely control pod clean-up behavior for all pods ?
