### ISSUE TITLE
Volcano job spec.SchedulerName does not take effect

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#943]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

create a volcano job with schedulerName set to `volcano`, but the pod is scheduled by default scheduler, we expect it is scheduled by volcano scheduler.

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 3
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure

```
